/*
Server API

# Overview Fingerprint Server API allows you to get, search, and update Events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device.

API version: 4
Contact: support@fingerprint.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fingerprint

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the BrowserDetails type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BrowserDetails{}

// BrowserDetails struct for BrowserDetails
type BrowserDetails struct {
	BrowserName         string `json:"browser_name"`
	BrowserMajorVersion string `json:"browser_major_version"`
	BrowserFullVersion  string `json:"browser_full_version"`
	Os                  string `json:"os"`
	OsVersion           string `json:"os_version"`
	Device              string `json:"device"`
}

type _BrowserDetails BrowserDetails

// NewBrowserDetails instantiates a new BrowserDetails object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBrowserDetails(browserName string, browserMajorVersion string, browserFullVersion string, os string, osVersion string, device string) *BrowserDetails {
	this := BrowserDetails{}
	this.BrowserName = browserName
	this.BrowserMajorVersion = browserMajorVersion
	this.BrowserFullVersion = browserFullVersion
	this.Os = os
	this.OsVersion = osVersion
	this.Device = device
	return &this
}

// NewBrowserDetailsWithDefaults instantiates a new BrowserDetails object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBrowserDetailsWithDefaults() *BrowserDetails {
	this := BrowserDetails{}
	return &this
}

// GetBrowserName returns the BrowserName field value
func (o *BrowserDetails) GetBrowserName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BrowserName
}

// GetBrowserNameOk returns a tuple with the BrowserName field value
// and a boolean to check if the value has been set.
func (o *BrowserDetails) GetBrowserNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BrowserName, true
}

// SetBrowserName sets field value
func (o *BrowserDetails) SetBrowserName(v string) {
	o.BrowserName = v
}

// GetBrowserMajorVersion returns the BrowserMajorVersion field value
func (o *BrowserDetails) GetBrowserMajorVersion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BrowserMajorVersion
}

// GetBrowserMajorVersionOk returns a tuple with the BrowserMajorVersion field value
// and a boolean to check if the value has been set.
func (o *BrowserDetails) GetBrowserMajorVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BrowserMajorVersion, true
}

// SetBrowserMajorVersion sets field value
func (o *BrowserDetails) SetBrowserMajorVersion(v string) {
	o.BrowserMajorVersion = v
}

// GetBrowserFullVersion returns the BrowserFullVersion field value
func (o *BrowserDetails) GetBrowserFullVersion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BrowserFullVersion
}

// GetBrowserFullVersionOk returns a tuple with the BrowserFullVersion field value
// and a boolean to check if the value has been set.
func (o *BrowserDetails) GetBrowserFullVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BrowserFullVersion, true
}

// SetBrowserFullVersion sets field value
func (o *BrowserDetails) SetBrowserFullVersion(v string) {
	o.BrowserFullVersion = v
}

// GetOs returns the Os field value
func (o *BrowserDetails) GetOs() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Os
}

// GetOsOk returns a tuple with the Os field value
// and a boolean to check if the value has been set.
func (o *BrowserDetails) GetOsOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Os, true
}

// SetOs sets field value
func (o *BrowserDetails) SetOs(v string) {
	o.Os = v
}

// GetOsVersion returns the OsVersion field value
func (o *BrowserDetails) GetOsVersion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OsVersion
}

// GetOsVersionOk returns a tuple with the OsVersion field value
// and a boolean to check if the value has been set.
func (o *BrowserDetails) GetOsVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OsVersion, true
}

// SetOsVersion sets field value
func (o *BrowserDetails) SetOsVersion(v string) {
	o.OsVersion = v
}

// GetDevice returns the Device field value
func (o *BrowserDetails) GetDevice() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Device
}

// GetDeviceOk returns a tuple with the Device field value
// and a boolean to check if the value has been set.
func (o *BrowserDetails) GetDeviceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Device, true
}

// SetDevice sets field value
func (o *BrowserDetails) SetDevice(v string) {
	o.Device = v
}

func (o BrowserDetails) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BrowserDetails) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["browser_name"] = o.BrowserName
	toSerialize["browser_major_version"] = o.BrowserMajorVersion
	toSerialize["browser_full_version"] = o.BrowserFullVersion
	toSerialize["os"] = o.Os
	toSerialize["os_version"] = o.OsVersion
	toSerialize["device"] = o.Device
	return toSerialize, nil
}

func (o *BrowserDetails) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"browser_name",
		"browser_major_version",
		"browser_full_version",
		"os",
		"os_version",
		"device",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBrowserDetails := _BrowserDetails{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBrowserDetails)

	if err != nil {
		return err
	}

	*o = BrowserDetails(varBrowserDetails)

	return err
}

type NullableBrowserDetails struct {
	value *BrowserDetails
	isSet bool
}

func (v NullableBrowserDetails) Get() *BrowserDetails {
	return v.value
}

func (v *NullableBrowserDetails) Set(val *BrowserDetails) {
	v.value = val
	v.isSet = true
}

func (v NullableBrowserDetails) IsSet() bool {
	return v.isSet
}

func (v *NullableBrowserDetails) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBrowserDetails(val *BrowserDetails) *NullableBrowserDetails {
	return &NullableBrowserDetails{value: val, isSet: true}
}

func (v NullableBrowserDetails) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBrowserDetails) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
