/*
Server API

Fingerprint Server API allows you to get, search, and update Events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device.

API version: 4
Contact: support@fingerprint.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fingerprint

import (
	"encoding/json"
)

// checks if the IPInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IPInfo{}

// IPInfo Details about the request IP address. Has separate fields for v4 and v6 IP address versions.
type IPInfo struct {
	V4 *IPInfoV4 `json:"v4,omitempty"`
	V6 *IPInfoV6 `json:"v6,omitempty"`
}

// NewIPInfo instantiates a new IPInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIPInfo() *IPInfo {
	this := IPInfo{}
	return &this
}

// NewIPInfoWithDefaults instantiates a new IPInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIPInfoWithDefaults() *IPInfo {
	this := IPInfo{}
	return &this
}

// GetV4 returns the V4 field value if set, zero value otherwise.
func (o *IPInfo) GetV4() IPInfoV4 {
	if o == nil || IsNil(o.V4) {
		var ret IPInfoV4
		return ret
	}
	return *o.V4
}

// GetV4Ok returns a tuple with the V4 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IPInfo) GetV4Ok() (*IPInfoV4, bool) {
	if o == nil || IsNil(o.V4) {
		return nil, false
	}
	return o.V4, true
}

// HasV4 returns a boolean if a field has been set.
func (o *IPInfo) HasV4() bool {
	if o != nil && !IsNil(o.V4) {
		return true
	}

	return false
}

// SetV4 gets a reference to the given IPInfoV4 and assigns it to the V4 field.
func (o *IPInfo) SetV4(v IPInfoV4) {
	o.V4 = &v
}

// GetV6 returns the V6 field value if set, zero value otherwise.
func (o *IPInfo) GetV6() IPInfoV6 {
	if o == nil || IsNil(o.V6) {
		var ret IPInfoV6
		return ret
	}
	return *o.V6
}

// GetV6Ok returns a tuple with the V6 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IPInfo) GetV6Ok() (*IPInfoV6, bool) {
	if o == nil || IsNil(o.V6) {
		return nil, false
	}
	return o.V6, true
}

// HasV6 returns a boolean if a field has been set.
func (o *IPInfo) HasV6() bool {
	if o != nil && !IsNil(o.V6) {
		return true
	}

	return false
}

// SetV6 gets a reference to the given IPInfoV6 and assigns it to the V6 field.
func (o *IPInfo) SetV6(v IPInfoV6) {
	o.V6 = &v
}

func (o IPInfo) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IPInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.V4) {
		toSerialize["v4"] = o.V4
	}
	if !IsNil(o.V6) {
		toSerialize["v6"] = o.V6
	}
	return toSerialize, nil
}

type NullableIPInfo struct {
	value *IPInfo
	isSet bool
}

func (v NullableIPInfo) Get() *IPInfo {
	return v.value
}

func (v *NullableIPInfo) Set(val *IPInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableIPInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableIPInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIPInfo(val *IPInfo) *NullableIPInfo {
	return &NullableIPInfo{value: val, isSet: true}
}

func (v NullableIPInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIPInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
