/*
Server API

Fingerprint Server API allows you to get, search, and update Events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device.

API version: 4
Contact: support@fingerprint.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fingerprint

import (
	"encoding/json"
)

// checks if the VPNMethods type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VPNMethods{}

// VPNMethods struct for VPNMethods
type VPNMethods struct {
	// The browser timezone doesn't match the timezone inferred from the request IP address.
	TimezoneMismatch *bool `json:"timezone_mismatch,omitempty"`
	// Request IP address is owned and used by a public VPN service provider.
	PublicVPN *bool `json:"public_vpn,omitempty"`
	// This method applies to mobile devices only. Indicates the result of additional methods used to detect a VPN in mobile devices.
	AuxiliaryMobile *bool `json:"auxiliary_mobile,omitempty"`
	// The browser runs on a different operating system than the operating system inferred from the request network signature.
	OsMismatch *bool `json:"os_mismatch,omitempty"`
	// Request IP address belongs to a relay service provider, indicating the use of relay services like [Apple Private relay](https://support.apple.com/en-us/102602) or [Cloudflare Warp](https://developers.cloudflare.com/warp-client/).  * Like VPNs, relay services anonymize the visitor's true IP address. * Unlike traditional VPNs, relay services don't let visitors spoof their location by choosing an exit node in a different country.  This field allows you to differentiate VPN users and relay service users in your fraud prevention logic.
	Relay                *bool `json:"relay,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _VPNMethods VPNMethods

// NewVPNMethods instantiates a new VPNMethods object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVPNMethods() *VPNMethods {
	this := VPNMethods{}
	return &this
}

// NewVPNMethodsWithDefaults instantiates a new VPNMethods object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVPNMethodsWithDefaults() *VPNMethods {
	this := VPNMethods{}
	return &this
}

// GetTimezoneMismatch returns the TimezoneMismatch field value if set, zero value otherwise.
func (o *VPNMethods) GetTimezoneMismatch() bool {
	if o == nil || IsNil(o.TimezoneMismatch) {
		var ret bool
		return ret
	}
	return *o.TimezoneMismatch
}

// GetTimezoneMismatchOk returns a tuple with the TimezoneMismatch field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VPNMethods) GetTimezoneMismatchOk() (*bool, bool) {
	if o == nil || IsNil(o.TimezoneMismatch) {
		return nil, false
	}
	return o.TimezoneMismatch, true
}

// HasTimezoneMismatch returns a boolean if a field has been set.
func (o *VPNMethods) HasTimezoneMismatch() bool {
	if o != nil && !IsNil(o.TimezoneMismatch) {
		return true
	}

	return false
}

// SetTimezoneMismatch gets a reference to the given bool and assigns it to the TimezoneMismatch field.
func (o *VPNMethods) SetTimezoneMismatch(v bool) {
	o.TimezoneMismatch = &v
}

// GetPublicVPN returns the PublicVPN field value if set, zero value otherwise.
func (o *VPNMethods) GetPublicVPN() bool {
	if o == nil || IsNil(o.PublicVPN) {
		var ret bool
		return ret
	}
	return *o.PublicVPN
}

// GetPublicVPNOk returns a tuple with the PublicVPN field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VPNMethods) GetPublicVPNOk() (*bool, bool) {
	if o == nil || IsNil(o.PublicVPN) {
		return nil, false
	}
	return o.PublicVPN, true
}

// HasPublicVPN returns a boolean if a field has been set.
func (o *VPNMethods) HasPublicVPN() bool {
	if o != nil && !IsNil(o.PublicVPN) {
		return true
	}

	return false
}

// SetPublicVPN gets a reference to the given bool and assigns it to the PublicVPN field.
func (o *VPNMethods) SetPublicVPN(v bool) {
	o.PublicVPN = &v
}

// GetAuxiliaryMobile returns the AuxiliaryMobile field value if set, zero value otherwise.
func (o *VPNMethods) GetAuxiliaryMobile() bool {
	if o == nil || IsNil(o.AuxiliaryMobile) {
		var ret bool
		return ret
	}
	return *o.AuxiliaryMobile
}

// GetAuxiliaryMobileOk returns a tuple with the AuxiliaryMobile field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VPNMethods) GetAuxiliaryMobileOk() (*bool, bool) {
	if o == nil || IsNil(o.AuxiliaryMobile) {
		return nil, false
	}
	return o.AuxiliaryMobile, true
}

// HasAuxiliaryMobile returns a boolean if a field has been set.
func (o *VPNMethods) HasAuxiliaryMobile() bool {
	if o != nil && !IsNil(o.AuxiliaryMobile) {
		return true
	}

	return false
}

// SetAuxiliaryMobile gets a reference to the given bool and assigns it to the AuxiliaryMobile field.
func (o *VPNMethods) SetAuxiliaryMobile(v bool) {
	o.AuxiliaryMobile = &v
}

// GetOsMismatch returns the OsMismatch field value if set, zero value otherwise.
func (o *VPNMethods) GetOsMismatch() bool {
	if o == nil || IsNil(o.OsMismatch) {
		var ret bool
		return ret
	}
	return *o.OsMismatch
}

// GetOsMismatchOk returns a tuple with the OsMismatch field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VPNMethods) GetOsMismatchOk() (*bool, bool) {
	if o == nil || IsNil(o.OsMismatch) {
		return nil, false
	}
	return o.OsMismatch, true
}

// HasOsMismatch returns a boolean if a field has been set.
func (o *VPNMethods) HasOsMismatch() bool {
	if o != nil && !IsNil(o.OsMismatch) {
		return true
	}

	return false
}

// SetOsMismatch gets a reference to the given bool and assigns it to the OsMismatch field.
func (o *VPNMethods) SetOsMismatch(v bool) {
	o.OsMismatch = &v
}

// GetRelay returns the Relay field value if set, zero value otherwise.
func (o *VPNMethods) GetRelay() bool {
	if o == nil || IsNil(o.Relay) {
		var ret bool
		return ret
	}
	return *o.Relay
}

// GetRelayOk returns a tuple with the Relay field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VPNMethods) GetRelayOk() (*bool, bool) {
	if o == nil || IsNil(o.Relay) {
		return nil, false
	}
	return o.Relay, true
}

// HasRelay returns a boolean if a field has been set.
func (o *VPNMethods) HasRelay() bool {
	if o != nil && !IsNil(o.Relay) {
		return true
	}

	return false
}

// SetRelay gets a reference to the given bool and assigns it to the Relay field.
func (o *VPNMethods) SetRelay(v bool) {
	o.Relay = &v
}

func (o VPNMethods) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VPNMethods) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TimezoneMismatch) {
		toSerialize["timezone_mismatch"] = o.TimezoneMismatch
	}
	if !IsNil(o.PublicVPN) {
		toSerialize["public_vpn"] = o.PublicVPN
	}
	if !IsNil(o.AuxiliaryMobile) {
		toSerialize["auxiliary_mobile"] = o.AuxiliaryMobile
	}
	if !IsNil(o.OsMismatch) {
		toSerialize["os_mismatch"] = o.OsMismatch
	}
	if !IsNil(o.Relay) {
		toSerialize["relay"] = o.Relay
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *VPNMethods) UnmarshalJSON(data []byte) (err error) {
	varVPNMethods := _VPNMethods{}

	err = json.Unmarshal(data, &varVPNMethods)

	if err != nil {
		return err
	}

	*o = VPNMethods(varVPNMethods)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "timezone_mismatch")
		delete(additionalProperties, "public_vpn")
		delete(additionalProperties, "auxiliary_mobile")
		delete(additionalProperties, "os_mismatch")
		delete(additionalProperties, "relay")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableVPNMethods struct {
	value *VPNMethods
	isSet bool
}

func (v NullableVPNMethods) Get() *VPNMethods {
	return v.value
}

func (v *NullableVPNMethods) Set(val *VPNMethods) {
	v.value = val
	v.isSet = true
}

func (v NullableVPNMethods) IsSet() bool {
	return v.isSet
}

func (v *NullableVPNMethods) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVPNMethods(val *VPNMethods) *NullableVPNMethods {
	return &NullableVPNMethods{value: val, isSet: true}
}

func (v NullableVPNMethods) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVPNMethods) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
