/*
Server API

# Overview Fingerprint Server API allows you to get, search, and update Events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device.

API version: 4
Contact: support@fingerprint.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fingerprint

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the GeolocationSubdivisionsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GeolocationSubdivisionsInner{}

// GeolocationSubdivisionsInner struct for GeolocationSubdivisionsInner
type GeolocationSubdivisionsInner struct {
	IsoCode string `json:"iso_code"`
	Name    string `json:"name"`
}

type _GeolocationSubdivisionsInner GeolocationSubdivisionsInner

// NewGeolocationSubdivisionsInner instantiates a new GeolocationSubdivisionsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGeolocationSubdivisionsInner(isoCode string, name string) *GeolocationSubdivisionsInner {
	this := GeolocationSubdivisionsInner{}
	this.IsoCode = isoCode
	this.Name = name
	return &this
}

// NewGeolocationSubdivisionsInnerWithDefaults instantiates a new GeolocationSubdivisionsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGeolocationSubdivisionsInnerWithDefaults() *GeolocationSubdivisionsInner {
	this := GeolocationSubdivisionsInner{}
	return &this
}

// GetIsoCode returns the IsoCode field value
func (o *GeolocationSubdivisionsInner) GetIsoCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.IsoCode
}

// GetIsoCodeOk returns a tuple with the IsoCode field value
// and a boolean to check if the value has been set.
func (o *GeolocationSubdivisionsInner) GetIsoCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsoCode, true
}

// SetIsoCode sets field value
func (o *GeolocationSubdivisionsInner) SetIsoCode(v string) {
	o.IsoCode = v
}

// GetName returns the Name field value
func (o *GeolocationSubdivisionsInner) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *GeolocationSubdivisionsInner) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *GeolocationSubdivisionsInner) SetName(v string) {
	o.Name = v
}

func (o GeolocationSubdivisionsInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GeolocationSubdivisionsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["iso_code"] = o.IsoCode
	toSerialize["name"] = o.Name
	return toSerialize, nil
}

func (o *GeolocationSubdivisionsInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"iso_code",
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGeolocationSubdivisionsInner := _GeolocationSubdivisionsInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGeolocationSubdivisionsInner)

	if err != nil {
		return err
	}

	*o = GeolocationSubdivisionsInner(varGeolocationSubdivisionsInner)

	return err
}

type NullableGeolocationSubdivisionsInner struct {
	value *GeolocationSubdivisionsInner
	isSet bool
}

func (v NullableGeolocationSubdivisionsInner) Get() *GeolocationSubdivisionsInner {
	return v.value
}

func (v *NullableGeolocationSubdivisionsInner) Set(val *GeolocationSubdivisionsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGeolocationSubdivisionsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGeolocationSubdivisionsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGeolocationSubdivisionsInner(val *GeolocationSubdivisionsInner) *NullableGeolocationSubdivisionsInner {
	return &NullableGeolocationSubdivisionsInner{value: val, isSet: true}
}

func (v NullableGeolocationSubdivisionsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGeolocationSubdivisionsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
