/*
Server API

# Overview Fingerprint Server API allows you to get, search, and update Events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device.

API version: 4
Contact: support@fingerprint.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fingerprint

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the IdentificationConfidence type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IdentificationConfidence{}

// IdentificationConfidence struct for IdentificationConfidence
type IdentificationConfidence struct {
	// The confidence score is a floating-point number between 0 and 1 that represents the probability of accurate identification.
	Score float64 `json:"score"`
	// The version name of the method used to calculate the Confidence score. This field is only present for customers who opted in to an alternative calculation method.
	Version *string `json:"version,omitempty"`
	Comment *string `json:"comment,omitempty"`
}

type _IdentificationConfidence IdentificationConfidence

// NewIdentificationConfidence instantiates a new IdentificationConfidence object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIdentificationConfidence(score float64) *IdentificationConfidence {
	this := IdentificationConfidence{}
	this.Score = score
	return &this
}

// NewIdentificationConfidenceWithDefaults instantiates a new IdentificationConfidence object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIdentificationConfidenceWithDefaults() *IdentificationConfidence {
	this := IdentificationConfidence{}
	return &this
}

// GetScore returns the Score field value
func (o *IdentificationConfidence) GetScore() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.Score
}

// GetScoreOk returns a tuple with the Score field value
// and a boolean to check if the value has been set.
func (o *IdentificationConfidence) GetScoreOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Score, true
}

// SetScore sets field value
func (o *IdentificationConfidence) SetScore(v float64) {
	o.Score = v
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *IdentificationConfidence) GetVersion() string {
	if o == nil || IsNil(o.Version) {
		var ret string
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IdentificationConfidence) GetVersionOk() (*string, bool) {
	if o == nil || IsNil(o.Version) {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *IdentificationConfidence) HasVersion() bool {
	if o != nil && !IsNil(o.Version) {
		return true
	}

	return false
}

// SetVersion gets a reference to the given string and assigns it to the Version field.
func (o *IdentificationConfidence) SetVersion(v string) {
	o.Version = &v
}

// GetComment returns the Comment field value if set, zero value otherwise.
func (o *IdentificationConfidence) GetComment() string {
	if o == nil || IsNil(o.Comment) {
		var ret string
		return ret
	}
	return *o.Comment
}

// GetCommentOk returns a tuple with the Comment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IdentificationConfidence) GetCommentOk() (*string, bool) {
	if o == nil || IsNil(o.Comment) {
		return nil, false
	}
	return o.Comment, true
}

// HasComment returns a boolean if a field has been set.
func (o *IdentificationConfidence) HasComment() bool {
	if o != nil && !IsNil(o.Comment) {
		return true
	}

	return false
}

// SetComment gets a reference to the given string and assigns it to the Comment field.
func (o *IdentificationConfidence) SetComment(v string) {
	o.Comment = &v
}

func (o IdentificationConfidence) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IdentificationConfidence) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["score"] = o.Score
	if !IsNil(o.Version) {
		toSerialize["version"] = o.Version
	}
	if !IsNil(o.Comment) {
		toSerialize["comment"] = o.Comment
	}
	return toSerialize, nil
}

func (o *IdentificationConfidence) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"score",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varIdentificationConfidence := _IdentificationConfidence{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varIdentificationConfidence)

	if err != nil {
		return err
	}

	*o = IdentificationConfidence(varIdentificationConfidence)

	return err
}

type NullableIdentificationConfidence struct {
	value *IdentificationConfidence
	isSet bool
}

func (v NullableIdentificationConfidence) Get() *IdentificationConfidence {
	return v.value
}

func (v *NullableIdentificationConfidence) Set(val *IdentificationConfidence) {
	v.value = val
	v.isSet = true
}

func (v NullableIdentificationConfidence) IsSet() bool {
	return v.isSet
}

func (v *NullableIdentificationConfidence) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIdentificationConfidence(val *IdentificationConfidence) *NullableIdentificationConfidence {
	return &NullableIdentificationConfidence{value: val, isSet: true}
}

func (v NullableIdentificationConfidence) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIdentificationConfidence) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
