/*
Server API

# Overview Fingerprint Server API allows you to get, search, and update Events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device.

API version: 4
Contact: support@fingerprint.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fingerprint

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ProxyDetails type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProxyDetails{}

// ProxyDetails Proxy detection details (present if `proxy` is `true`)
type ProxyDetails struct {
	// Residential proxies use real user IP addresses to appear as legitimate traffic,  while data center proxies are public proxies hosted in data centers
	ProxyType string `json:"proxy_type"`
	// Unix millisecond timestamp with hourly resolution of when this IP was last seen as a proxy
	LastSeenAt *int64 `json:"last_seen_at,omitempty"`
}

type _ProxyDetails ProxyDetails

// NewProxyDetails instantiates a new ProxyDetails object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProxyDetails(proxyType string) *ProxyDetails {
	this := ProxyDetails{}
	this.ProxyType = proxyType
	return &this
}

// NewProxyDetailsWithDefaults instantiates a new ProxyDetails object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProxyDetailsWithDefaults() *ProxyDetails {
	this := ProxyDetails{}
	return &this
}

// GetProxyType returns the ProxyType field value
func (o *ProxyDetails) GetProxyType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProxyType
}

// GetProxyTypeOk returns a tuple with the ProxyType field value
// and a boolean to check if the value has been set.
func (o *ProxyDetails) GetProxyTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProxyType, true
}

// SetProxyType sets field value
func (o *ProxyDetails) SetProxyType(v string) {
	o.ProxyType = v
}

// GetLastSeenAt returns the LastSeenAt field value if set, zero value otherwise.
func (o *ProxyDetails) GetLastSeenAt() int64 {
	if o == nil || IsNil(o.LastSeenAt) {
		var ret int64
		return ret
	}
	return *o.LastSeenAt
}

// GetLastSeenAtOk returns a tuple with the LastSeenAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProxyDetails) GetLastSeenAtOk() (*int64, bool) {
	if o == nil || IsNil(o.LastSeenAt) {
		return nil, false
	}
	return o.LastSeenAt, true
}

// HasLastSeenAt returns a boolean if a field has been set.
func (o *ProxyDetails) HasLastSeenAt() bool {
	if o != nil && !IsNil(o.LastSeenAt) {
		return true
	}

	return false
}

// SetLastSeenAt gets a reference to the given int64 and assigns it to the LastSeenAt field.
func (o *ProxyDetails) SetLastSeenAt(v int64) {
	o.LastSeenAt = &v
}

func (o ProxyDetails) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProxyDetails) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["proxy_type"] = o.ProxyType
	if !IsNil(o.LastSeenAt) {
		toSerialize["last_seen_at"] = o.LastSeenAt
	}
	return toSerialize, nil
}

func (o *ProxyDetails) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"proxy_type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varProxyDetails := _ProxyDetails{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varProxyDetails)

	if err != nil {
		return err
	}

	*o = ProxyDetails(varProxyDetails)

	return err
}

type NullableProxyDetails struct {
	value *ProxyDetails
	isSet bool
}

func (v NullableProxyDetails) Get() *ProxyDetails {
	return v.value
}

func (v *NullableProxyDetails) Set(val *ProxyDetails) {
	v.value = val
	v.isSet = true
}

func (v NullableProxyDetails) IsSet() bool {
	return v.isSet
}

func (v *NullableProxyDetails) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProxyDetails(val *ProxyDetails) *NullableProxyDetails {
	return &NullableProxyDetails{value: val, isSet: true}
}

func (v NullableProxyDetails) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProxyDetails) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
