/*
Server API

Fingerprint Server API allows you to get, search, and update Events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device.

API version: 4
Contact: support@fingerprint.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fingerprint

import (
	"github.com/fingerprintjs/go-sdk/v8/internal/openapi"
)

type BotInfo = openapi.BotInfo
type BotResult = openapi.BotResult

const (
	BotResultBad         = openapi.BotResultBad
	BotResultGood        = openapi.BotResultGood
	BotResultNotDetected = openapi.BotResultNotDetected
)

type BrowserDetails = openapi.BrowserDetails
type Canvas = openapi.Canvas
type Emoji = openapi.Emoji
type Error = openapi.Error
type ErrorCode = openapi.ErrorCode

const (
	ErrorCodeRequestCannotBeParsed = openapi.ErrorCodeRequestCannotBeParsed
	ErrorCodeSecretAPIKeyRequired  = openapi.ErrorCodeSecretAPIKeyRequired
	ErrorCodeSecretAPIKeyNotFound  = openapi.ErrorCodeSecretAPIKeyNotFound
	ErrorCodePublicAPIKeyRequired  = openapi.ErrorCodePublicAPIKeyRequired
	ErrorCodePublicAPIKeyNotFound  = openapi.ErrorCodePublicAPIKeyNotFound
	ErrorCodeSubscriptionNotActive = openapi.ErrorCodeSubscriptionNotActive
	ErrorCodeWrongRegion           = openapi.ErrorCodeWrongRegion
	ErrorCodeFeatureNotEnabled     = openapi.ErrorCodeFeatureNotEnabled
	ErrorCodeRequestNotFound       = openapi.ErrorCodeRequestNotFound
	ErrorCodeVisitorNotFound       = openapi.ErrorCodeVisitorNotFound
	ErrorCodeTooManyRequests       = openapi.ErrorCodeTooManyRequests
	ErrorCodeStateNotReady         = openapi.ErrorCodeStateNotReady
	ErrorCodeFailed                = openapi.ErrorCodeFailed
	ErrorCodeEventNotFound         = openapi.ErrorCodeEventNotFound
	ErrorCodeMissingModule         = openapi.ErrorCodeMissingModule
	ErrorCodePayloadTooLarge       = openapi.ErrorCodePayloadTooLarge
	ErrorCodeServiceUnavailable    = openapi.ErrorCodeServiceUnavailable
	ErrorCodeRulesetNotFound       = openapi.ErrorCodeRulesetNotFound
)

type ErrorResponse = openapi.ErrorResponse
type Event = openapi.Event
type EventRuleAction = openapi.EventRuleAction
type EventRuleActionAllow = openapi.EventRuleActionAllow
type EventRuleActionBlock = openapi.EventRuleActionBlock
type EventSearch = openapi.EventSearch
type EventUpdate = openapi.EventUpdate
type FontPreferences = openapi.FontPreferences
type Geolocation = openapi.Geolocation
type GeolocationSubdivisionsInner = openapi.GeolocationSubdivisionsInner
type IPBlockList = openapi.IPBlockList
type IPInfo = openapi.IPInfo
type IPInfoV4 = openapi.IPInfoV4
type IPInfoV6 = openapi.IPInfoV6
type Identification = openapi.Identification
type IdentificationConfidence = openapi.IdentificationConfidence
type Integration = openapi.Integration
type IntegrationSubintegration = openapi.IntegrationSubintegration
type PluginsInner = openapi.PluginsInner
type PluginsInnerMimeTypesInner = openapi.PluginsInnerMimeTypesInner
type Proximity = openapi.Proximity
type ProxyConfidence = openapi.ProxyConfidence

const (
	ProxyConfidenceLow    = openapi.ProxyConfidenceLow
	ProxyConfidenceMedium = openapi.ProxyConfidenceMedium
	ProxyConfidenceHigh   = openapi.ProxyConfidenceHigh
)

type ProxyDetails = openapi.ProxyDetails
type RawDeviceAttributes = openapi.RawDeviceAttributes
type RequestHeaderModifications = openapi.RequestHeaderModifications
type RuleActionHeaderField = openapi.RuleActionHeaderField
type RuleActionType = openapi.RuleActionType

const (
	RuleActionTypeAllow = openapi.RuleActionTypeAllow
	RuleActionTypeBlock = openapi.RuleActionTypeBlock
)

type SDK = openapi.SDK
type SearchEventsBot = openapi.SearchEventsBot

const (
	SearchEventsBotAll  = openapi.SearchEventsBotAll
	SearchEventsBotGood = openapi.SearchEventsBotGood
	SearchEventsBotBad  = openapi.SearchEventsBotBad
	SearchEventsBotNone = openapi.SearchEventsBotNone
)

type SearchEventsSDKPlatform = openapi.SearchEventsSDKPlatform

const (
	SearchEventsSDKPlatformJs      = openapi.SearchEventsSDKPlatformJs
	SearchEventsSDKPlatformAndroid = openapi.SearchEventsSDKPlatformAndroid
	SearchEventsSDKPlatformIos     = openapi.SearchEventsSDKPlatformIos
)

type SearchEventsVPNConfidence = openapi.SearchEventsVPNConfidence

const (
	SearchEventsVPNConfidenceHigh   = openapi.SearchEventsVPNConfidenceHigh
	SearchEventsVPNConfidenceMedium = openapi.SearchEventsVPNConfidenceMedium
	SearchEventsVPNConfidenceLow    = openapi.SearchEventsVPNConfidenceLow
)

type SupplementaryIDHighRecall = openapi.SupplementaryIDHighRecall
type TamperingDetails = openapi.TamperingDetails
type TouchSupport = openapi.TouchSupport
type VPNConfidence = openapi.VPNConfidence

const (
	VPNConfidenceLow    = openapi.VPNConfidenceLow
	VPNConfidenceMedium = openapi.VPNConfidenceMedium
	VPNConfidenceHigh   = openapi.VPNConfidenceHigh
)

type VPNMethods = openapi.VPNMethods
type Velocity = openapi.Velocity
type VelocityData = openapi.VelocityData
type WebGlBasics = openapi.WebGlBasics
type WebGlExtensions = openapi.WebGlExtensions
