/*
Server API

# Overview Fingerprint Server API allows you to get, search, and update Events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device.

API version: 4
Contact: support@fingerprint.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fingerprint

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the SDK type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SDK{}

// SDK Contains information about the SDK used to perform the request.
type SDK struct {
	// Platform of the SDK used for the identification request.
	Platform string `json:"platform"`
	// Version string of the SDK used for the identification request. For example: `\"3.12.1\"`
	Version      string        `json:"version"`
	Integrations []Integration `json:"integrations,omitempty"`
}

type _SDK SDK

// NewSDK instantiates a new SDK object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSDK(platform string, version string) *SDK {
	this := SDK{}
	this.Platform = platform
	this.Version = version
	return &this
}

// NewSDKWithDefaults instantiates a new SDK object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSDKWithDefaults() *SDK {
	this := SDK{}
	return &this
}

// GetPlatform returns the Platform field value
func (o *SDK) GetPlatform() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Platform
}

// GetPlatformOk returns a tuple with the Platform field value
// and a boolean to check if the value has been set.
func (o *SDK) GetPlatformOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Platform, true
}

// SetPlatform sets field value
func (o *SDK) SetPlatform(v string) {
	o.Platform = v
}

// GetVersion returns the Version field value
func (o *SDK) GetVersion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Version
}

// GetVersionOk returns a tuple with the Version field value
// and a boolean to check if the value has been set.
func (o *SDK) GetVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Version, true
}

// SetVersion sets field value
func (o *SDK) SetVersion(v string) {
	o.Version = v
}

// GetIntegrations returns the Integrations field value if set, zero value otherwise.
func (o *SDK) GetIntegrations() []Integration {
	if o == nil || IsNil(o.Integrations) {
		var ret []Integration
		return ret
	}
	return o.Integrations
}

// GetIntegrationsOk returns a tuple with the Integrations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SDK) GetIntegrationsOk() ([]Integration, bool) {
	if o == nil || IsNil(o.Integrations) {
		return nil, false
	}
	return o.Integrations, true
}

// HasIntegrations returns a boolean if a field has been set.
func (o *SDK) HasIntegrations() bool {
	if o != nil && !IsNil(o.Integrations) {
		return true
	}

	return false
}

// SetIntegrations gets a reference to the given []Integration and assigns it to the Integrations field.
func (o *SDK) SetIntegrations(v []Integration) {
	o.Integrations = v
}

func (o SDK) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SDK) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["platform"] = o.Platform
	toSerialize["version"] = o.Version
	if !IsNil(o.Integrations) {
		toSerialize["integrations"] = o.Integrations
	}
	return toSerialize, nil
}

func (o *SDK) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"platform",
		"version",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSDK := _SDK{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSDK)

	if err != nil {
		return err
	}

	*o = SDK(varSDK)

	return err
}

type NullableSDK struct {
	value *SDK
	isSet bool
}

func (v NullableSDK) Get() *SDK {
	return v.value
}

func (v *NullableSDK) Set(val *SDK) {
	v.value = val
	v.isSet = true
}

func (v NullableSDK) IsSet() bool {
	return v.isSet
}

func (v *NullableSDK) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSDK(val *SDK) *NullableSDK {
	return &NullableSDK{value: val, isSet: true}
}

func (v NullableSDK) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSDK) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
