/*
Server API

Testing FingerprintAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package fingerprint

import (
	"context"
	openapiclient "github.com/fingerprintjs/go-sdk"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func Test_fingerprint_FingerprintAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test FingerprintAPIService DeleteVisitorData", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var visitorId string

		httpRes, err := apiClient.FingerprintAPI.DeleteVisitorData(context.Background(), visitorId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test FingerprintAPIService GetEvent", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var eventId string

		resp, httpRes, err := apiClient.FingerprintAPI.GetEvent(context.Background(), eventId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test FingerprintAPIService SearchEvents", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.FingerprintAPI.SearchEvents(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test FingerprintAPIService UpdateEvent", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var eventId string

		httpRes, err := apiClient.FingerprintAPI.UpdateEvent(context.Background(), eventId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
