/*
Server API

Fingerprint Server API allows you to get, search, and update Events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device.

API version: 4
Contact: support@fingerprint.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// BotInfoIdentity The verification status of the bot's identity:  * `verified` - well-known bot with publicly verifiable identity, directed by the bot provider.  * `signed` - bot that signs its platform via Web Bot Auth, directed by the bot provider's customers.  * `spoofed` - bot that claims a public identity but fails verification.  * `unknown` - bot that does not publish a verifiable identity.
type BotInfoIdentity string

// List of BotInfoIdentity
const (
	BotInfoIdentityVerified BotInfoIdentity = "verified"
	BotInfoIdentitySigned   BotInfoIdentity = "signed"
	BotInfoIdentitySpoofed  BotInfoIdentity = "spoofed"
	BotInfoIdentityUnknown  BotInfoIdentity = "unknown"
)

// All allowed values of BotInfoIdentity enum
var AllowedBotInfoIdentityEnumValues = []BotInfoIdentity{
	BotInfoIdentityVerified,
	BotInfoIdentitySigned,
	BotInfoIdentitySpoofed,
	BotInfoIdentityUnknown,
}

func (v *BotInfoIdentity) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := BotInfoIdentity(value)
	for _, existing := range AllowedBotInfoIdentityEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid BotInfoIdentity", value)
}
