/*
Server API

Fingerprint Server API allows you to get, search, and update Events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device.

API version: 4
Contact: support@fingerprint.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// SearchEventsVPNConfidence Filter events by VPN Detection result confidence level. `high` - events with high VPN Detection confidence. `medium` - events with medium VPN Detection confidence. `low` - events with low VPN Detection confidence. > Note: When using this parameter, only events with the `vpn.confidence` property set to a valid value are returned. Events without a `vpn` Smart Signal result are left out of the response.
type SearchEventsVPNConfidence string

// List of SearchEventsVPNConfidence
const (
	SearchEventsVPNConfidenceHigh   SearchEventsVPNConfidence = "high"
	SearchEventsVPNConfidenceMedium SearchEventsVPNConfidence = "medium"
	SearchEventsVPNConfidenceLow    SearchEventsVPNConfidence = "low"
)

// All allowed values of SearchEventsVPNConfidence enum
var AllowedSearchEventsVPNConfidenceEnumValues = []SearchEventsVPNConfidence{
	SearchEventsVPNConfidenceHigh,
	SearchEventsVPNConfidenceMedium,
	SearchEventsVPNConfidenceLow,
}

func (v *SearchEventsVPNConfidence) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := SearchEventsVPNConfidence(value)
	for _, existing := range AllowedSearchEventsVPNConfidenceEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid SearchEventsVPNConfidence", value)
}
