/*
Server API

Fingerprint Server API allows you to get, search, and update Events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device.

API version: 4
Contact: support@fingerprint.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// VPNConfidence A confidence rating for the VPN detection result — \"low\", \"medium\", or \"high\". Depends on the combination of results returned from all VPN detection methods.
type VPNConfidence string

// List of VPNConfidence
const (
	VPNConfidenceLow    VPNConfidence = "low"
	VPNConfidenceMedium VPNConfidence = "medium"
	VPNConfidenceHigh   VPNConfidence = "high"
)

// All allowed values of VPNConfidence enum
var AllowedVPNConfidenceEnumValues = []VPNConfidence{
	VPNConfidenceLow,
	VPNConfidenceMedium,
	VPNConfidenceHigh,
}

func (v *VPNConfidence) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := VPNConfidence(value)
	for _, existing := range AllowedVPNConfidenceEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid VPNConfidence", value)
}
