/*
Server API

Fingerprint Server API allows you to get, search, and update Events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device.

API version: 4
Contact: support@fingerprint.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the WebGlExtensions type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WebGlExtensions{}

// WebGlExtensions Hashes of WebGL context attributes and extension support.
type WebGlExtensions struct {
	ContextAttributes     *string  `json:"context_attributes,omitempty"`
	Parameters            *string  `json:"parameters,omitempty"`
	ShaderPrecisions      *string  `json:"shader_precisions,omitempty"`
	Extensions            *string  `json:"extensions,omitempty"`
	ExtensionParameters   *string  `json:"extension_parameters,omitempty"`
	UnsupportedExtensions []string `json:"unsupported_extensions,omitempty"`
	AdditionalProperties  map[string]interface{}
}

type _WebGlExtensions WebGlExtensions

func (o WebGlExtensions) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WebGlExtensions) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ContextAttributes) {
		toSerialize["context_attributes"] = o.ContextAttributes
	}
	if !IsNil(o.Parameters) {
		toSerialize["parameters"] = o.Parameters
	}
	if !IsNil(o.ShaderPrecisions) {
		toSerialize["shader_precisions"] = o.ShaderPrecisions
	}
	if !IsNil(o.Extensions) {
		toSerialize["extensions"] = o.Extensions
	}
	if !IsNil(o.ExtensionParameters) {
		toSerialize["extension_parameters"] = o.ExtensionParameters
	}
	if !IsNil(o.UnsupportedExtensions) {
		toSerialize["unsupported_extensions"] = o.UnsupportedExtensions
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *WebGlExtensions) UnmarshalJSON(data []byte) (err error) {
	varWebGlExtensions := _WebGlExtensions{}

	err = json.Unmarshal(data, &varWebGlExtensions)

	if err != nil {
		return err
	}

	*o = WebGlExtensions(varWebGlExtensions)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "context_attributes")
		delete(additionalProperties, "parameters")
		delete(additionalProperties, "shader_precisions")
		delete(additionalProperties, "extensions")
		delete(additionalProperties, "extension_parameters")
		delete(additionalProperties, "unsupported_extensions")
		o.AdditionalProperties = additionalProperties
	}

	return err
}
