/*
Server API

Fingerprint Server API allows you to get, search, and update Events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device.

API version: 4
Contact: support@fingerprint.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the TamperingDetails type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TamperingDetails{}

// TamperingDetails struct for TamperingDetails
type TamperingDetails struct {
	// The output of this model is captured as anomaly_score, a statistical score indicating how rare the visitor's browser signature is compared to the overall population. Values close to 1 signify highly anomalous browsers and we consider anything above the threshold of 0.5 to be actionable (the result field conveniently captures that fact).
	AnomalyScore *float64 `json:"anomaly_score,omitempty"`
	// Detects whether the request shows evidence of anti-detect browser usage. This field may be triggered by: * heuristic detection of known anti-detect browser behavior * machine learning detection of anti-detect browser patterns  Examples of anti-detect browsers include tools such as AdsPower, DolphinAnty, OctoBrowser, and GoLogin.
	AntiDetectBrowser    *bool `json:"anti_detect_browser,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _TamperingDetails TamperingDetails

func (o TamperingDetails) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TamperingDetails) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AnomalyScore) {
		toSerialize["anomaly_score"] = o.AnomalyScore
	}
	if !IsNil(o.AntiDetectBrowser) {
		toSerialize["anti_detect_browser"] = o.AntiDetectBrowser
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *TamperingDetails) UnmarshalJSON(data []byte) (err error) {
	varTamperingDetails := _TamperingDetails{}

	err = json.Unmarshal(data, &varTamperingDetails)

	if err != nil {
		return err
	}

	*o = TamperingDetails(varTamperingDetails)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "anomaly_score")
		delete(additionalProperties, "anti_detect_browser")
		o.AdditionalProperties = additionalProperties
	}

	return err
}
