/*
Server API

Fingerprint Server API allows you to get, search, and update Events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device.

API version: 4
Contact: support@fingerprint.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the Canvas type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Canvas{}

// Canvas Canvas fingerprint containing winding flag plus geometry/text hashes.
type Canvas struct {
	Winding *bool `json:"winding,omitempty"`
	// Hash of geometry rendering output or `unsupported` markers.
	Geometry *string `json:"geometry,omitempty"`
	// Hash of text rendering output or `unsupported` markers.
	Text                 *string `json:"text,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _Canvas Canvas

func (o Canvas) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Canvas) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Winding) {
		toSerialize["winding"] = o.Winding
	}
	if !IsNil(o.Geometry) {
		toSerialize["geometry"] = o.Geometry
	}
	if !IsNil(o.Text) {
		toSerialize["text"] = o.Text
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *Canvas) UnmarshalJSON(data []byte) (err error) {
	varCanvas := _Canvas{}

	err = json.Unmarshal(data, &varCanvas)

	if err != nil {
		return err
	}

	*o = Canvas(varCanvas)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "winding")
		delete(additionalProperties, "geometry")
		delete(additionalProperties, "text")
		o.AdditionalProperties = additionalProperties
	}

	return err
}
