/*
Server API

Fingerprint Server API allows you to get, search, and update Events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device.

API version: 4
Contact: support@fingerprint.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the VPNMethods type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VPNMethods{}

// VPNMethods struct for VPNMethods
type VPNMethods struct {
	// The browser timezone doesn't match the timezone inferred from the request IP address.
	TimezoneMismatch *bool `json:"timezone_mismatch,omitempty"`
	// Request IP address is owned and used by a public VPN service provider.
	PublicVPN *bool `json:"public_vpn,omitempty"`
	// This method applies to mobile devices only. Indicates the result of additional methods used to detect a VPN in mobile devices.
	AuxiliaryMobile *bool `json:"auxiliary_mobile,omitempty"`
	// The browser runs on a different operating system than the operating system inferred from the request network signature.
	OsMismatch *bool `json:"os_mismatch,omitempty"`
	// Request IP address belongs to a relay service provider, indicating the use of relay services like [Apple Private relay](https://support.apple.com/en-us/102602) or [Cloudflare Warp](https://developers.cloudflare.com/warp-client/).  * Like VPNs, relay services anonymize the visitor's true IP address. * Unlike traditional VPNs, relay services don't let visitors spoof their location by choosing an exit node in a different country.  This field allows you to differentiate VPN users and relay service users in your fraud prevention logic.
	Relay                *bool `json:"relay,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _VPNMethods VPNMethods

func (o VPNMethods) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VPNMethods) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TimezoneMismatch) {
		toSerialize["timezone_mismatch"] = o.TimezoneMismatch
	}
	if !IsNil(o.PublicVPN) {
		toSerialize["public_vpn"] = o.PublicVPN
	}
	if !IsNil(o.AuxiliaryMobile) {
		toSerialize["auxiliary_mobile"] = o.AuxiliaryMobile
	}
	if !IsNil(o.OsMismatch) {
		toSerialize["os_mismatch"] = o.OsMismatch
	}
	if !IsNil(o.Relay) {
		toSerialize["relay"] = o.Relay
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *VPNMethods) UnmarshalJSON(data []byte) (err error) {
	varVPNMethods := _VPNMethods{}

	err = json.Unmarshal(data, &varVPNMethods)

	if err != nil {
		return err
	}

	*o = VPNMethods(varVPNMethods)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "timezone_mismatch")
		delete(additionalProperties, "public_vpn")
		delete(additionalProperties, "auxiliary_mobile")
		delete(additionalProperties, "os_mismatch")
		delete(additionalProperties, "relay")
		o.AdditionalProperties = additionalProperties
	}

	return err
}
