/*
Server API

Fingerprint Server API allows you to get, search, and update Events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device.

API version: 4
Contact: support@fingerprint.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the IPInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IPInfo{}

// IPInfo Details about the request IP address. Has separate fields for v4 and v6 IP address versions.
type IPInfo struct {
	V4                   *IPInfoV4 `json:"v4,omitempty"`
	V6                   *IPInfoV6 `json:"v6,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _IPInfo IPInfo

func (o IPInfo) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IPInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.V4) {
		toSerialize["v4"] = o.V4
	}
	if !IsNil(o.V6) {
		toSerialize["v6"] = o.V6
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *IPInfo) UnmarshalJSON(data []byte) (err error) {
	varIPInfo := _IPInfo{}

	err = json.Unmarshal(data, &varIPInfo)

	if err != nil {
		return err
	}

	*o = IPInfo(varIPInfo)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "v4")
		delete(additionalProperties, "v6")
		o.AdditionalProperties = additionalProperties
	}

	return err
}
