/*
Server API

Fingerprint Server API allows you to get, search, and update Events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device.

API version: 4
Contact: support@fingerprint.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the EventRuleActionAllow type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EventRuleActionAllow{}

// EventRuleActionAllow Informs the client that the request should be forwarded to the origin with optional request header modifications.
type EventRuleActionAllow struct {
	// The ID of the evaluated ruleset.
	RulesetID string `json:"ruleset_id"`
	// The ID of the rule that matched the identification event.
	RuleID *string `json:"rule_id,omitempty"`
	// The expression of the rule that matched the identification event.
	RuleExpression             *string                     `json:"rule_expression,omitempty"`
	Type                       RuleActionType              `json:"type"`
	RequestHeaderModifications *RequestHeaderModifications `json:"request_header_modifications,omitempty"`
	AdditionalProperties       map[string]interface{}
}

type _EventRuleActionAllow EventRuleActionAllow

func (o EventRuleActionAllow) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EventRuleActionAllow) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["ruleset_id"] = o.RulesetID
	if !IsNil(o.RuleID) {
		toSerialize["rule_id"] = o.RuleID
	}
	if !IsNil(o.RuleExpression) {
		toSerialize["rule_expression"] = o.RuleExpression
	}
	toSerialize["type"] = o.Type
	if !IsNil(o.RequestHeaderModifications) {
		toSerialize["request_header_modifications"] = o.RequestHeaderModifications
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *EventRuleActionAllow) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"ruleset_id",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEventRuleActionAllow := _EventRuleActionAllow{}

	err = json.Unmarshal(data, &varEventRuleActionAllow)

	if err != nil {
		return err
	}

	*o = EventRuleActionAllow(varEventRuleActionAllow)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "ruleset_id")
		delete(additionalProperties, "rule_id")
		delete(additionalProperties, "rule_expression")
		delete(additionalProperties, "type")
		delete(additionalProperties, "request_header_modifications")
		o.AdditionalProperties = additionalProperties
	}

	return err
}
