/*
Server API

Fingerprint Server API allows you to get, search, and update Events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device.

API version: 4
Contact: support@fingerprint.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// SearchEventsRareDevicePercentileBucket Filter events by Device Rarity percentile bucket. `<p95` - device configuration is in the bottom 95% (most common). `p95-p99` - device is in the 95th to 99th percentile. `p99-p99.5` - device is in the 99th to 99.5th percentile. `p99.5-p99.9` - device is in the 99.5th to 99.9th percentile. `p99.9+` - device is in the top 0.1% (rarest). `not_seen` - device configuration has never been observed before.
type SearchEventsRareDevicePercentileBucket string

// List of SearchEventsRareDevicePercentileBucket
const (
	SearchEventsRareDevicePercentileBucketP95      SearchEventsRareDevicePercentileBucket = "<p95"
	SearchEventsRareDevicePercentileBucketP95P99   SearchEventsRareDevicePercentileBucket = "p95-p99"
	SearchEventsRareDevicePercentileBucketP99P995  SearchEventsRareDevicePercentileBucket = "p99-p99.5"
	SearchEventsRareDevicePercentileBucketP995P999 SearchEventsRareDevicePercentileBucket = "p99.5-p99.9"
	SearchEventsRareDevicePercentileBucketP999     SearchEventsRareDevicePercentileBucket = "p99.9+"
	SearchEventsRareDevicePercentileBucketNotSeen  SearchEventsRareDevicePercentileBucket = "not_seen"
)

// All allowed values of SearchEventsRareDevicePercentileBucket enum
var AllowedSearchEventsRareDevicePercentileBucketEnumValues = []SearchEventsRareDevicePercentileBucket{
	SearchEventsRareDevicePercentileBucketP95,
	SearchEventsRareDevicePercentileBucketP95P99,
	SearchEventsRareDevicePercentileBucketP99P995,
	SearchEventsRareDevicePercentileBucketP995P999,
	SearchEventsRareDevicePercentileBucketP999,
	SearchEventsRareDevicePercentileBucketNotSeen,
}

func (v *SearchEventsRareDevicePercentileBucket) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := SearchEventsRareDevicePercentileBucket(value)
	for _, existing := range AllowedSearchEventsRareDevicePercentileBucketEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid SearchEventsRareDevicePercentileBucket", value)
}
