/*
Server API

Fingerprint Server API allows you to get, search, and update Events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device.

API version: 4
Contact: support@fingerprint.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the BrowserDetails type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BrowserDetails{}

// BrowserDetails struct for BrowserDetails
type BrowserDetails struct {
	BrowserName          string `json:"browser_name"`
	BrowserMajorVersion  string `json:"browser_major_version"`
	BrowserFullVersion   string `json:"browser_full_version"`
	Os                   string `json:"os"`
	OsVersion            string `json:"os_version"`
	Device               string `json:"device"`
	AdditionalProperties map[string]interface{}
}

type _BrowserDetails BrowserDetails

func (o BrowserDetails) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BrowserDetails) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["browser_name"] = o.BrowserName
	toSerialize["browser_major_version"] = o.BrowserMajorVersion
	toSerialize["browser_full_version"] = o.BrowserFullVersion
	toSerialize["os"] = o.Os
	toSerialize["os_version"] = o.OsVersion
	toSerialize["device"] = o.Device

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *BrowserDetails) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"browser_name",
		"browser_major_version",
		"browser_full_version",
		"os",
		"os_version",
		"device",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBrowserDetails := _BrowserDetails{}

	err = json.Unmarshal(data, &varBrowserDetails)

	if err != nil {
		return err
	}

	*o = BrowserDetails(varBrowserDetails)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "browser_name")
		delete(additionalProperties, "browser_major_version")
		delete(additionalProperties, "browser_full_version")
		delete(additionalProperties, "os")
		delete(additionalProperties, "os_version")
		delete(additionalProperties, "device")
		o.AdditionalProperties = additionalProperties
	}

	return err
}
