/*
Server API

Fingerprint Server API allows you to get, search, and update Events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device. The API also supports collection of Automation Intelligence for requests to your server in edge, pre-origin, or middleware contexts.

API version: 4
Contact: support@fingerprint.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// RuleActionType Describes the action to take with the request.
type RuleActionType string

// List of RuleActionType
const (
	RuleActionTypeAllow RuleActionType = "allow"
	RuleActionTypeBlock RuleActionType = "block"
)

// All allowed values of RuleActionType enum
var AllowedRuleActionTypeEnumValues = []RuleActionType{
	RuleActionTypeAllow,
	RuleActionTypeBlock,
}

func (v *RuleActionType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}

	// Do not validate the value against the allowed values. The server
	// API may use new enum values before the SDK supports them
	// and that scenario must not result in deserialization failures.
	//
	// SDK users can limit the enum values they work with by
	// using the exported AllowedRuleActionTypeEnumValues slice.
	*v = RuleActionType(value)
	return nil
}
