/*
Server API

Fingerprint Server API allows you to get, search, and update Events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device.

API version: 4
Contact: support@fingerprint.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the IdentificationConfidence type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IdentificationConfidence{}

// IdentificationConfidence struct for IdentificationConfidence
type IdentificationConfidence struct {
	// The confidence score is a floating-point number between 0 and 1 that represents the probability of accurate identification.
	Score float64 `json:"score"`
	// The version name of the method used to calculate the Confidence score. This field is only present for customers who opted in to an alternative calculation method.
	Version              *string `json:"version,omitempty"`
	Comment              *string `json:"comment,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _IdentificationConfidence IdentificationConfidence

func (o IdentificationConfidence) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IdentificationConfidence) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["score"] = o.Score
	if !IsNil(o.Version) {
		toSerialize["version"] = o.Version
	}
	if !IsNil(o.Comment) {
		toSerialize["comment"] = o.Comment
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *IdentificationConfidence) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"score",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varIdentificationConfidence := _IdentificationConfidence{}

	err = json.Unmarshal(data, &varIdentificationConfidence)

	if err != nil {
		return err
	}

	*o = IdentificationConfidence(varIdentificationConfidence)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "score")
		delete(additionalProperties, "version")
		delete(additionalProperties, "comment")
		o.AdditionalProperties = additionalProperties
	}

	return err
}
