/*
Server API

Fingerprint Server API allows you to get, search, and update Events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device.

API version: 4
Contact: support@fingerprint.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the RawDeviceAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RawDeviceAttributes{}

// RawDeviceAttributes A curated subset of raw browser/device attributes that the API surface exposes. Each property contains a value or object with the data for the collected signal.
type RawDeviceAttributes struct {
	FontPreferences *FontPreferences `json:"font_preferences,omitempty"`
	Emoji           *Emoji           `json:"emoji,omitempty"`
	// List of fonts detected on the device.
	Fonts []string `json:"fonts,omitempty"`
	// Rounded amount of RAM (in gigabytes) reported by the browser.
	DeviceMemory *int32 `json:"device_memory,omitempty"`
	// Timezone identifier detected on the client.
	Timezone *string `json:"timezone,omitempty"`
	Canvas   *Canvas `json:"canvas,omitempty"`
	// Navigator languages reported by the agent including fallbacks. Each inner array represents ordered language preferences reported by different APIs.
	Languages       [][]string       `json:"languages,omitempty"`
	WebglExtensions *WebGlExtensions `json:"webgl_extensions,omitempty"`
	WebglBasics     *WebGlBasics     `json:"webgl_basics,omitempty"`
	// Current screen resolution.
	ScreenResolution []int32       `json:"screen_resolution,omitempty"`
	TouchSupport     *TouchSupport `json:"touch_support,omitempty"`
	// Navigator `oscpu` string.
	Oscpu *string `json:"oscpu,omitempty"`
	// Integer representing the CPU architecture exposed by the browser.
	Architecture *int32 `json:"architecture,omitempty"`
	// Whether the cookies are enabled in the browser.
	CookiesEnabled *bool `json:"cookies_enabled,omitempty"`
	// Number of logical CPU cores reported by the browser.
	HardwareConcurrency *int32 `json:"hardware_concurrency,omitempty"`
	// Locale derived from the Intl.DateTimeFormat API. Negative values indicate known error states. The negative statuses can be: - \"-1\": A permanent status for browsers that don't support Intl API. - \"-2\": A permanent status for browsers that don't supportDateTimeFormat constructor. - \"-3\": A permanent status for browsers in which DateTimeFormat locale is undefined or null.
	DateTimeLocale *string `json:"date_time_locale,omitempty"`
	// Navigator vendor string.
	Vendor *string `json:"vendor,omitempty"`
	// Screen color depth in bits.
	ColorDepth *int32 `json:"color_depth,omitempty"`
	// Navigator platform string.
	Platform *string `json:"platform,omitempty"`
	// Whether sessionStorage is available.
	SessionStorage *bool `json:"session_storage,omitempty"`
	// Whether localStorage is available.
	LocalStorage *bool `json:"local_storage,omitempty"`
	// AudioContext fingerprint or negative status when unavailable. The negative statuses can be: - -1: A permanent status for those browsers which are known to always suspend audio context - -2: A permanent status for browsers that don't support the signal - -3: A temporary status that means that an unexpected timeout has happened
	Audio *float64 `json:"audio,omitempty"`
	// Browser plugins reported by `navigator.plugins`.
	Plugins []PluginsInner `json:"plugins,omitempty"`
	// Whether IndexedDB is available.
	IndexedDb *bool `json:"indexed_db,omitempty"`
	// Hash of Math APIs used for entropy collection.
	Math                 *string `json:"math,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _RawDeviceAttributes RawDeviceAttributes

func (o RawDeviceAttributes) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RawDeviceAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.FontPreferences) {
		toSerialize["font_preferences"] = o.FontPreferences
	}
	if !IsNil(o.Emoji) {
		toSerialize["emoji"] = o.Emoji
	}
	if !IsNil(o.Fonts) {
		toSerialize["fonts"] = o.Fonts
	}
	if !IsNil(o.DeviceMemory) {
		toSerialize["device_memory"] = o.DeviceMemory
	}
	if !IsNil(o.Timezone) {
		toSerialize["timezone"] = o.Timezone
	}
	if !IsNil(o.Canvas) {
		toSerialize["canvas"] = o.Canvas
	}
	if !IsNil(o.Languages) {
		toSerialize["languages"] = o.Languages
	}
	if !IsNil(o.WebglExtensions) {
		toSerialize["webgl_extensions"] = o.WebglExtensions
	}
	if !IsNil(o.WebglBasics) {
		toSerialize["webgl_basics"] = o.WebglBasics
	}
	if !IsNil(o.ScreenResolution) {
		toSerialize["screen_resolution"] = o.ScreenResolution
	}
	if !IsNil(o.TouchSupport) {
		toSerialize["touch_support"] = o.TouchSupport
	}
	if !IsNil(o.Oscpu) {
		toSerialize["oscpu"] = o.Oscpu
	}
	if !IsNil(o.Architecture) {
		toSerialize["architecture"] = o.Architecture
	}
	if !IsNil(o.CookiesEnabled) {
		toSerialize["cookies_enabled"] = o.CookiesEnabled
	}
	if !IsNil(o.HardwareConcurrency) {
		toSerialize["hardware_concurrency"] = o.HardwareConcurrency
	}
	if !IsNil(o.DateTimeLocale) {
		toSerialize["date_time_locale"] = o.DateTimeLocale
	}
	if !IsNil(o.Vendor) {
		toSerialize["vendor"] = o.Vendor
	}
	if !IsNil(o.ColorDepth) {
		toSerialize["color_depth"] = o.ColorDepth
	}
	if !IsNil(o.Platform) {
		toSerialize["platform"] = o.Platform
	}
	if !IsNil(o.SessionStorage) {
		toSerialize["session_storage"] = o.SessionStorage
	}
	if !IsNil(o.LocalStorage) {
		toSerialize["local_storage"] = o.LocalStorage
	}
	if !IsNil(o.Audio) {
		toSerialize["audio"] = o.Audio
	}
	if !IsNil(o.Plugins) {
		toSerialize["plugins"] = o.Plugins
	}
	if !IsNil(o.IndexedDb) {
		toSerialize["indexed_db"] = o.IndexedDb
	}
	if !IsNil(o.Math) {
		toSerialize["math"] = o.Math
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *RawDeviceAttributes) UnmarshalJSON(data []byte) (err error) {
	varRawDeviceAttributes := _RawDeviceAttributes{}

	err = json.Unmarshal(data, &varRawDeviceAttributes)

	if err != nil {
		return err
	}

	*o = RawDeviceAttributes(varRawDeviceAttributes)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "font_preferences")
		delete(additionalProperties, "emoji")
		delete(additionalProperties, "fonts")
		delete(additionalProperties, "device_memory")
		delete(additionalProperties, "timezone")
		delete(additionalProperties, "canvas")
		delete(additionalProperties, "languages")
		delete(additionalProperties, "webgl_extensions")
		delete(additionalProperties, "webgl_basics")
		delete(additionalProperties, "screen_resolution")
		delete(additionalProperties, "touch_support")
		delete(additionalProperties, "oscpu")
		delete(additionalProperties, "architecture")
		delete(additionalProperties, "cookies_enabled")
		delete(additionalProperties, "hardware_concurrency")
		delete(additionalProperties, "date_time_locale")
		delete(additionalProperties, "vendor")
		delete(additionalProperties, "color_depth")
		delete(additionalProperties, "platform")
		delete(additionalProperties, "session_storage")
		delete(additionalProperties, "local_storage")
		delete(additionalProperties, "audio")
		delete(additionalProperties, "plugins")
		delete(additionalProperties, "indexed_db")
		delete(additionalProperties, "math")
		o.AdditionalProperties = additionalProperties
	}

	return err
}
