/*
Server API

Fingerprint Server API allows you to get, search, and update Events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device. The API also supports collection of Automation Intelligence for requests to your server in edge, pre-origin, or middleware contexts.

API version: 4
Contact: support@fingerprint.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// BotInfoConfidence Confidence level of the bot identification.
type BotInfoConfidence string

// List of BotInfoConfidence
const (
	BotInfoConfidenceLow    BotInfoConfidence = "low"
	BotInfoConfidenceMedium BotInfoConfidence = "medium"
	BotInfoConfidenceHigh   BotInfoConfidence = "high"
)

// All allowed values of BotInfoConfidence enum
var AllowedBotInfoConfidenceEnumValues = []BotInfoConfidence{
	BotInfoConfidenceLow,
	BotInfoConfidenceMedium,
	BotInfoConfidenceHigh,
}

func (v *BotInfoConfidence) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}

	// Do not validate the value against the allowed values. The server
	// API may use new enum values before the SDK supports them
	// and that scenario must not result in deserialization failures.
	//
	// SDK users can limit the enum values they work with by
	// using the exported AllowedBotInfoConfidenceEnumValues slice.
	*v = BotInfoConfidence(value)
	return nil
}
