/*
Server API

Fingerprint Server API allows you to get, search, and update Events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device.

API version: 4
Contact: support@fingerprint.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// ProxyConfidence Confidence level of the proxy detection. If a proxy is not detected, confidence is \"high\". If it's detected, can be \"low\", \"medium\", or \"high\".
type ProxyConfidence string

// List of ProxyConfidence
const (
	ProxyConfidenceLow    ProxyConfidence = "low"
	ProxyConfidenceMedium ProxyConfidence = "medium"
	ProxyConfidenceHigh   ProxyConfidence = "high"
)

// All allowed values of ProxyConfidence enum
var AllowedProxyConfidenceEnumValues = []ProxyConfidence{
	ProxyConfidenceLow,
	ProxyConfidenceMedium,
	ProxyConfidenceHigh,
}

func (v *ProxyConfidence) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := ProxyConfidence(value)
	for _, existing := range AllowedProxyConfidenceEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid ProxyConfidence", value)
}
