/*
Server API

Fingerprint Server API allows you to get, search, and update Events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device.

API version: 4
Contact: support@fingerprint.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the RequestHeaderModifications type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RequestHeaderModifications{}

// RequestHeaderModifications The set of header modifications to apply, in the following order: remove, set, append.
type RequestHeaderModifications struct {
	// The list of headers to remove.
	Remove []string `json:"remove,omitempty"`
	// The list of headers to set, overwriting any existing headers with the same name.
	Set []RuleActionHeaderField `json:"set,omitempty"`
	// The list of headers to append.
	Append               []RuleActionHeaderField `json:"append,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _RequestHeaderModifications RequestHeaderModifications

func (o RequestHeaderModifications) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RequestHeaderModifications) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Remove) {
		toSerialize["remove"] = o.Remove
	}
	if !IsNil(o.Set) {
		toSerialize["set"] = o.Set
	}
	if !IsNil(o.Append) {
		toSerialize["append"] = o.Append
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *RequestHeaderModifications) UnmarshalJSON(data []byte) (err error) {
	varRequestHeaderModifications := _RequestHeaderModifications{}

	err = json.Unmarshal(data, &varRequestHeaderModifications)

	if err != nil {
		return err
	}

	*o = RequestHeaderModifications(varRequestHeaderModifications)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "remove")
		delete(additionalProperties, "set")
		delete(additionalProperties, "append")
		o.AdditionalProperties = additionalProperties
	}

	return err
}
