/*
Server API

Fingerprint Server API allows you to get, search, and update Events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device.

API version: 4
Contact: support@fingerprint.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// TamperingConfidence Confidence level of the tampering detection. If a proxy is not detected, confidence is \"high\". If it's detected, can be \"low\", \"medium\", or \"high\".
type TamperingConfidence string

// List of TamperingConfidence
const (
	TamperingConfidenceLow    TamperingConfidence = "low"
	TamperingConfidenceMedium TamperingConfidence = "medium"
	TamperingConfidenceHigh   TamperingConfidence = "high"
)

// All allowed values of TamperingConfidence enum
var AllowedTamperingConfidenceEnumValues = []TamperingConfidence{
	TamperingConfidenceLow,
	TamperingConfidenceMedium,
	TamperingConfidenceHigh,
}

func (v *TamperingConfidence) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := TamperingConfidence(value)
	for _, existing := range AllowedTamperingConfidenceEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid TamperingConfidence", value)
}
