/*
Server API

Fingerprint Server API allows you to get, search, and update Events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device.

API version: 4
Contact: support@fingerprint.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the SupplementaryIDHighRecall type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SupplementaryIDHighRecall{}

// SupplementaryIDHighRecall A supplementary browser identifier that prioritizes coverage over precision. The High Recall ID algorithm matches more generously, i.e., this identifier will remain the same even when there are subtle differences between two requests. This algorithm does not create as many new visitor IDs as the standard algorithms do, but there could be an increase in false-positive identification.
type SupplementaryIDHighRecall struct {
	// String of 20 characters that uniquely identifies the visitor's browser or mobile device.
	VisitorID string `json:"visitor_id"`
	// Attribute represents if a visitor had been identified before.
	VisitorFound bool                      `json:"visitor_found"`
	Confidence   *IdentificationConfidence `json:"confidence,omitempty"`
	// Unix epoch time milliseconds timestamp indicating the time at which this ID was first seen. example: `1758069706642` - Corresponding to Wed Sep 17 2025 00:41:46 GMT+0000
	FirstSeenAt *int64 `json:"first_seen_at,omitempty"`
	// Unix epoch time milliseconds timestamp indicating the time at which this ID was last seen. example: `1758069706642` - Corresponding to Wed Sep 17 2025 00:41:46 GMT+0000
	LastSeenAt           *int64 `json:"last_seen_at,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _SupplementaryIDHighRecall SupplementaryIDHighRecall

func (o SupplementaryIDHighRecall) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SupplementaryIDHighRecall) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["visitor_id"] = o.VisitorID
	toSerialize["visitor_found"] = o.VisitorFound
	if !IsNil(o.Confidence) {
		toSerialize["confidence"] = o.Confidence
	}
	if !IsNil(o.FirstSeenAt) {
		toSerialize["first_seen_at"] = o.FirstSeenAt
	}
	if !IsNil(o.LastSeenAt) {
		toSerialize["last_seen_at"] = o.LastSeenAt
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SupplementaryIDHighRecall) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"visitor_id",
		"visitor_found",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSupplementaryIDHighRecall := _SupplementaryIDHighRecall{}

	err = json.Unmarshal(data, &varSupplementaryIDHighRecall)

	if err != nil {
		return err
	}

	*o = SupplementaryIDHighRecall(varSupplementaryIDHighRecall)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "visitor_id")
		delete(additionalProperties, "visitor_found")
		delete(additionalProperties, "confidence")
		delete(additionalProperties, "first_seen_at")
		delete(additionalProperties, "last_seen_at")
		o.AdditionalProperties = additionalProperties
	}

	return err
}
