/*
Server API

Fingerprint Server API allows you to get, search, and update Events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device.

API version: 4
Contact: support@fingerprint.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the Emoji type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Emoji{}

// Emoji Bounding box metrics describing how the emoji glyph renders.
type Emoji struct {
	// Font family reported by the browser when drawing the emoji.
	Font                 *string  `json:"font,omitempty"`
	Width                *float64 `json:"width,omitempty"`
	Height               *float64 `json:"height,omitempty"`
	Top                  *float64 `json:"top,omitempty"`
	Bottom               *float64 `json:"bottom,omitempty"`
	Left                 *float64 `json:"left,omitempty"`
	Right                *float64 `json:"right,omitempty"`
	X                    *float64 `json:"x,omitempty"`
	Y                    *float64 `json:"y,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _Emoji Emoji

func (o Emoji) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Emoji) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Font) {
		toSerialize["font"] = o.Font
	}
	if !IsNil(o.Width) {
		toSerialize["width"] = o.Width
	}
	if !IsNil(o.Height) {
		toSerialize["height"] = o.Height
	}
	if !IsNil(o.Top) {
		toSerialize["top"] = o.Top
	}
	if !IsNil(o.Bottom) {
		toSerialize["bottom"] = o.Bottom
	}
	if !IsNil(o.Left) {
		toSerialize["left"] = o.Left
	}
	if !IsNil(o.Right) {
		toSerialize["right"] = o.Right
	}
	if !IsNil(o.X) {
		toSerialize["x"] = o.X
	}
	if !IsNil(o.Y) {
		toSerialize["y"] = o.Y
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *Emoji) UnmarshalJSON(data []byte) (err error) {
	varEmoji := _Emoji{}

	err = json.Unmarshal(data, &varEmoji)

	if err != nil {
		return err
	}

	*o = Emoji(varEmoji)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "font")
		delete(additionalProperties, "width")
		delete(additionalProperties, "height")
		delete(additionalProperties, "top")
		delete(additionalProperties, "bottom")
		delete(additionalProperties, "left")
		delete(additionalProperties, "right")
		delete(additionalProperties, "x")
		delete(additionalProperties, "y")
		o.AdditionalProperties = additionalProperties
	}

	return err
}
