/*
Server API

Fingerprint Server API allows you to get, search, and update Events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device. The API also supports collection of Automation Intelligence for requests to your server in edge, pre-origin, or middleware contexts.

API version: 4
Contact: support@fingerprint.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// SearchEventsBotInfo Filter events by their Bot Info result, specifically:   - `all` - events where any kind of bot was detected.   - `none` - events where no bot was detected.
type SearchEventsBotInfo string

// List of SearchEventsBotInfo
const (
	SearchEventsBotInfoAll  SearchEventsBotInfo = "all"
	SearchEventsBotInfoNone SearchEventsBotInfo = "none"
)

// All allowed values of SearchEventsBotInfo enum
var AllowedSearchEventsBotInfoEnumValues = []SearchEventsBotInfo{
	SearchEventsBotInfoAll,
	SearchEventsBotInfoNone,
}

func (v *SearchEventsBotInfo) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}

	// Do not validate the value against the allowed values. The server
	// API may use new enum values before the SDK supports them
	// and that scenario must not result in deserialization failures.
	//
	// SDK users can limit the enum values they work with by
	// using the exported AllowedSearchEventsBotInfoEnumValues slice.
	*v = SearchEventsBotInfo(value)
	return nil
}
