/*
Server API

Fingerprint Server API allows you to get, search, and update Events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device.

API version: 4
Contact: support@fingerprint.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the ProxyDetails type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProxyDetails{}

// ProxyDetails Proxy detection details (present if `proxy` is `true`)
type ProxyDetails struct {
	// Residential proxies use real user IP addresses to appear as legitimate traffic,  while data center proxies are public proxies hosted in data centers
	ProxyType string `json:"proxy_type"`
	// Unix millisecond timestamp with hourly resolution of when this IP was last seen as a proxy
	LastSeenAt *int64 `json:"last_seen_at,omitempty"`
	// String representing the last proxy service provider detected when this IP was synced. An IP can be shared by multiple service providers.
	Provider             *string `json:"provider,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ProxyDetails ProxyDetails

func (o ProxyDetails) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProxyDetails) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["proxy_type"] = o.ProxyType
	if !IsNil(o.LastSeenAt) {
		toSerialize["last_seen_at"] = o.LastSeenAt
	}
	if !IsNil(o.Provider) {
		toSerialize["provider"] = o.Provider
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ProxyDetails) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"proxy_type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varProxyDetails := _ProxyDetails{}

	err = json.Unmarshal(data, &varProxyDetails)

	if err != nil {
		return err
	}

	*o = ProxyDetails(varProxyDetails)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "proxy_type")
		delete(additionalProperties, "last_seen_at")
		delete(additionalProperties, "provider")
		o.AdditionalProperties = additionalProperties
	}

	return err
}
