/*
Server API

Fingerprint Server API allows you to get, search, and update Events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device.

API version: 4
Contact: support@fingerprint.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// ErrorCode Error code: * `request_cannot_be_parsed` - The query parameters or JSON payload contains some errors   that prevented us from parsing it (wrong type/surpassed limits). * `secret_api_key_required` - secret API key in header is missing or empty. * `secret_api_key_not_found` - No Fingerprint workspace found for specified secret API key. * `public_api_key_required` - public API key in header is missing or empty. * `public_api_key_not_found` - No Fingerprint workspace found for specified public API key. * `subscription_not_active` - Fingerprint workspace is not active. * `wrong_region` - Server and workspace region differ. * `feature_not_enabled` - This feature (for example, Delete API) is not enabled for your workspace. * `request_not_found` - The specified event ID was not found. It never existed, expired, or it has been deleted. * `visitor_not_found` - The specified visitor ID was not found. It never existed or it may have already been deleted. * `too_many_requests` - The limit on secret API key requests per second has been exceeded. * `state_not_ready` - The event specified with event ID is   not ready for updates yet. Try again.   This error happens in rare cases when update API is called immediately   after receiving the event ID on the client. In case you need to send   information right away, we recommend using the JS agent API instead. * `failed` - Internal server error. * `event_not_found` - The specified event ID was not found. It never existed, expired, or it has been deleted. * `missing_module` - The request is invalid because it is missing a required module. * `payload_too_large` - The request payload is too large and cannot be processed. * `service_unavailable` - The service was unable to process the request. * `ruleset_not_found` - The specified ruleset was not found. It never existed or it has been deleted.
type ErrorCode string

// List of ErrorCode
const (
	ErrorCodeRequestCannotBeParsed ErrorCode = "request_cannot_be_parsed"
	ErrorCodeSecretAPIKeyRequired  ErrorCode = "secret_api_key_required"
	ErrorCodeSecretAPIKeyNotFound  ErrorCode = "secret_api_key_not_found"
	ErrorCodePublicAPIKeyRequired  ErrorCode = "public_api_key_required"
	ErrorCodePublicAPIKeyNotFound  ErrorCode = "public_api_key_not_found"
	ErrorCodeSubscriptionNotActive ErrorCode = "subscription_not_active"
	ErrorCodeWrongRegion           ErrorCode = "wrong_region"
	ErrorCodeFeatureNotEnabled     ErrorCode = "feature_not_enabled"
	ErrorCodeRequestNotFound       ErrorCode = "request_not_found"
	ErrorCodeVisitorNotFound       ErrorCode = "visitor_not_found"
	ErrorCodeTooManyRequests       ErrorCode = "too_many_requests"
	ErrorCodeStateNotReady         ErrorCode = "state_not_ready"
	ErrorCodeFailed                ErrorCode = "failed"
	ErrorCodeEventNotFound         ErrorCode = "event_not_found"
	ErrorCodeMissingModule         ErrorCode = "missing_module"
	ErrorCodePayloadTooLarge       ErrorCode = "payload_too_large"
	ErrorCodeServiceUnavailable    ErrorCode = "service_unavailable"
	ErrorCodeRulesetNotFound       ErrorCode = "ruleset_not_found"
)

// All allowed values of ErrorCode enum
var AllowedErrorCodeEnumValues = []ErrorCode{
	ErrorCodeRequestCannotBeParsed,
	ErrorCodeSecretAPIKeyRequired,
	ErrorCodeSecretAPIKeyNotFound,
	ErrorCodePublicAPIKeyRequired,
	ErrorCodePublicAPIKeyNotFound,
	ErrorCodeSubscriptionNotActive,
	ErrorCodeWrongRegion,
	ErrorCodeFeatureNotEnabled,
	ErrorCodeRequestNotFound,
	ErrorCodeVisitorNotFound,
	ErrorCodeTooManyRequests,
	ErrorCodeStateNotReady,
	ErrorCodeFailed,
	ErrorCodeEventNotFound,
	ErrorCodeMissingModule,
	ErrorCodePayloadTooLarge,
	ErrorCodeServiceUnavailable,
	ErrorCodeRulesetNotFound,
}

func (v *ErrorCode) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := ErrorCode(value)
	for _, existing := range AllowedErrorCodeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid ErrorCode", value)
}

// NewErrorCodeFromValue returns a pointer to a valid ErrorCode
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewErrorCodeFromValue(v string) (*ErrorCode, error) {
	ev := ErrorCode(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for ErrorCode: valid values are %v", v, AllowedErrorCodeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v ErrorCode) IsValid() bool {
	for _, existing := range AllowedErrorCodeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to ErrorCode value
func (v ErrorCode) Ptr() *ErrorCode {
	return &v
}

type NullableErrorCode struct {
	value *ErrorCode
	isSet bool
}

func (v NullableErrorCode) Get() *ErrorCode {
	return v.value
}

func (v *NullableErrorCode) Set(val *ErrorCode) {
	v.value = val
	v.isSet = true
}

func (v NullableErrorCode) IsSet() bool {
	return v.isSet
}

func (v *NullableErrorCode) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableErrorCode(val *ErrorCode) *NullableErrorCode {
	return &NullableErrorCode{value: val, isSet: true}
}

func (v NullableErrorCode) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableErrorCode) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
