/*
Server API

Fingerprint Server API allows you to get, search, and update Events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device. The API also supports collection of Automation Intelligence for requests to your server in edge, pre-origin, or middleware contexts.

API version: 4
Contact: support@fingerprint.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// Event - An identification event (`source: device`) or an Automation Intelligence event (`source: edge`).  Use `source` to tell them apart. Device events include Identification and device-derived Smart Signals. Edge events do not.  Consult the [Smart Signals reference](https://docs.fingerprint.com/docs/smart-signals-reference) for more details.
//
// SPIKE INTER-2457 — BREAKING CHANGE. DO NOT SHIP.
// Event used to have Identification, EventID, etc. as fields. It is now a oneOf
// wrapper: EventDevice *EventDevice; EventEdge *EventEdge. Callers of GetEvent /
// SearchEvents that read event.Identification fail to compile. Use
// event.EventDevice.Identification after checking which pointer is set.
type Event struct {
	EventDevice *EventDevice
	EventEdge   *EventEdge
}

// EventDeviceAsEvent is a convenience function that returns EventDevice wrapped in Event
func EventDeviceAsEvent(v *EventDevice) Event {
	return Event{
		EventDevice: v,
	}
}

// EventEdgeAsEvent is a convenience function that returns EventEdge wrapped in Event
func EventEdgeAsEvent(v *EventEdge) Event {
	return Event{
		EventEdge: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *Event) UnmarshalJSON(data []byte) error {
	var err error
	// use discriminator value to speed up the lookup
	var jsonDict map[string]interface{}
	err = newStrictDecoder(data).Decode(&jsonDict)
	if err != nil {
		return fmt.Errorf("failed to unmarshal JSON into map for the discriminator lookup")
	}

	// check if the discriminator value is 'device'
	if jsonDict["source"] == "device" {
		// try to unmarshal JSON data into EventDevice
		err = json.Unmarshal(data, &dst.EventDevice)
		if err == nil {
			return nil // data stored in dst.EventDevice, return on the first match
		} else {
			dst.EventDevice = nil
			return fmt.Errorf("failed to unmarshal Event as EventDevice: %s", err.Error())
		}
	}

	// check if the discriminator value is 'edge'
	if jsonDict["source"] == "edge" {
		// try to unmarshal JSON data into EventEdge
		err = json.Unmarshal(data, &dst.EventEdge)
		if err == nil {
			return nil // data stored in dst.EventEdge, return on the first match
		} else {
			dst.EventEdge = nil
			return fmt.Errorf("failed to unmarshal Event as EventEdge: %s", err.Error())
		}
	}

	return nil
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src Event) MarshalJSON() ([]byte, error) {
	if src.EventDevice != nil {
		return json.Marshal(&src.EventDevice)
	}

	if src.EventEdge != nil {
		return json.Marshal(&src.EventEdge)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *Event) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.EventDevice != nil {
		return obj.EventDevice
	}

	if obj.EventEdge != nil {
		return obj.EventEdge
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj Event) GetActualInstanceValue() interface{} {
	if obj.EventDevice != nil {
		return *obj.EventDevice
	}

	if obj.EventEdge != nil {
		return *obj.EventEdge
	}

	// all schemas are nil
	return nil
}

type NullableEvent struct {
	value *Event
	isSet bool
}

func (v NullableEvent) Get() *Event {
	return v.value
}

func (v *NullableEvent) Set(val *Event) {
	v.value = val
	v.isSet = true
}

func (v NullableEvent) IsSet() bool {
	return v.isSet
}

func (v *NullableEvent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEvent(val *Event) *NullableEvent {
	return &NullableEvent{value: val, isSet: true}
}

func (v NullableEvent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEvent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
