/*
Server API

Fingerprint Server API allows you to get, search, and update Events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device.

API version: 4
Contact: support@fingerprint.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the IPBlockList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IPBlockList{}

// IPBlockList struct for IPBlockList
type IPBlockList struct {
	// IP address was part of a known email spam attack (SMTP).
	EmailSpam *bool `json:"email_spam,omitempty"`
	// IP address was part of a known network attack (SSH/HTTPS).
	AttackSource *bool `json:"attack_source,omitempty"`
	// IP address was part of known TOR network activity.
	TorNode              *bool `json:"tor_node,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _IPBlockList IPBlockList

func (o IPBlockList) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IPBlockList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.EmailSpam) {
		toSerialize["email_spam"] = o.EmailSpam
	}
	if !IsNil(o.AttackSource) {
		toSerialize["attack_source"] = o.AttackSource
	}
	if !IsNil(o.TorNode) {
		toSerialize["tor_node"] = o.TorNode
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *IPBlockList) UnmarshalJSON(data []byte) (err error) {
	varIPBlockList := _IPBlockList{}

	err = json.Unmarshal(data, &varIPBlockList)

	if err != nil {
		return err
	}

	*o = IPBlockList(varIPBlockList)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "email_spam")
		delete(additionalProperties, "attack_source")
		delete(additionalProperties, "tor_node")
		o.AdditionalProperties = additionalProperties
	}

	return err
}
