/*
Server API

Fingerprint Server API allows you to get, search, and update Events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device.

API version: 4
Contact: support@fingerprint.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// SearchEventsBot Filter events by the Bot Detection result, specifically:   `all` - events where any kind of bot was detected.   `good` - events where a good bot was detected.   `bad` - events where a bad bot was detected.   `none` - events where no bot was detected. > Note: When using this parameter, only events with the `bot` property set to a valid value are returned. Events without a `bot` Smart Signal result are left out of the response.
type SearchEventsBot string

// List of SearchEventsBot
const (
	SearchEventsBotAll  SearchEventsBot = "all"
	SearchEventsBotGood SearchEventsBot = "good"
	SearchEventsBotBad  SearchEventsBot = "bad"
	SearchEventsBotNone SearchEventsBot = "none"
)

// All allowed values of SearchEventsBot enum
var AllowedSearchEventsBotEnumValues = []SearchEventsBot{
	SearchEventsBotAll,
	SearchEventsBotGood,
	SearchEventsBotBad,
	SearchEventsBotNone,
}

func (v *SearchEventsBot) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := SearchEventsBot(value)
	for _, existing := range AllowedSearchEventsBotEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid SearchEventsBot", value)
}
