/*
Server API

Fingerprint Server API allows you to get, search, and update Events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device. The API also supports collection of Automation Intelligence for requests to your server in edge, pre-origin, or middleware contexts.

API version: 4
Contact: support@fingerprint.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// SearchEventsInline the model 'SearchEventsInline'
type SearchEventsInline string

// List of SearchEventsInline
const (
	SearchEventsInlineEdge SearchEventsInline = "edge"
)

// All allowed values of SearchEventsInline enum
var AllowedSearchEventsInlineEnumValues = []SearchEventsInline{
	SearchEventsInlineEdge,
}

func (v *SearchEventsInline) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := SearchEventsInline(value)
	for _, existing := range AllowedSearchEventsInlineEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid SearchEventsInline", value)
}
