// Code generated by post-processing script. DO NOT EDIT.

package openapi

import outerapi "github.com/fingerprintjs/go-sdk/v8/openapi"

type MappedNullable = outerapi.MappedNullable

type BotInfo = outerapi.BotInfo
type BotInfoCategory = outerapi.BotInfoCategory
type BotInfoConfidence = outerapi.BotInfoConfidence
type BotInfoIdentity = outerapi.BotInfoIdentity
type BotResult = outerapi.BotResult
type BrowserDetails = outerapi.BrowserDetails
type Canvas = outerapi.Canvas
type Emoji = outerapi.Emoji
type Error = outerapi.Error
type ErrorCode = outerapi.ErrorCode
type ErrorResponse = outerapi.ErrorResponse
type Event = outerapi.Event
type EventRuleAction = outerapi.EventRuleAction
type EventRuleActionAllow = outerapi.EventRuleActionAllow
type EventRuleActionBlock = outerapi.EventRuleActionBlock
type EventSearch = outerapi.EventSearch
type EventUpdate = outerapi.EventUpdate
type FontPreferences = outerapi.FontPreferences
type Geolocation = outerapi.Geolocation
type GeolocationSubdivisionsInner = outerapi.GeolocationSubdivisionsInner
type Identification = outerapi.Identification
type IdentificationConfidence = outerapi.IdentificationConfidence
type IncrementalIdentificationStatus = outerapi.IncrementalIdentificationStatus
type Integration = outerapi.Integration
type IntegrationSubintegration = outerapi.IntegrationSubintegration
type IPBlockList = outerapi.IPBlockList
type IPInfo = outerapi.IPInfo
type LabelsInner = outerapi.LabelsInner
type NullableEventRuleAction = outerapi.NullableEventRuleAction
type PluginsInner = outerapi.PluginsInner
type PluginsInnerMimeTypesInner = outerapi.PluginsInnerMimeTypesInner
type Proximity = outerapi.Proximity
type ProxyConfidence = outerapi.ProxyConfidence
type ProxyDetails = outerapi.ProxyDetails
type RareDevicePercentileBucket = outerapi.RareDevicePercentileBucket
type RawDeviceAttributes = outerapi.RawDeviceAttributes
type RequestHeaderModifications = outerapi.RequestHeaderModifications
type RuleActionHeaderField = outerapi.RuleActionHeaderField
type RuleActionType = outerapi.RuleActionType
type SDK = outerapi.SDK
type SearchEventsBot = outerapi.SearchEventsBot
type SearchEventsBotInfo = outerapi.SearchEventsBotInfo
type SearchEventsIncrementalIdentificationStatus = outerapi.SearchEventsIncrementalIdentificationStatus
type SearchEventsRareDevicePercentileBucket = outerapi.SearchEventsRareDevicePercentileBucket
type SearchEventsSDKPlatform = outerapi.SearchEventsSDKPlatform
type SearchEventsVPNConfidence = outerapi.SearchEventsVPNConfidence
type SupplementaryIDHighRecall = outerapi.SupplementaryIDHighRecall
type TamperingConfidence = outerapi.TamperingConfidence
type TamperingDetails = outerapi.TamperingDetails
type TouchSupport = outerapi.TouchSupport
type Velocity = outerapi.Velocity
type VelocityData = outerapi.VelocityData
type VPNConfidence = outerapi.VPNConfidence
type VPNMethods = outerapi.VPNMethods
type WebGlBasics = outerapi.WebGlBasics
type WebGlExtensions = outerapi.WebGlExtensions
