/*
Server API

Fingerprint Server API allows you to get, search, and update Events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device. The API also supports collection of Automation Intelligence for requests to your server in edge, pre-origin, or middleware contexts.

API version: 4
Contact: support@fingerprint.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the DeviceDetails type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeviceDetails{}

// DeviceDetails Native, SDK-collected mobile device identification signals (manufacturer, model, and OS version). Structurally separate from the top-level `device`, `os`, and `os_version` fields and from `browser_details`, all of which are derived from user-agent parsing rather than native SDK signals.
type DeviceDetails struct {
	// Raw device manufacturer string as reported by the device OS. Not normalized: casing is vendor-defined (samsung, Xiaomi, OPPO, HUAWEI). Always `Apple` on iOS.
	DeviceManufacturer *string `json:"device_manufacturer,omitempty"`
	// Raw device model identifier, as reported by the mobile OS.
	DeviceModel *string `json:"device_model,omitempty"`
	// Mobile operating system version. Component count is not fixed and must not be assumed by consumers: iOS always reports `major.minor.patch` (e.g. `17.4.1`), while Android's precision varies by OS era and which raw signal resolved it — `major` only (`9`, `13`) since Android 10 dropped point releases, `major.minor` (`16.1`) from Android 16 (API 36+) reintroducing a minor component, or a genuine `major.minor.patch` (`8.1.0`) on pre-Android 10 devices that shipped real point releases. Never a fabricated/zero-padded component.
	OsVersion            *string `json:"os_version,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _DeviceDetails DeviceDetails

func (o DeviceDetails) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeviceDetails) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DeviceManufacturer) {
		toSerialize["device_manufacturer"] = o.DeviceManufacturer
	}
	if !IsNil(o.DeviceModel) {
		toSerialize["device_model"] = o.DeviceModel
	}
	if !IsNil(o.OsVersion) {
		toSerialize["os_version"] = o.OsVersion
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *DeviceDetails) UnmarshalJSON(data []byte) (err error) {
	varDeviceDetails := _DeviceDetails{}

	err = json.Unmarshal(data, &varDeviceDetails)

	if err != nil {
		return err
	}

	*o = DeviceDetails(varDeviceDetails)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "device_manufacturer")
		delete(additionalProperties, "device_model")
		delete(additionalProperties, "os_version")
		o.AdditionalProperties = additionalProperties
	}

	return err
}
