/*
Server API

Fingerprint Server API allows you to get, search, and update Events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device.

API version: 4
Contact: support@fingerprint.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the LabelsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LabelsInner{}

// LabelsInner struct for LabelsInner
type LabelsInner struct {
	Label                *string  `json:"label,omitempty"`
	Prediction           *bool    `json:"prediction,omitempty"`
	MlScore              *float64 `json:"ml_score,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _LabelsInner LabelsInner

func (o LabelsInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LabelsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Label) {
		toSerialize["label"] = o.Label
	}
	if !IsNil(o.Prediction) {
		toSerialize["prediction"] = o.Prediction
	}
	if !IsNil(o.MlScore) {
		toSerialize["ml_score"] = o.MlScore
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *LabelsInner) UnmarshalJSON(data []byte) (err error) {
	varLabelsInner := _LabelsInner{}

	err = json.Unmarshal(data, &varLabelsInner)

	if err != nil {
		return err
	}

	*o = LabelsInner(varLabelsInner)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "label")
		delete(additionalProperties, "prediction")
		delete(additionalProperties, "ml_score")
		o.AdditionalProperties = additionalProperties
	}

	return err
}
