/*
Server API

Fingerprint Server API allows you to get, search, and update Events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device.

API version: 4
Contact: support@fingerprint.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// BotInfoConfidence Confidence level of the bot identification.
type BotInfoConfidence string

// List of BotInfoConfidence
const (
	BotInfoConfidenceLow    BotInfoConfidence = "low"
	BotInfoConfidenceMedium BotInfoConfidence = "medium"
	BotInfoConfidenceHigh   BotInfoConfidence = "high"
)

// All allowed values of BotInfoConfidence enum
var AllowedBotInfoConfidenceEnumValues = []BotInfoConfidence{
	BotInfoConfidenceLow,
	BotInfoConfidenceMedium,
	BotInfoConfidenceHigh,
}

func (v *BotInfoConfidence) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := BotInfoConfidence(value)
	for _, existing := range AllowedBotInfoConfidenceEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid BotInfoConfidence", value)
}
