/*
Server API

Fingerprint Server API allows you to get, search, and update Events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device.

API version: 4
Contact: support@fingerprint.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the EventUpdate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EventUpdate{}

// EventUpdate struct for EventUpdate
type EventUpdate struct {
	// Linked Id value to assign to the existing event
	LinkedID *string `json:"linked_id,omitempty"`
	// A customer-provided value or an object that was sent with the identification request or updated later.
	Tags map[string]interface{} `json:"tags,omitempty"`
	// Suspect flag indicating observed suspicious or fraudulent event
	Suspect              *bool `json:"suspect,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _EventUpdate EventUpdate

func (o EventUpdate) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EventUpdate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.LinkedID) {
		toSerialize["linked_id"] = o.LinkedID
	}
	if !IsNil(o.Tags) {
		toSerialize["tags"] = o.Tags
	}
	if !IsNil(o.Suspect) {
		toSerialize["suspect"] = o.Suspect
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *EventUpdate) UnmarshalJSON(data []byte) (err error) {
	varEventUpdate := _EventUpdate{}

	err = json.Unmarshal(data, &varEventUpdate)

	if err != nil {
		return err
	}

	*o = EventUpdate(varEventUpdate)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "linked_id")
		delete(additionalProperties, "tags")
		delete(additionalProperties, "suspect")
		o.AdditionalProperties = additionalProperties
	}

	return err
}
