/*
Server API

Fingerprint Server API allows you to get, search, and update Events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device.

API version: 4
Contact: support@fingerprint.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the BotInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BotInfo{}

// BotInfo Extended bot information.
type BotInfo struct {
	// The type and purpose of the bot.
	Category string `json:"category"`
	// The organization or company operating the bot.
	Provider string `json:"provider"`
	// The URL of the bot provider's website.
	ProviderURL *string `json:"provider_url,omitempty"`
	// The specific name or identifier of the bot.
	Name string `json:"name"`
	// The verification status of the bot's identity:  * `verified` - well-known bot with publicly verifiable identity, directed by the bot provider.  * `signed` - bot that signs its platform via Web Bot Auth, directed by the bot provider’s customers.  * `spoofed` - bot that claims a public identity but fails verification.  * `unknown` - bot that does not publish a verifiable identity.
	Identity string `json:"identity"`
	// Confidence level of the bot identification.
	Confidence           string `json:"confidence"`
	AdditionalProperties map[string]interface{}
}

type _BotInfo BotInfo

func (o BotInfo) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BotInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["category"] = o.Category
	toSerialize["provider"] = o.Provider
	if !IsNil(o.ProviderURL) {
		toSerialize["provider_url"] = o.ProviderURL
	}
	toSerialize["name"] = o.Name
	toSerialize["identity"] = o.Identity
	toSerialize["confidence"] = o.Confidence

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *BotInfo) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"category",
		"provider",
		"name",
		"identity",
		"confidence",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBotInfo := _BotInfo{}

	err = json.Unmarshal(data, &varBotInfo)

	if err != nil {
		return err
	}

	*o = BotInfo(varBotInfo)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "category")
		delete(additionalProperties, "provider")
		delete(additionalProperties, "provider_url")
		delete(additionalProperties, "name")
		delete(additionalProperties, "identity")
		delete(additionalProperties, "confidence")
		o.AdditionalProperties = additionalProperties
	}

	return err
}
