# sets generator options.
generator:
  # sets generator features.
  features:
    enable:
      # Enables paths client generation
      - "paths/client"
      - "webhooks/client"
    disable_all: true