/*
Server API

Fingerprint Server API allows you to get, search, and update Events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device. 

API version: 4
Contact: support@fingerprint.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fingerprint

import (
	"encoding/json"
)

// checks if the VpnMethods type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VpnMethods{}

// VpnMethods struct for VpnMethods
type VpnMethods struct {
	// The browser timezone doesn't match the timezone inferred from the request IP address.
	TimezoneMismatch *bool `json:"timezone_mismatch,omitempty"`
	// Request IP address is owned and used by a public VPN service provider.
	PublicVpn *bool `json:"public_vpn,omitempty"`
	// This method applies to mobile devices only. Indicates the result of additional methods used to detect a VPN in mobile devices.
	AuxiliaryMobile *bool `json:"auxiliary_mobile,omitempty"`
	// The browser runs on a different operating system than the operating system inferred from the request network signature.
	OsMismatch *bool `json:"os_mismatch,omitempty"`
	// Request IP address belongs to a relay service provider, indicating the use of relay services like [Apple Private relay](https://support.apple.com/en-us/102602) or [Cloudflare Warp](https://developers.cloudflare.com/warp-client/).  * Like VPNs, relay services anonymize the visitor's true IP address. * Unlike traditional VPNs, relay services don't let visitors spoof their location by choosing an exit node in a different country.  This field allows you to differentiate VPN users and relay service users in your fraud prevention logic. 
	Relay *bool `json:"relay,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _VpnMethods VpnMethods

// NewVpnMethods instantiates a new VpnMethods object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVpnMethods() *VpnMethods {
	this := VpnMethods{}
	return &this
}

// NewVpnMethodsWithDefaults instantiates a new VpnMethods object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVpnMethodsWithDefaults() *VpnMethods {
	this := VpnMethods{}
	return &this
}

// GetTimezoneMismatch returns the TimezoneMismatch field value if set, zero value otherwise.
func (o *VpnMethods) GetTimezoneMismatch() bool {
	if o == nil || IsNil(o.TimezoneMismatch) {
		var ret bool
		return ret
	}
	return *o.TimezoneMismatch
}

// GetTimezoneMismatchOk returns a tuple with the TimezoneMismatch field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VpnMethods) GetTimezoneMismatchOk() (*bool, bool) {
	if o == nil || IsNil(o.TimezoneMismatch) {
		return nil, false
	}
	return o.TimezoneMismatch, true
}

// HasTimezoneMismatch returns a boolean if a field has been set.
func (o *VpnMethods) HasTimezoneMismatch() bool {
	if o != nil && !IsNil(o.TimezoneMismatch) {
		return true
	}

	return false
}

// SetTimezoneMismatch gets a reference to the given bool and assigns it to the TimezoneMismatch field.
func (o *VpnMethods) SetTimezoneMismatch(v bool) {
	o.TimezoneMismatch = &v
}

// GetPublicVpn returns the PublicVpn field value if set, zero value otherwise.
func (o *VpnMethods) GetPublicVpn() bool {
	if o == nil || IsNil(o.PublicVpn) {
		var ret bool
		return ret
	}
	return *o.PublicVpn
}

// GetPublicVpnOk returns a tuple with the PublicVpn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VpnMethods) GetPublicVpnOk() (*bool, bool) {
	if o == nil || IsNil(o.PublicVpn) {
		return nil, false
	}
	return o.PublicVpn, true
}

// HasPublicVpn returns a boolean if a field has been set.
func (o *VpnMethods) HasPublicVpn() bool {
	if o != nil && !IsNil(o.PublicVpn) {
		return true
	}

	return false
}

// SetPublicVpn gets a reference to the given bool and assigns it to the PublicVpn field.
func (o *VpnMethods) SetPublicVpn(v bool) {
	o.PublicVpn = &v
}

// GetAuxiliaryMobile returns the AuxiliaryMobile field value if set, zero value otherwise.
func (o *VpnMethods) GetAuxiliaryMobile() bool {
	if o == nil || IsNil(o.AuxiliaryMobile) {
		var ret bool
		return ret
	}
	return *o.AuxiliaryMobile
}

// GetAuxiliaryMobileOk returns a tuple with the AuxiliaryMobile field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VpnMethods) GetAuxiliaryMobileOk() (*bool, bool) {
	if o == nil || IsNil(o.AuxiliaryMobile) {
		return nil, false
	}
	return o.AuxiliaryMobile, true
}

// HasAuxiliaryMobile returns a boolean if a field has been set.
func (o *VpnMethods) HasAuxiliaryMobile() bool {
	if o != nil && !IsNil(o.AuxiliaryMobile) {
		return true
	}

	return false
}

// SetAuxiliaryMobile gets a reference to the given bool and assigns it to the AuxiliaryMobile field.
func (o *VpnMethods) SetAuxiliaryMobile(v bool) {
	o.AuxiliaryMobile = &v
}

// GetOsMismatch returns the OsMismatch field value if set, zero value otherwise.
func (o *VpnMethods) GetOsMismatch() bool {
	if o == nil || IsNil(o.OsMismatch) {
		var ret bool
		return ret
	}
	return *o.OsMismatch
}

// GetOsMismatchOk returns a tuple with the OsMismatch field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VpnMethods) GetOsMismatchOk() (*bool, bool) {
	if o == nil || IsNil(o.OsMismatch) {
		return nil, false
	}
	return o.OsMismatch, true
}

// HasOsMismatch returns a boolean if a field has been set.
func (o *VpnMethods) HasOsMismatch() bool {
	if o != nil && !IsNil(o.OsMismatch) {
		return true
	}

	return false
}

// SetOsMismatch gets a reference to the given bool and assigns it to the OsMismatch field.
func (o *VpnMethods) SetOsMismatch(v bool) {
	o.OsMismatch = &v
}

// GetRelay returns the Relay field value if set, zero value otherwise.
func (o *VpnMethods) GetRelay() bool {
	if o == nil || IsNil(o.Relay) {
		var ret bool
		return ret
	}
	return *o.Relay
}

// GetRelayOk returns a tuple with the Relay field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VpnMethods) GetRelayOk() (*bool, bool) {
	if o == nil || IsNil(o.Relay) {
		return nil, false
	}
	return o.Relay, true
}

// HasRelay returns a boolean if a field has been set.
func (o *VpnMethods) HasRelay() bool {
	if o != nil && !IsNil(o.Relay) {
		return true
	}

	return false
}

// SetRelay gets a reference to the given bool and assigns it to the Relay field.
func (o *VpnMethods) SetRelay(v bool) {
	o.Relay = &v
}

func (o VpnMethods) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VpnMethods) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TimezoneMismatch) {
		toSerialize["timezone_mismatch"] = o.TimezoneMismatch
	}
	if !IsNil(o.PublicVpn) {
		toSerialize["public_vpn"] = o.PublicVpn
	}
	if !IsNil(o.AuxiliaryMobile) {
		toSerialize["auxiliary_mobile"] = o.AuxiliaryMobile
	}
	if !IsNil(o.OsMismatch) {
		toSerialize["os_mismatch"] = o.OsMismatch
	}
	if !IsNil(o.Relay) {
		toSerialize["relay"] = o.Relay
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *VpnMethods) UnmarshalJSON(data []byte) (err error) {
	varVpnMethods := _VpnMethods{}

	err = json.Unmarshal(data, &varVpnMethods)

	if err != nil {
		return err
	}

	*o = VpnMethods(varVpnMethods)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "timezone_mismatch")
		delete(additionalProperties, "public_vpn")
		delete(additionalProperties, "auxiliary_mobile")
		delete(additionalProperties, "os_mismatch")
		delete(additionalProperties, "relay")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableVpnMethods struct {
	value *VpnMethods
	isSet bool
}

func (v NullableVpnMethods) Get() *VpnMethods {
	return v.value
}

func (v *NullableVpnMethods) Set(val *VpnMethods) {
	v.value = val
	v.isSet = true
}

func (v NullableVpnMethods) IsSet() bool {
	return v.isSet
}

func (v *NullableVpnMethods) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVpnMethods(val *VpnMethods) *NullableVpnMethods {
	return &NullableVpnMethods{value: val, isSet: true}
}

func (v NullableVpnMethods) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVpnMethods) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


