/*
Server API

Fingerprint Server API allows you to get, search, and update Events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device.

API version: 4
Contact: support@fingerprint.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fingerprint

import (
	"encoding/json"
	"fmt"
)

// checks if the Event type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Event{}

// Event Contains results from Fingerprint Identification and all active Smart Signals.
type Event struct {
	// Unique identifier of the user's request. The first portion of the event_id is a unix epoch milliseconds timestamp For example: `1758130560902.8tRtrH`
	EventID string `json:"event_id"`
	// Timestamp of the event with millisecond precision in Unix time.
	Timestamp int64 `json:"timestamp"`
	// A customer-provided id that was sent with the request.
	LinkedID *string `json:"linked_id,omitempty"`
	// Environment Id of the event. For example: `ae_47abaca3db2c7c43`
	EnvironmentID *string `json:"environment_id,omitempty"`
	// Field is `true` if you have previously set the `suspect` flag for this event using the [Server API Update event endpoint](https://dev.fingerprint.com/reference/updateevent).
	Suspect *bool `json:"suspect,omitempty"`
	SDK     *SDK  `json:"sdk,omitempty"`
	// `true` if we determined that this payload was replayed, `false` otherwise.
	Replayed                  *bool                      `json:"replayed,omitempty"`
	Identification            *Identification            `json:"identification,omitempty"`
	SupplementaryIDHighRecall *SupplementaryIDHighRecall `json:"supplementary_id_high_recall,omitempty"`
	// A customer-provided value or an object that was sent with the identification request or updated later.
	Tags map[string]interface{} `json:"tags,omitempty"`
	// Page URL from which the request was sent. For example `https://example.com/`
	URL *string `json:"url,omitempty"`
	// Bundle Id of the iOS application integrated with the Fingerprint SDK for the event. For example: `com.foo.app`
	BundleID *string `json:"bundle_id,omitempty"`
	// Package name of the Android application integrated with the Fingerprint SDK for the event. For example: `com.foo.app`
	PackageName *string `json:"package_name,omitempty"`
	// IP address of the requesting browser or bot.
	IPAddress *string `json:"ip_address,omitempty"`
	// User Agent of the client, for example: `Mozilla/5.0 (Windows NT 6.1; Win64; x64) ....`
	UserAgent *string `json:"user_agent,omitempty"`
	// Client Referrer field corresponds to the `document.referrer` field gathered during an identification request. The value is an empty string if the user navigated to the page directly (not through a link, but, for example, by using a bookmark) For example: `https://example.com/blog/my-article`
	ClientReferrer *string         `json:"client_referrer,omitempty"`
	BrowserDetails *BrowserDetails `json:"browser_details,omitempty"`
	Proximity      *Proximity      `json:"proximity,omitempty"`
	Bot            *BotResult      `json:"bot,omitempty"`
	// Additional classification of the bot type if detected.
	BotType *string  `json:"bot_type,omitempty"`
	BotInfo *BotInfo `json:"bot_info,omitempty"`
	// Android specific cloned application detection. There are 2 values:  * `true` - Presence of app cloners work detected (e.g. fully cloned application found or launch of it inside of a not main working profile detected). * `false` - No signs of cloned application detected or the client is not Android.
	ClonedApp *bool `json:"cloned_app,omitempty"`
	// `true` if the browser is Chrome with DevTools open or Firefox with Developer Tools open, `false` otherwise.
	DeveloperTools *bool `json:"developer_tools,omitempty"`
	// Android specific emulator detection. There are 2 values:  * `true` - Emulated environment detected (e.g. launch inside of AVD).  * `false` - No signs of emulated environment detected or the client is not Android.
	Emulator *bool `json:"emulator,omitempty"`
	// The time of the most recent factory reset that happened on the **mobile device** is expressed as Unix epoch time. When a factory reset cannot be detected on the mobile device or when the request is initiated from a browser,  this field will correspond to the *epoch* time (i.e 1 Jan 1970 UTC) as a value of 0. See [Factory Reset Detection](https://dev.fingerprint.com/docs/smart-signals-overview#factory-reset-detection) to learn more about this Smart Signal.
	FactoryResetTimestamp *int64 `json:"factory_reset_timestamp,omitempty"`
	// [Frida](https://frida.re/docs/) detection for Android and iOS devices. There are 2 values: * `true` - Frida detected * `false` - No signs of Frida or the client is not a mobile device.
	Frida       *bool        `json:"frida,omitempty"`
	IPBlocklist *IPBlockList `json:"ip_blocklist,omitempty"`
	IPInfo      *IPInfo      `json:"ip_info,omitempty"`
	// IP address was used by a public proxy provider or belonged to a known recent residential proxy
	Proxy           *bool            `json:"proxy,omitempty"`
	ProxyConfidence *ProxyConfidence `json:"proxy_confidence,omitempty"`
	ProxyDetails    *ProxyDetails    `json:"proxy_details,omitempty"`
	// `true` if we detected incognito mode used in the browser, `false` otherwise.
	Incognito *bool `json:"incognito,omitempty"`
	// iOS specific jailbreak detection. There are 2 values:  * `true` - Jailbreak detected. * `false` - No signs of jailbreak or the client is not iOS.
	Jailbroken *bool `json:"jailbroken,omitempty"`
	// Flag indicating whether the request came from a mobile device with location spoofing enabled.
	LocationSpoofing *bool `json:"location_spoofing,omitempty"`
	// * `true` - When requests made from your users' mobile devices to Fingerprint servers have been intercepted and potentially modified.  * `false` - Otherwise or when the request originated from a browser. See [MitM Attack Detection](https://dev.fingerprint.com/docs/smart-signals-reference#mitm-attack-detection) to learn more about this Smart Signal.
	MITMAttack *bool `json:"mitm_attack,omitempty"`
	// `true` if the request is from a privacy aware browser (e.g. Tor) or from a browser in which fingerprinting is blocked. Otherwise `false`.
	PrivacySettings *bool `json:"privacy_settings,omitempty"`
	// Android specific root management apps detection. There are 2 values:  * `true` - Root Management Apps detected (e.g. Magisk). * `false` - No Root Management Apps detected or the client isn't Android.
	RootApps   *bool            `json:"root_apps,omitempty"`
	RuleAction *EventRuleAction `json:"rule_action,omitempty"`
	// Suspect Score is an easy way to integrate Smart Signals into your fraud protection work flow.  It is a weighted representation of all Smart Signals present in the payload that helps identify suspicious activity. The value range is [0; S] where S is sum of all Smart Signals weights.  See more details here: https://dev.fingerprint.com/docs/suspect-score
	SuspectScore *int32 `json:"suspect_score,omitempty"`
	// Flag indicating browser tampering was detected. This happens when either:   * There are inconsistencies in the browser configuration that cross internal tampering thresholds (see `tampering_details.anomaly_score`).   * The browser signature resembles an \"anti-detect\" browser specifically designed to evade fingerprinting (see `tampering_details.anti_detect_browser`).
	Tampering        *bool             `json:"tampering,omitempty"`
	TamperingDetails *TamperingDetails `json:"tampering_details,omitempty"`
	Velocity         *Velocity         `json:"velocity,omitempty"`
	// `true` if the request came from a browser running inside a virtual machine (e.g. VMWare), `false` otherwise.
	VirtualMachine *bool `json:"virtual_machine,omitempty"`
	// VPN or other anonymizing service has been used when sending the request.
	VPN           *bool          `json:"vpn,omitempty"`
	VPNConfidence *VPNConfidence `json:"vpn_confidence,omitempty"`
	// Local timezone which is used in timezone_mismatch method.
	VPNOriginTimezone *string `json:"vpn_origin_timezone,omitempty"`
	// Country of the request (only for Android SDK version >= 2.4.0, ISO 3166 format or unknown).
	VPNOriginCountry *string     `json:"vpn_origin_country,omitempty"`
	VPNMethods       *VPNMethods `json:"vpn_methods,omitempty"`
	// Flag indicating if the request came from a high-activity visitor.
	HighActivityDevice   *bool                `json:"high_activity_device,omitempty"`
	RawDeviceAttributes  *RawDeviceAttributes `json:"raw_device_attributes,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _Event Event

// NewEvent instantiates a new Event object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEvent(eventID string, timestamp int64) *Event {
	this := Event{}
	this.EventID = eventID
	this.Timestamp = timestamp
	return &this
}

// NewEventWithDefaults instantiates a new Event object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEventWithDefaults() *Event {
	this := Event{}
	return &this
}

// GetEventID returns the EventID field value
func (o *Event) GetEventID() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EventID
}

// GetEventIDOk returns a tuple with the EventID field value
// and a boolean to check if the value has been set.
func (o *Event) GetEventIDOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EventID, true
}

// SetEventID sets field value
func (o *Event) SetEventID(v string) {
	o.EventID = v
}

// GetTimestamp returns the Timestamp field value
func (o *Event) GetTimestamp() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Timestamp
}

// GetTimestampOk returns a tuple with the Timestamp field value
// and a boolean to check if the value has been set.
func (o *Event) GetTimestampOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Timestamp, true
}

// SetTimestamp sets field value
func (o *Event) SetTimestamp(v int64) {
	o.Timestamp = v
}

// GetLinkedID returns the LinkedID field value if set, zero value otherwise.
func (o *Event) GetLinkedID() string {
	if o == nil || IsNil(o.LinkedID) {
		var ret string
		return ret
	}
	return *o.LinkedID
}

// GetLinkedIDOk returns a tuple with the LinkedID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Event) GetLinkedIDOk() (*string, bool) {
	if o == nil || IsNil(o.LinkedID) {
		return nil, false
	}
	return o.LinkedID, true
}

// HasLinkedID returns a boolean if a field has been set.
func (o *Event) HasLinkedID() bool {
	if o != nil && !IsNil(o.LinkedID) {
		return true
	}

	return false
}

// SetLinkedID gets a reference to the given string and assigns it to the LinkedID field.
func (o *Event) SetLinkedID(v string) {
	o.LinkedID = &v
}

// GetEnvironmentID returns the EnvironmentID field value if set, zero value otherwise.
func (o *Event) GetEnvironmentID() string {
	if o == nil || IsNil(o.EnvironmentID) {
		var ret string
		return ret
	}
	return *o.EnvironmentID
}

// GetEnvironmentIDOk returns a tuple with the EnvironmentID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Event) GetEnvironmentIDOk() (*string, bool) {
	if o == nil || IsNil(o.EnvironmentID) {
		return nil, false
	}
	return o.EnvironmentID, true
}

// HasEnvironmentID returns a boolean if a field has been set.
func (o *Event) HasEnvironmentID() bool {
	if o != nil && !IsNil(o.EnvironmentID) {
		return true
	}

	return false
}

// SetEnvironmentID gets a reference to the given string and assigns it to the EnvironmentID field.
func (o *Event) SetEnvironmentID(v string) {
	o.EnvironmentID = &v
}

// GetSuspect returns the Suspect field value if set, zero value otherwise.
func (o *Event) GetSuspect() bool {
	if o == nil || IsNil(o.Suspect) {
		var ret bool
		return ret
	}
	return *o.Suspect
}

// GetSuspectOk returns a tuple with the Suspect field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Event) GetSuspectOk() (*bool, bool) {
	if o == nil || IsNil(o.Suspect) {
		return nil, false
	}
	return o.Suspect, true
}

// HasSuspect returns a boolean if a field has been set.
func (o *Event) HasSuspect() bool {
	if o != nil && !IsNil(o.Suspect) {
		return true
	}

	return false
}

// SetSuspect gets a reference to the given bool and assigns it to the Suspect field.
func (o *Event) SetSuspect(v bool) {
	o.Suspect = &v
}

// GetSDK returns the SDK field value if set, zero value otherwise.
func (o *Event) GetSDK() SDK {
	if o == nil || IsNil(o.SDK) {
		var ret SDK
		return ret
	}
	return *o.SDK
}

// GetSDKOk returns a tuple with the SDK field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Event) GetSDKOk() (*SDK, bool) {
	if o == nil || IsNil(o.SDK) {
		return nil, false
	}
	return o.SDK, true
}

// HasSDK returns a boolean if a field has been set.
func (o *Event) HasSDK() bool {
	if o != nil && !IsNil(o.SDK) {
		return true
	}

	return false
}

// SetSDK gets a reference to the given SDK and assigns it to the SDK field.
func (o *Event) SetSDK(v SDK) {
	o.SDK = &v
}

// GetReplayed returns the Replayed field value if set, zero value otherwise.
func (o *Event) GetReplayed() bool {
	if o == nil || IsNil(o.Replayed) {
		var ret bool
		return ret
	}
	return *o.Replayed
}

// GetReplayedOk returns a tuple with the Replayed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Event) GetReplayedOk() (*bool, bool) {
	if o == nil || IsNil(o.Replayed) {
		return nil, false
	}
	return o.Replayed, true
}

// HasReplayed returns a boolean if a field has been set.
func (o *Event) HasReplayed() bool {
	if o != nil && !IsNil(o.Replayed) {
		return true
	}

	return false
}

// SetReplayed gets a reference to the given bool and assigns it to the Replayed field.
func (o *Event) SetReplayed(v bool) {
	o.Replayed = &v
}

// GetIdentification returns the Identification field value if set, zero value otherwise.
func (o *Event) GetIdentification() Identification {
	if o == nil || IsNil(o.Identification) {
		var ret Identification
		return ret
	}
	return *o.Identification
}

// GetIdentificationOk returns a tuple with the Identification field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Event) GetIdentificationOk() (*Identification, bool) {
	if o == nil || IsNil(o.Identification) {
		return nil, false
	}
	return o.Identification, true
}

// HasIdentification returns a boolean if a field has been set.
func (o *Event) HasIdentification() bool {
	if o != nil && !IsNil(o.Identification) {
		return true
	}

	return false
}

// SetIdentification gets a reference to the given Identification and assigns it to the Identification field.
func (o *Event) SetIdentification(v Identification) {
	o.Identification = &v
}

// GetSupplementaryIDHighRecall returns the SupplementaryIDHighRecall field value if set, zero value otherwise.
func (o *Event) GetSupplementaryIDHighRecall() SupplementaryIDHighRecall {
	if o == nil || IsNil(o.SupplementaryIDHighRecall) {
		var ret SupplementaryIDHighRecall
		return ret
	}
	return *o.SupplementaryIDHighRecall
}

// GetSupplementaryIDHighRecallOk returns a tuple with the SupplementaryIDHighRecall field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Event) GetSupplementaryIDHighRecallOk() (*SupplementaryIDHighRecall, bool) {
	if o == nil || IsNil(o.SupplementaryIDHighRecall) {
		return nil, false
	}
	return o.SupplementaryIDHighRecall, true
}

// HasSupplementaryIDHighRecall returns a boolean if a field has been set.
func (o *Event) HasSupplementaryIDHighRecall() bool {
	if o != nil && !IsNil(o.SupplementaryIDHighRecall) {
		return true
	}

	return false
}

// SetSupplementaryIDHighRecall gets a reference to the given SupplementaryIDHighRecall and assigns it to the SupplementaryIDHighRecall field.
func (o *Event) SetSupplementaryIDHighRecall(v SupplementaryIDHighRecall) {
	o.SupplementaryIDHighRecall = &v
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *Event) GetTags() map[string]interface{} {
	if o == nil || IsNil(o.Tags) {
		var ret map[string]interface{}
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Event) GetTagsOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Tags) {
		return map[string]interface{}{}, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *Event) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given map[string]interface{} and assigns it to the Tags field.
func (o *Event) SetTags(v map[string]interface{}) {
	o.Tags = v
}

// GetURL returns the URL field value if set, zero value otherwise.
func (o *Event) GetURL() string {
	if o == nil || IsNil(o.URL) {
		var ret string
		return ret
	}
	return *o.URL
}

// GetURLOk returns a tuple with the URL field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Event) GetURLOk() (*string, bool) {
	if o == nil || IsNil(o.URL) {
		return nil, false
	}
	return o.URL, true
}

// HasURL returns a boolean if a field has been set.
func (o *Event) HasURL() bool {
	if o != nil && !IsNil(o.URL) {
		return true
	}

	return false
}

// SetURL gets a reference to the given string and assigns it to the URL field.
func (o *Event) SetURL(v string) {
	o.URL = &v
}

// GetBundleID returns the BundleID field value if set, zero value otherwise.
func (o *Event) GetBundleID() string {
	if o == nil || IsNil(o.BundleID) {
		var ret string
		return ret
	}
	return *o.BundleID
}

// GetBundleIDOk returns a tuple with the BundleID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Event) GetBundleIDOk() (*string, bool) {
	if o == nil || IsNil(o.BundleID) {
		return nil, false
	}
	return o.BundleID, true
}

// HasBundleID returns a boolean if a field has been set.
func (o *Event) HasBundleID() bool {
	if o != nil && !IsNil(o.BundleID) {
		return true
	}

	return false
}

// SetBundleID gets a reference to the given string and assigns it to the BundleID field.
func (o *Event) SetBundleID(v string) {
	o.BundleID = &v
}

// GetPackageName returns the PackageName field value if set, zero value otherwise.
func (o *Event) GetPackageName() string {
	if o == nil || IsNil(o.PackageName) {
		var ret string
		return ret
	}
	return *o.PackageName
}

// GetPackageNameOk returns a tuple with the PackageName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Event) GetPackageNameOk() (*string, bool) {
	if o == nil || IsNil(o.PackageName) {
		return nil, false
	}
	return o.PackageName, true
}

// HasPackageName returns a boolean if a field has been set.
func (o *Event) HasPackageName() bool {
	if o != nil && !IsNil(o.PackageName) {
		return true
	}

	return false
}

// SetPackageName gets a reference to the given string and assigns it to the PackageName field.
func (o *Event) SetPackageName(v string) {
	o.PackageName = &v
}

// GetIPAddress returns the IPAddress field value if set, zero value otherwise.
func (o *Event) GetIPAddress() string {
	if o == nil || IsNil(o.IPAddress) {
		var ret string
		return ret
	}
	return *o.IPAddress
}

// GetIPAddressOk returns a tuple with the IPAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Event) GetIPAddressOk() (*string, bool) {
	if o == nil || IsNil(o.IPAddress) {
		return nil, false
	}
	return o.IPAddress, true
}

// HasIPAddress returns a boolean if a field has been set.
func (o *Event) HasIPAddress() bool {
	if o != nil && !IsNil(o.IPAddress) {
		return true
	}

	return false
}

// SetIPAddress gets a reference to the given string and assigns it to the IPAddress field.
func (o *Event) SetIPAddress(v string) {
	o.IPAddress = &v
}

// GetUserAgent returns the UserAgent field value if set, zero value otherwise.
func (o *Event) GetUserAgent() string {
	if o == nil || IsNil(o.UserAgent) {
		var ret string
		return ret
	}
	return *o.UserAgent
}

// GetUserAgentOk returns a tuple with the UserAgent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Event) GetUserAgentOk() (*string, bool) {
	if o == nil || IsNil(o.UserAgent) {
		return nil, false
	}
	return o.UserAgent, true
}

// HasUserAgent returns a boolean if a field has been set.
func (o *Event) HasUserAgent() bool {
	if o != nil && !IsNil(o.UserAgent) {
		return true
	}

	return false
}

// SetUserAgent gets a reference to the given string and assigns it to the UserAgent field.
func (o *Event) SetUserAgent(v string) {
	o.UserAgent = &v
}

// GetClientReferrer returns the ClientReferrer field value if set, zero value otherwise.
func (o *Event) GetClientReferrer() string {
	if o == nil || IsNil(o.ClientReferrer) {
		var ret string
		return ret
	}
	return *o.ClientReferrer
}

// GetClientReferrerOk returns a tuple with the ClientReferrer field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Event) GetClientReferrerOk() (*string, bool) {
	if o == nil || IsNil(o.ClientReferrer) {
		return nil, false
	}
	return o.ClientReferrer, true
}

// HasClientReferrer returns a boolean if a field has been set.
func (o *Event) HasClientReferrer() bool {
	if o != nil && !IsNil(o.ClientReferrer) {
		return true
	}

	return false
}

// SetClientReferrer gets a reference to the given string and assigns it to the ClientReferrer field.
func (o *Event) SetClientReferrer(v string) {
	o.ClientReferrer = &v
}

// GetBrowserDetails returns the BrowserDetails field value if set, zero value otherwise.
func (o *Event) GetBrowserDetails() BrowserDetails {
	if o == nil || IsNil(o.BrowserDetails) {
		var ret BrowserDetails
		return ret
	}
	return *o.BrowserDetails
}

// GetBrowserDetailsOk returns a tuple with the BrowserDetails field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Event) GetBrowserDetailsOk() (*BrowserDetails, bool) {
	if o == nil || IsNil(o.BrowserDetails) {
		return nil, false
	}
	return o.BrowserDetails, true
}

// HasBrowserDetails returns a boolean if a field has been set.
func (o *Event) HasBrowserDetails() bool {
	if o != nil && !IsNil(o.BrowserDetails) {
		return true
	}

	return false
}

// SetBrowserDetails gets a reference to the given BrowserDetails and assigns it to the BrowserDetails field.
func (o *Event) SetBrowserDetails(v BrowserDetails) {
	o.BrowserDetails = &v
}

// GetProximity returns the Proximity field value if set, zero value otherwise.
func (o *Event) GetProximity() Proximity {
	if o == nil || IsNil(o.Proximity) {
		var ret Proximity
		return ret
	}
	return *o.Proximity
}

// GetProximityOk returns a tuple with the Proximity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Event) GetProximityOk() (*Proximity, bool) {
	if o == nil || IsNil(o.Proximity) {
		return nil, false
	}
	return o.Proximity, true
}

// HasProximity returns a boolean if a field has been set.
func (o *Event) HasProximity() bool {
	if o != nil && !IsNil(o.Proximity) {
		return true
	}

	return false
}

// SetProximity gets a reference to the given Proximity and assigns it to the Proximity field.
func (o *Event) SetProximity(v Proximity) {
	o.Proximity = &v
}

// GetBot returns the Bot field value if set, zero value otherwise.
func (o *Event) GetBot() BotResult {
	if o == nil || IsNil(o.Bot) {
		var ret BotResult
		return ret
	}
	return *o.Bot
}

// GetBotOk returns a tuple with the Bot field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Event) GetBotOk() (*BotResult, bool) {
	if o == nil || IsNil(o.Bot) {
		return nil, false
	}
	return o.Bot, true
}

// HasBot returns a boolean if a field has been set.
func (o *Event) HasBot() bool {
	if o != nil && !IsNil(o.Bot) {
		return true
	}

	return false
}

// SetBot gets a reference to the given BotResult and assigns it to the Bot field.
func (o *Event) SetBot(v BotResult) {
	o.Bot = &v
}

// GetBotType returns the BotType field value if set, zero value otherwise.
func (o *Event) GetBotType() string {
	if o == nil || IsNil(o.BotType) {
		var ret string
		return ret
	}
	return *o.BotType
}

// GetBotTypeOk returns a tuple with the BotType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Event) GetBotTypeOk() (*string, bool) {
	if o == nil || IsNil(o.BotType) {
		return nil, false
	}
	return o.BotType, true
}

// HasBotType returns a boolean if a field has been set.
func (o *Event) HasBotType() bool {
	if o != nil && !IsNil(o.BotType) {
		return true
	}

	return false
}

// SetBotType gets a reference to the given string and assigns it to the BotType field.
func (o *Event) SetBotType(v string) {
	o.BotType = &v
}

// GetBotInfo returns the BotInfo field value if set, zero value otherwise.
func (o *Event) GetBotInfo() BotInfo {
	if o == nil || IsNil(o.BotInfo) {
		var ret BotInfo
		return ret
	}
	return *o.BotInfo
}

// GetBotInfoOk returns a tuple with the BotInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Event) GetBotInfoOk() (*BotInfo, bool) {
	if o == nil || IsNil(o.BotInfo) {
		return nil, false
	}
	return o.BotInfo, true
}

// HasBotInfo returns a boolean if a field has been set.
func (o *Event) HasBotInfo() bool {
	if o != nil && !IsNil(o.BotInfo) {
		return true
	}

	return false
}

// SetBotInfo gets a reference to the given BotInfo and assigns it to the BotInfo field.
func (o *Event) SetBotInfo(v BotInfo) {
	o.BotInfo = &v
}

// GetClonedApp returns the ClonedApp field value if set, zero value otherwise.
func (o *Event) GetClonedApp() bool {
	if o == nil || IsNil(o.ClonedApp) {
		var ret bool
		return ret
	}
	return *o.ClonedApp
}

// GetClonedAppOk returns a tuple with the ClonedApp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Event) GetClonedAppOk() (*bool, bool) {
	if o == nil || IsNil(o.ClonedApp) {
		return nil, false
	}
	return o.ClonedApp, true
}

// HasClonedApp returns a boolean if a field has been set.
func (o *Event) HasClonedApp() bool {
	if o != nil && !IsNil(o.ClonedApp) {
		return true
	}

	return false
}

// SetClonedApp gets a reference to the given bool and assigns it to the ClonedApp field.
func (o *Event) SetClonedApp(v bool) {
	o.ClonedApp = &v
}

// GetDeveloperTools returns the DeveloperTools field value if set, zero value otherwise.
func (o *Event) GetDeveloperTools() bool {
	if o == nil || IsNil(o.DeveloperTools) {
		var ret bool
		return ret
	}
	return *o.DeveloperTools
}

// GetDeveloperToolsOk returns a tuple with the DeveloperTools field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Event) GetDeveloperToolsOk() (*bool, bool) {
	if o == nil || IsNil(o.DeveloperTools) {
		return nil, false
	}
	return o.DeveloperTools, true
}

// HasDeveloperTools returns a boolean if a field has been set.
func (o *Event) HasDeveloperTools() bool {
	if o != nil && !IsNil(o.DeveloperTools) {
		return true
	}

	return false
}

// SetDeveloperTools gets a reference to the given bool and assigns it to the DeveloperTools field.
func (o *Event) SetDeveloperTools(v bool) {
	o.DeveloperTools = &v
}

// GetEmulator returns the Emulator field value if set, zero value otherwise.
func (o *Event) GetEmulator() bool {
	if o == nil || IsNil(o.Emulator) {
		var ret bool
		return ret
	}
	return *o.Emulator
}

// GetEmulatorOk returns a tuple with the Emulator field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Event) GetEmulatorOk() (*bool, bool) {
	if o == nil || IsNil(o.Emulator) {
		return nil, false
	}
	return o.Emulator, true
}

// HasEmulator returns a boolean if a field has been set.
func (o *Event) HasEmulator() bool {
	if o != nil && !IsNil(o.Emulator) {
		return true
	}

	return false
}

// SetEmulator gets a reference to the given bool and assigns it to the Emulator field.
func (o *Event) SetEmulator(v bool) {
	o.Emulator = &v
}

// GetFactoryResetTimestamp returns the FactoryResetTimestamp field value if set, zero value otherwise.
func (o *Event) GetFactoryResetTimestamp() int64 {
	if o == nil || IsNil(o.FactoryResetTimestamp) {
		var ret int64
		return ret
	}
	return *o.FactoryResetTimestamp
}

// GetFactoryResetTimestampOk returns a tuple with the FactoryResetTimestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Event) GetFactoryResetTimestampOk() (*int64, bool) {
	if o == nil || IsNil(o.FactoryResetTimestamp) {
		return nil, false
	}
	return o.FactoryResetTimestamp, true
}

// HasFactoryResetTimestamp returns a boolean if a field has been set.
func (o *Event) HasFactoryResetTimestamp() bool {
	if o != nil && !IsNil(o.FactoryResetTimestamp) {
		return true
	}

	return false
}

// SetFactoryResetTimestamp gets a reference to the given int64 and assigns it to the FactoryResetTimestamp field.
func (o *Event) SetFactoryResetTimestamp(v int64) {
	o.FactoryResetTimestamp = &v
}

// GetFrida returns the Frida field value if set, zero value otherwise.
func (o *Event) GetFrida() bool {
	if o == nil || IsNil(o.Frida) {
		var ret bool
		return ret
	}
	return *o.Frida
}

// GetFridaOk returns a tuple with the Frida field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Event) GetFridaOk() (*bool, bool) {
	if o == nil || IsNil(o.Frida) {
		return nil, false
	}
	return o.Frida, true
}

// HasFrida returns a boolean if a field has been set.
func (o *Event) HasFrida() bool {
	if o != nil && !IsNil(o.Frida) {
		return true
	}

	return false
}

// SetFrida gets a reference to the given bool and assigns it to the Frida field.
func (o *Event) SetFrida(v bool) {
	o.Frida = &v
}

// GetIPBlocklist returns the IPBlocklist field value if set, zero value otherwise.
func (o *Event) GetIPBlocklist() IPBlockList {
	if o == nil || IsNil(o.IPBlocklist) {
		var ret IPBlockList
		return ret
	}
	return *o.IPBlocklist
}

// GetIPBlocklistOk returns a tuple with the IPBlocklist field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Event) GetIPBlocklistOk() (*IPBlockList, bool) {
	if o == nil || IsNil(o.IPBlocklist) {
		return nil, false
	}
	return o.IPBlocklist, true
}

// HasIPBlocklist returns a boolean if a field has been set.
func (o *Event) HasIPBlocklist() bool {
	if o != nil && !IsNil(o.IPBlocklist) {
		return true
	}

	return false
}

// SetIPBlocklist gets a reference to the given IPBlockList and assigns it to the IPBlocklist field.
func (o *Event) SetIPBlocklist(v IPBlockList) {
	o.IPBlocklist = &v
}

// GetIPInfo returns the IPInfo field value if set, zero value otherwise.
func (o *Event) GetIPInfo() IPInfo {
	if o == nil || IsNil(o.IPInfo) {
		var ret IPInfo
		return ret
	}
	return *o.IPInfo
}

// GetIPInfoOk returns a tuple with the IPInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Event) GetIPInfoOk() (*IPInfo, bool) {
	if o == nil || IsNil(o.IPInfo) {
		return nil, false
	}
	return o.IPInfo, true
}

// HasIPInfo returns a boolean if a field has been set.
func (o *Event) HasIPInfo() bool {
	if o != nil && !IsNil(o.IPInfo) {
		return true
	}

	return false
}

// SetIPInfo gets a reference to the given IPInfo and assigns it to the IPInfo field.
func (o *Event) SetIPInfo(v IPInfo) {
	o.IPInfo = &v
}

// GetProxy returns the Proxy field value if set, zero value otherwise.
func (o *Event) GetProxy() bool {
	if o == nil || IsNil(o.Proxy) {
		var ret bool
		return ret
	}
	return *o.Proxy
}

// GetProxyOk returns a tuple with the Proxy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Event) GetProxyOk() (*bool, bool) {
	if o == nil || IsNil(o.Proxy) {
		return nil, false
	}
	return o.Proxy, true
}

// HasProxy returns a boolean if a field has been set.
func (o *Event) HasProxy() bool {
	if o != nil && !IsNil(o.Proxy) {
		return true
	}

	return false
}

// SetProxy gets a reference to the given bool and assigns it to the Proxy field.
func (o *Event) SetProxy(v bool) {
	o.Proxy = &v
}

// GetProxyConfidence returns the ProxyConfidence field value if set, zero value otherwise.
func (o *Event) GetProxyConfidence() ProxyConfidence {
	if o == nil || IsNil(o.ProxyConfidence) {
		var ret ProxyConfidence
		return ret
	}
	return *o.ProxyConfidence
}

// GetProxyConfidenceOk returns a tuple with the ProxyConfidence field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Event) GetProxyConfidenceOk() (*ProxyConfidence, bool) {
	if o == nil || IsNil(o.ProxyConfidence) {
		return nil, false
	}
	return o.ProxyConfidence, true
}

// HasProxyConfidence returns a boolean if a field has been set.
func (o *Event) HasProxyConfidence() bool {
	if o != nil && !IsNil(o.ProxyConfidence) {
		return true
	}

	return false
}

// SetProxyConfidence gets a reference to the given ProxyConfidence and assigns it to the ProxyConfidence field.
func (o *Event) SetProxyConfidence(v ProxyConfidence) {
	o.ProxyConfidence = &v
}

// GetProxyDetails returns the ProxyDetails field value if set, zero value otherwise.
func (o *Event) GetProxyDetails() ProxyDetails {
	if o == nil || IsNil(o.ProxyDetails) {
		var ret ProxyDetails
		return ret
	}
	return *o.ProxyDetails
}

// GetProxyDetailsOk returns a tuple with the ProxyDetails field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Event) GetProxyDetailsOk() (*ProxyDetails, bool) {
	if o == nil || IsNil(o.ProxyDetails) {
		return nil, false
	}
	return o.ProxyDetails, true
}

// HasProxyDetails returns a boolean if a field has been set.
func (o *Event) HasProxyDetails() bool {
	if o != nil && !IsNil(o.ProxyDetails) {
		return true
	}

	return false
}

// SetProxyDetails gets a reference to the given ProxyDetails and assigns it to the ProxyDetails field.
func (o *Event) SetProxyDetails(v ProxyDetails) {
	o.ProxyDetails = &v
}

// GetIncognito returns the Incognito field value if set, zero value otherwise.
func (o *Event) GetIncognito() bool {
	if o == nil || IsNil(o.Incognito) {
		var ret bool
		return ret
	}
	return *o.Incognito
}

// GetIncognitoOk returns a tuple with the Incognito field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Event) GetIncognitoOk() (*bool, bool) {
	if o == nil || IsNil(o.Incognito) {
		return nil, false
	}
	return o.Incognito, true
}

// HasIncognito returns a boolean if a field has been set.
func (o *Event) HasIncognito() bool {
	if o != nil && !IsNil(o.Incognito) {
		return true
	}

	return false
}

// SetIncognito gets a reference to the given bool and assigns it to the Incognito field.
func (o *Event) SetIncognito(v bool) {
	o.Incognito = &v
}

// GetJailbroken returns the Jailbroken field value if set, zero value otherwise.
func (o *Event) GetJailbroken() bool {
	if o == nil || IsNil(o.Jailbroken) {
		var ret bool
		return ret
	}
	return *o.Jailbroken
}

// GetJailbrokenOk returns a tuple with the Jailbroken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Event) GetJailbrokenOk() (*bool, bool) {
	if o == nil || IsNil(o.Jailbroken) {
		return nil, false
	}
	return o.Jailbroken, true
}

// HasJailbroken returns a boolean if a field has been set.
func (o *Event) HasJailbroken() bool {
	if o != nil && !IsNil(o.Jailbroken) {
		return true
	}

	return false
}

// SetJailbroken gets a reference to the given bool and assigns it to the Jailbroken field.
func (o *Event) SetJailbroken(v bool) {
	o.Jailbroken = &v
}

// GetLocationSpoofing returns the LocationSpoofing field value if set, zero value otherwise.
func (o *Event) GetLocationSpoofing() bool {
	if o == nil || IsNil(o.LocationSpoofing) {
		var ret bool
		return ret
	}
	return *o.LocationSpoofing
}

// GetLocationSpoofingOk returns a tuple with the LocationSpoofing field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Event) GetLocationSpoofingOk() (*bool, bool) {
	if o == nil || IsNil(o.LocationSpoofing) {
		return nil, false
	}
	return o.LocationSpoofing, true
}

// HasLocationSpoofing returns a boolean if a field has been set.
func (o *Event) HasLocationSpoofing() bool {
	if o != nil && !IsNil(o.LocationSpoofing) {
		return true
	}

	return false
}

// SetLocationSpoofing gets a reference to the given bool and assigns it to the LocationSpoofing field.
func (o *Event) SetLocationSpoofing(v bool) {
	o.LocationSpoofing = &v
}

// GetMITMAttack returns the MITMAttack field value if set, zero value otherwise.
func (o *Event) GetMITMAttack() bool {
	if o == nil || IsNil(o.MITMAttack) {
		var ret bool
		return ret
	}
	return *o.MITMAttack
}

// GetMITMAttackOk returns a tuple with the MITMAttack field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Event) GetMITMAttackOk() (*bool, bool) {
	if o == nil || IsNil(o.MITMAttack) {
		return nil, false
	}
	return o.MITMAttack, true
}

// HasMITMAttack returns a boolean if a field has been set.
func (o *Event) HasMITMAttack() bool {
	if o != nil && !IsNil(o.MITMAttack) {
		return true
	}

	return false
}

// SetMITMAttack gets a reference to the given bool and assigns it to the MITMAttack field.
func (o *Event) SetMITMAttack(v bool) {
	o.MITMAttack = &v
}

// GetPrivacySettings returns the PrivacySettings field value if set, zero value otherwise.
func (o *Event) GetPrivacySettings() bool {
	if o == nil || IsNil(o.PrivacySettings) {
		var ret bool
		return ret
	}
	return *o.PrivacySettings
}

// GetPrivacySettingsOk returns a tuple with the PrivacySettings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Event) GetPrivacySettingsOk() (*bool, bool) {
	if o == nil || IsNil(o.PrivacySettings) {
		return nil, false
	}
	return o.PrivacySettings, true
}

// HasPrivacySettings returns a boolean if a field has been set.
func (o *Event) HasPrivacySettings() bool {
	if o != nil && !IsNil(o.PrivacySettings) {
		return true
	}

	return false
}

// SetPrivacySettings gets a reference to the given bool and assigns it to the PrivacySettings field.
func (o *Event) SetPrivacySettings(v bool) {
	o.PrivacySettings = &v
}

// GetRootApps returns the RootApps field value if set, zero value otherwise.
func (o *Event) GetRootApps() bool {
	if o == nil || IsNil(o.RootApps) {
		var ret bool
		return ret
	}
	return *o.RootApps
}

// GetRootAppsOk returns a tuple with the RootApps field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Event) GetRootAppsOk() (*bool, bool) {
	if o == nil || IsNil(o.RootApps) {
		return nil, false
	}
	return o.RootApps, true
}

// HasRootApps returns a boolean if a field has been set.
func (o *Event) HasRootApps() bool {
	if o != nil && !IsNil(o.RootApps) {
		return true
	}

	return false
}

// SetRootApps gets a reference to the given bool and assigns it to the RootApps field.
func (o *Event) SetRootApps(v bool) {
	o.RootApps = &v
}

// GetRuleAction returns the RuleAction field value if set, zero value otherwise.
func (o *Event) GetRuleAction() EventRuleAction {
	if o == nil || IsNil(o.RuleAction) {
		var ret EventRuleAction
		return ret
	}
	return *o.RuleAction
}

// GetRuleActionOk returns a tuple with the RuleAction field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Event) GetRuleActionOk() (*EventRuleAction, bool) {
	if o == nil || IsNil(o.RuleAction) {
		return nil, false
	}
	return o.RuleAction, true
}

// HasRuleAction returns a boolean if a field has been set.
func (o *Event) HasRuleAction() bool {
	if o != nil && !IsNil(o.RuleAction) {
		return true
	}

	return false
}

// SetRuleAction gets a reference to the given EventRuleAction and assigns it to the RuleAction field.
func (o *Event) SetRuleAction(v EventRuleAction) {
	o.RuleAction = &v
}

// GetSuspectScore returns the SuspectScore field value if set, zero value otherwise.
func (o *Event) GetSuspectScore() int32 {
	if o == nil || IsNil(o.SuspectScore) {
		var ret int32
		return ret
	}
	return *o.SuspectScore
}

// GetSuspectScoreOk returns a tuple with the SuspectScore field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Event) GetSuspectScoreOk() (*int32, bool) {
	if o == nil || IsNil(o.SuspectScore) {
		return nil, false
	}
	return o.SuspectScore, true
}

// HasSuspectScore returns a boolean if a field has been set.
func (o *Event) HasSuspectScore() bool {
	if o != nil && !IsNil(o.SuspectScore) {
		return true
	}

	return false
}

// SetSuspectScore gets a reference to the given int32 and assigns it to the SuspectScore field.
func (o *Event) SetSuspectScore(v int32) {
	o.SuspectScore = &v
}

// GetTampering returns the Tampering field value if set, zero value otherwise.
func (o *Event) GetTampering() bool {
	if o == nil || IsNil(o.Tampering) {
		var ret bool
		return ret
	}
	return *o.Tampering
}

// GetTamperingOk returns a tuple with the Tampering field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Event) GetTamperingOk() (*bool, bool) {
	if o == nil || IsNil(o.Tampering) {
		return nil, false
	}
	return o.Tampering, true
}

// HasTampering returns a boolean if a field has been set.
func (o *Event) HasTampering() bool {
	if o != nil && !IsNil(o.Tampering) {
		return true
	}

	return false
}

// SetTampering gets a reference to the given bool and assigns it to the Tampering field.
func (o *Event) SetTampering(v bool) {
	o.Tampering = &v
}

// GetTamperingDetails returns the TamperingDetails field value if set, zero value otherwise.
func (o *Event) GetTamperingDetails() TamperingDetails {
	if o == nil || IsNil(o.TamperingDetails) {
		var ret TamperingDetails
		return ret
	}
	return *o.TamperingDetails
}

// GetTamperingDetailsOk returns a tuple with the TamperingDetails field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Event) GetTamperingDetailsOk() (*TamperingDetails, bool) {
	if o == nil || IsNil(o.TamperingDetails) {
		return nil, false
	}
	return o.TamperingDetails, true
}

// HasTamperingDetails returns a boolean if a field has been set.
func (o *Event) HasTamperingDetails() bool {
	if o != nil && !IsNil(o.TamperingDetails) {
		return true
	}

	return false
}

// SetTamperingDetails gets a reference to the given TamperingDetails and assigns it to the TamperingDetails field.
func (o *Event) SetTamperingDetails(v TamperingDetails) {
	o.TamperingDetails = &v
}

// GetVelocity returns the Velocity field value if set, zero value otherwise.
func (o *Event) GetVelocity() Velocity {
	if o == nil || IsNil(o.Velocity) {
		var ret Velocity
		return ret
	}
	return *o.Velocity
}

// GetVelocityOk returns a tuple with the Velocity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Event) GetVelocityOk() (*Velocity, bool) {
	if o == nil || IsNil(o.Velocity) {
		return nil, false
	}
	return o.Velocity, true
}

// HasVelocity returns a boolean if a field has been set.
func (o *Event) HasVelocity() bool {
	if o != nil && !IsNil(o.Velocity) {
		return true
	}

	return false
}

// SetVelocity gets a reference to the given Velocity and assigns it to the Velocity field.
func (o *Event) SetVelocity(v Velocity) {
	o.Velocity = &v
}

// GetVirtualMachine returns the VirtualMachine field value if set, zero value otherwise.
func (o *Event) GetVirtualMachine() bool {
	if o == nil || IsNil(o.VirtualMachine) {
		var ret bool
		return ret
	}
	return *o.VirtualMachine
}

// GetVirtualMachineOk returns a tuple with the VirtualMachine field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Event) GetVirtualMachineOk() (*bool, bool) {
	if o == nil || IsNil(o.VirtualMachine) {
		return nil, false
	}
	return o.VirtualMachine, true
}

// HasVirtualMachine returns a boolean if a field has been set.
func (o *Event) HasVirtualMachine() bool {
	if o != nil && !IsNil(o.VirtualMachine) {
		return true
	}

	return false
}

// SetVirtualMachine gets a reference to the given bool and assigns it to the VirtualMachine field.
func (o *Event) SetVirtualMachine(v bool) {
	o.VirtualMachine = &v
}

// GetVPN returns the VPN field value if set, zero value otherwise.
func (o *Event) GetVPN() bool {
	if o == nil || IsNil(o.VPN) {
		var ret bool
		return ret
	}
	return *o.VPN
}

// GetVPNOk returns a tuple with the VPN field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Event) GetVPNOk() (*bool, bool) {
	if o == nil || IsNil(o.VPN) {
		return nil, false
	}
	return o.VPN, true
}

// HasVPN returns a boolean if a field has been set.
func (o *Event) HasVPN() bool {
	if o != nil && !IsNil(o.VPN) {
		return true
	}

	return false
}

// SetVPN gets a reference to the given bool and assigns it to the VPN field.
func (o *Event) SetVPN(v bool) {
	o.VPN = &v
}

// GetVPNConfidence returns the VPNConfidence field value if set, zero value otherwise.
func (o *Event) GetVPNConfidence() VPNConfidence {
	if o == nil || IsNil(o.VPNConfidence) {
		var ret VPNConfidence
		return ret
	}
	return *o.VPNConfidence
}

// GetVPNConfidenceOk returns a tuple with the VPNConfidence field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Event) GetVPNConfidenceOk() (*VPNConfidence, bool) {
	if o == nil || IsNil(o.VPNConfidence) {
		return nil, false
	}
	return o.VPNConfidence, true
}

// HasVPNConfidence returns a boolean if a field has been set.
func (o *Event) HasVPNConfidence() bool {
	if o != nil && !IsNil(o.VPNConfidence) {
		return true
	}

	return false
}

// SetVPNConfidence gets a reference to the given VPNConfidence and assigns it to the VPNConfidence field.
func (o *Event) SetVPNConfidence(v VPNConfidence) {
	o.VPNConfidence = &v
}

// GetVPNOriginTimezone returns the VPNOriginTimezone field value if set, zero value otherwise.
func (o *Event) GetVPNOriginTimezone() string {
	if o == nil || IsNil(o.VPNOriginTimezone) {
		var ret string
		return ret
	}
	return *o.VPNOriginTimezone
}

// GetVPNOriginTimezoneOk returns a tuple with the VPNOriginTimezone field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Event) GetVPNOriginTimezoneOk() (*string, bool) {
	if o == nil || IsNil(o.VPNOriginTimezone) {
		return nil, false
	}
	return o.VPNOriginTimezone, true
}

// HasVPNOriginTimezone returns a boolean if a field has been set.
func (o *Event) HasVPNOriginTimezone() bool {
	if o != nil && !IsNil(o.VPNOriginTimezone) {
		return true
	}

	return false
}

// SetVPNOriginTimezone gets a reference to the given string and assigns it to the VPNOriginTimezone field.
func (o *Event) SetVPNOriginTimezone(v string) {
	o.VPNOriginTimezone = &v
}

// GetVPNOriginCountry returns the VPNOriginCountry field value if set, zero value otherwise.
func (o *Event) GetVPNOriginCountry() string {
	if o == nil || IsNil(o.VPNOriginCountry) {
		var ret string
		return ret
	}
	return *o.VPNOriginCountry
}

// GetVPNOriginCountryOk returns a tuple with the VPNOriginCountry field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Event) GetVPNOriginCountryOk() (*string, bool) {
	if o == nil || IsNil(o.VPNOriginCountry) {
		return nil, false
	}
	return o.VPNOriginCountry, true
}

// HasVPNOriginCountry returns a boolean if a field has been set.
func (o *Event) HasVPNOriginCountry() bool {
	if o != nil && !IsNil(o.VPNOriginCountry) {
		return true
	}

	return false
}

// SetVPNOriginCountry gets a reference to the given string and assigns it to the VPNOriginCountry field.
func (o *Event) SetVPNOriginCountry(v string) {
	o.VPNOriginCountry = &v
}

// GetVPNMethods returns the VPNMethods field value if set, zero value otherwise.
func (o *Event) GetVPNMethods() VPNMethods {
	if o == nil || IsNil(o.VPNMethods) {
		var ret VPNMethods
		return ret
	}
	return *o.VPNMethods
}

// GetVPNMethodsOk returns a tuple with the VPNMethods field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Event) GetVPNMethodsOk() (*VPNMethods, bool) {
	if o == nil || IsNil(o.VPNMethods) {
		return nil, false
	}
	return o.VPNMethods, true
}

// HasVPNMethods returns a boolean if a field has been set.
func (o *Event) HasVPNMethods() bool {
	if o != nil && !IsNil(o.VPNMethods) {
		return true
	}

	return false
}

// SetVPNMethods gets a reference to the given VPNMethods and assigns it to the VPNMethods field.
func (o *Event) SetVPNMethods(v VPNMethods) {
	o.VPNMethods = &v
}

// GetHighActivityDevice returns the HighActivityDevice field value if set, zero value otherwise.
func (o *Event) GetHighActivityDevice() bool {
	if o == nil || IsNil(o.HighActivityDevice) {
		var ret bool
		return ret
	}
	return *o.HighActivityDevice
}

// GetHighActivityDeviceOk returns a tuple with the HighActivityDevice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Event) GetHighActivityDeviceOk() (*bool, bool) {
	if o == nil || IsNil(o.HighActivityDevice) {
		return nil, false
	}
	return o.HighActivityDevice, true
}

// HasHighActivityDevice returns a boolean if a field has been set.
func (o *Event) HasHighActivityDevice() bool {
	if o != nil && !IsNil(o.HighActivityDevice) {
		return true
	}

	return false
}

// SetHighActivityDevice gets a reference to the given bool and assigns it to the HighActivityDevice field.
func (o *Event) SetHighActivityDevice(v bool) {
	o.HighActivityDevice = &v
}

// GetRawDeviceAttributes returns the RawDeviceAttributes field value if set, zero value otherwise.
func (o *Event) GetRawDeviceAttributes() RawDeviceAttributes {
	if o == nil || IsNil(o.RawDeviceAttributes) {
		var ret RawDeviceAttributes
		return ret
	}
	return *o.RawDeviceAttributes
}

// GetRawDeviceAttributesOk returns a tuple with the RawDeviceAttributes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Event) GetRawDeviceAttributesOk() (*RawDeviceAttributes, bool) {
	if o == nil || IsNil(o.RawDeviceAttributes) {
		return nil, false
	}
	return o.RawDeviceAttributes, true
}

// HasRawDeviceAttributes returns a boolean if a field has been set.
func (o *Event) HasRawDeviceAttributes() bool {
	if o != nil && !IsNil(o.RawDeviceAttributes) {
		return true
	}

	return false
}

// SetRawDeviceAttributes gets a reference to the given RawDeviceAttributes and assigns it to the RawDeviceAttributes field.
func (o *Event) SetRawDeviceAttributes(v RawDeviceAttributes) {
	o.RawDeviceAttributes = &v
}

func (o Event) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Event) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["event_id"] = o.EventID
	toSerialize["timestamp"] = o.Timestamp
	if !IsNil(o.LinkedID) {
		toSerialize["linked_id"] = o.LinkedID
	}
	if !IsNil(o.EnvironmentID) {
		toSerialize["environment_id"] = o.EnvironmentID
	}
	if !IsNil(o.Suspect) {
		toSerialize["suspect"] = o.Suspect
	}
	if !IsNil(o.SDK) {
		toSerialize["sdk"] = o.SDK
	}
	if !IsNil(o.Replayed) {
		toSerialize["replayed"] = o.Replayed
	}
	if !IsNil(o.Identification) {
		toSerialize["identification"] = o.Identification
	}
	if !IsNil(o.SupplementaryIDHighRecall) {
		toSerialize["supplementary_id_high_recall"] = o.SupplementaryIDHighRecall
	}
	if !IsNil(o.Tags) {
		toSerialize["tags"] = o.Tags
	}
	if !IsNil(o.URL) {
		toSerialize["url"] = o.URL
	}
	if !IsNil(o.BundleID) {
		toSerialize["bundle_id"] = o.BundleID
	}
	if !IsNil(o.PackageName) {
		toSerialize["package_name"] = o.PackageName
	}
	if !IsNil(o.IPAddress) {
		toSerialize["ip_address"] = o.IPAddress
	}
	if !IsNil(o.UserAgent) {
		toSerialize["user_agent"] = o.UserAgent
	}
	if !IsNil(o.ClientReferrer) {
		toSerialize["client_referrer"] = o.ClientReferrer
	}
	if !IsNil(o.BrowserDetails) {
		toSerialize["browser_details"] = o.BrowserDetails
	}
	if !IsNil(o.Proximity) {
		toSerialize["proximity"] = o.Proximity
	}
	if !IsNil(o.Bot) {
		toSerialize["bot"] = o.Bot
	}
	if !IsNil(o.BotType) {
		toSerialize["bot_type"] = o.BotType
	}
	if !IsNil(o.BotInfo) {
		toSerialize["bot_info"] = o.BotInfo
	}
	if !IsNil(o.ClonedApp) {
		toSerialize["cloned_app"] = o.ClonedApp
	}
	if !IsNil(o.DeveloperTools) {
		toSerialize["developer_tools"] = o.DeveloperTools
	}
	if !IsNil(o.Emulator) {
		toSerialize["emulator"] = o.Emulator
	}
	if !IsNil(o.FactoryResetTimestamp) {
		toSerialize["factory_reset_timestamp"] = o.FactoryResetTimestamp
	}
	if !IsNil(o.Frida) {
		toSerialize["frida"] = o.Frida
	}
	if !IsNil(o.IPBlocklist) {
		toSerialize["ip_blocklist"] = o.IPBlocklist
	}
	if !IsNil(o.IPInfo) {
		toSerialize["ip_info"] = o.IPInfo
	}
	if !IsNil(o.Proxy) {
		toSerialize["proxy"] = o.Proxy
	}
	if !IsNil(o.ProxyConfidence) {
		toSerialize["proxy_confidence"] = o.ProxyConfidence
	}
	if !IsNil(o.ProxyDetails) {
		toSerialize["proxy_details"] = o.ProxyDetails
	}
	if !IsNil(o.Incognito) {
		toSerialize["incognito"] = o.Incognito
	}
	if !IsNil(o.Jailbroken) {
		toSerialize["jailbroken"] = o.Jailbroken
	}
	if !IsNil(o.LocationSpoofing) {
		toSerialize["location_spoofing"] = o.LocationSpoofing
	}
	if !IsNil(o.MITMAttack) {
		toSerialize["mitm_attack"] = o.MITMAttack
	}
	if !IsNil(o.PrivacySettings) {
		toSerialize["privacy_settings"] = o.PrivacySettings
	}
	if !IsNil(o.RootApps) {
		toSerialize["root_apps"] = o.RootApps
	}
	if !IsNil(o.RuleAction) {
		toSerialize["rule_action"] = o.RuleAction
	}
	if !IsNil(o.SuspectScore) {
		toSerialize["suspect_score"] = o.SuspectScore
	}
	if !IsNil(o.Tampering) {
		toSerialize["tampering"] = o.Tampering
	}
	if !IsNil(o.TamperingDetails) {
		toSerialize["tampering_details"] = o.TamperingDetails
	}
	if !IsNil(o.Velocity) {
		toSerialize["velocity"] = o.Velocity
	}
	if !IsNil(o.VirtualMachine) {
		toSerialize["virtual_machine"] = o.VirtualMachine
	}
	if !IsNil(o.VPN) {
		toSerialize["vpn"] = o.VPN
	}
	if !IsNil(o.VPNConfidence) {
		toSerialize["vpn_confidence"] = o.VPNConfidence
	}
	if !IsNil(o.VPNOriginTimezone) {
		toSerialize["vpn_origin_timezone"] = o.VPNOriginTimezone
	}
	if !IsNil(o.VPNOriginCountry) {
		toSerialize["vpn_origin_country"] = o.VPNOriginCountry
	}
	if !IsNil(o.VPNMethods) {
		toSerialize["vpn_methods"] = o.VPNMethods
	}
	if !IsNil(o.HighActivityDevice) {
		toSerialize["high_activity_device"] = o.HighActivityDevice
	}
	if !IsNil(o.RawDeviceAttributes) {
		toSerialize["raw_device_attributes"] = o.RawDeviceAttributes
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *Event) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"event_id",
		"timestamp",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEvent := _Event{}

	err = json.Unmarshal(data, &varEvent)

	if err != nil {
		return err
	}

	*o = Event(varEvent)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "event_id")
		delete(additionalProperties, "timestamp")
		delete(additionalProperties, "linked_id")
		delete(additionalProperties, "environment_id")
		delete(additionalProperties, "suspect")
		delete(additionalProperties, "sdk")
		delete(additionalProperties, "replayed")
		delete(additionalProperties, "identification")
		delete(additionalProperties, "supplementary_id_high_recall")
		delete(additionalProperties, "tags")
		delete(additionalProperties, "url")
		delete(additionalProperties, "bundle_id")
		delete(additionalProperties, "package_name")
		delete(additionalProperties, "ip_address")
		delete(additionalProperties, "user_agent")
		delete(additionalProperties, "client_referrer")
		delete(additionalProperties, "browser_details")
		delete(additionalProperties, "proximity")
		delete(additionalProperties, "bot")
		delete(additionalProperties, "bot_type")
		delete(additionalProperties, "bot_info")
		delete(additionalProperties, "cloned_app")
		delete(additionalProperties, "developer_tools")
		delete(additionalProperties, "emulator")
		delete(additionalProperties, "factory_reset_timestamp")
		delete(additionalProperties, "frida")
		delete(additionalProperties, "ip_blocklist")
		delete(additionalProperties, "ip_info")
		delete(additionalProperties, "proxy")
		delete(additionalProperties, "proxy_confidence")
		delete(additionalProperties, "proxy_details")
		delete(additionalProperties, "incognito")
		delete(additionalProperties, "jailbroken")
		delete(additionalProperties, "location_spoofing")
		delete(additionalProperties, "mitm_attack")
		delete(additionalProperties, "privacy_settings")
		delete(additionalProperties, "root_apps")
		delete(additionalProperties, "rule_action")
		delete(additionalProperties, "suspect_score")
		delete(additionalProperties, "tampering")
		delete(additionalProperties, "tampering_details")
		delete(additionalProperties, "velocity")
		delete(additionalProperties, "virtual_machine")
		delete(additionalProperties, "vpn")
		delete(additionalProperties, "vpn_confidence")
		delete(additionalProperties, "vpn_origin_timezone")
		delete(additionalProperties, "vpn_origin_country")
		delete(additionalProperties, "vpn_methods")
		delete(additionalProperties, "high_activity_device")
		delete(additionalProperties, "raw_device_attributes")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableEvent struct {
	value *Event
	isSet bool
}

func (v NullableEvent) Get() *Event {
	return v.value
}

func (v *NullableEvent) Set(val *Event) {
	v.value = val
	v.isSet = true
}

func (v NullableEvent) IsSet() bool {
	return v.isSet
}

func (v *NullableEvent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEvent(val *Event) *NullableEvent {
	return &NullableEvent{value: val, isSet: true}
}

func (v NullableEvent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEvent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
