/*
Server API

Fingerprint Server API allows you to get, search, and update Events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device. 

API version: 4
Contact: support@fingerprint.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fingerprint

import (
	"encoding/json"
	"fmt"
)

// RuleActionType Describes the action to take with the request.
type RuleActionType string

// List of RuleActionType
const (
    RuleActionTypeAllow RuleActionType = "allow"
    RuleActionTypeBlock RuleActionType = "block"
)

// All allowed values of RuleActionType enum
var AllowedRuleActionTypeEnumValues = []RuleActionType{
        RuleActionTypeAllow,
        RuleActionTypeBlock,
}

func (v *RuleActionType) UnmarshalJSON(src []byte) error {
var value string
err := json.Unmarshal(src, &value)
if err != nil {
return err
}
enumTypeValue := RuleActionType(value)
for _, existing := range AllowedRuleActionTypeEnumValues {
if existing == enumTypeValue {
*v = enumTypeValue
return nil
}
}

return fmt.Errorf("%+v is not a valid RuleActionType", value)
}

// NewRuleActionTypeFromValue returns a pointer to a valid RuleActionType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewRuleActionTypeFromValue(v string) (*RuleActionType, error) {
ev := RuleActionType(v)
if ev.IsValid() {
return &ev, nil
} else {
return nil, fmt.Errorf("invalid value '%v' for RuleActionType: valid values are %v", v, AllowedRuleActionTypeEnumValues)
}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v RuleActionType) IsValid() bool {
for _, existing := range AllowedRuleActionTypeEnumValues {
if existing == v {
return true
}
}
return false
}

// Ptr returns reference to RuleActionType value
func (v RuleActionType) Ptr() *RuleActionType {
return &v
}

type NullableRuleActionType struct {
value *RuleActionType
isSet bool
}

func (v NullableRuleActionType) Get() *RuleActionType {
return v.value
}

func (v *NullableRuleActionType) Set(val *RuleActionType) {
v.value = val
v.isSet = true
}

func (v NullableRuleActionType) IsSet() bool {
return v.isSet
}

func (v *NullableRuleActionType) Unset() {
v.value = nil
v.isSet = false
}

func NewNullableRuleActionType(val *RuleActionType) *NullableRuleActionType {
return &NullableRuleActionType{value: val, isSet: true}
}

func (v NullableRuleActionType) MarshalJSON() ([]byte, error) {
return json.Marshal(v.value)
}

func (v *NullableRuleActionType) UnmarshalJSON(src []byte) error {
v.isSet = true
return json.Unmarshal(src, &v.value)
}

