/*
Server API

Fingerprint Server API allows you to get, search, and update Events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device.

API version: 4
Contact: support@fingerprint.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fingerprint

import (
	"encoding/json"
)

// checks if the EventUpdate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EventUpdate{}

// EventUpdate struct for EventUpdate
type EventUpdate struct {
	// Linked Id value to assign to the existing event
	LinkedId *string `json:"linked_id,omitempty"`
	// A customer-provided value or an object that was sent with the identification request or updated later.
	Tags map[string]interface{} `json:"tags,omitempty"`
	// Suspect flag indicating observed suspicious or fraudulent event
	Suspect              *bool `json:"suspect,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _EventUpdate EventUpdate

// NewEventUpdate instantiates a new EventUpdate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEventUpdate() *EventUpdate {
	this := EventUpdate{}
	return &this
}

// NewEventUpdateWithDefaults instantiates a new EventUpdate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEventUpdateWithDefaults() *EventUpdate {
	this := EventUpdate{}
	return &this
}

// GetLinkedId returns the LinkedId field value if set, zero value otherwise.
func (o *EventUpdate) GetLinkedId() string {
	if o == nil || IsNil(o.LinkedId) {
		var ret string
		return ret
	}
	return *o.LinkedId
}

// GetLinkedIdOk returns a tuple with the LinkedId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EventUpdate) GetLinkedIdOk() (*string, bool) {
	if o == nil || IsNil(o.LinkedId) {
		return nil, false
	}
	return o.LinkedId, true
}

// HasLinkedId returns a boolean if a field has been set.
func (o *EventUpdate) HasLinkedId() bool {
	if o != nil && !IsNil(o.LinkedId) {
		return true
	}

	return false
}

// SetLinkedId gets a reference to the given string and assigns it to the LinkedId field.
func (o *EventUpdate) SetLinkedId(v string) {
	o.LinkedId = &v
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *EventUpdate) GetTags() map[string]interface{} {
	if o == nil || IsNil(o.Tags) {
		var ret map[string]interface{}
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EventUpdate) GetTagsOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Tags) {
		return map[string]interface{}{}, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *EventUpdate) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given map[string]interface{} and assigns it to the Tags field.
func (o *EventUpdate) SetTags(v map[string]interface{}) {
	o.Tags = v
}

// GetSuspect returns the Suspect field value if set, zero value otherwise.
func (o *EventUpdate) GetSuspect() bool {
	if o == nil || IsNil(o.Suspect) {
		var ret bool
		return ret
	}
	return *o.Suspect
}

// GetSuspectOk returns a tuple with the Suspect field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EventUpdate) GetSuspectOk() (*bool, bool) {
	if o == nil || IsNil(o.Suspect) {
		return nil, false
	}
	return o.Suspect, true
}

// HasSuspect returns a boolean if a field has been set.
func (o *EventUpdate) HasSuspect() bool {
	if o != nil && !IsNil(o.Suspect) {
		return true
	}

	return false
}

// SetSuspect gets a reference to the given bool and assigns it to the Suspect field.
func (o *EventUpdate) SetSuspect(v bool) {
	o.Suspect = &v
}

func (o EventUpdate) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EventUpdate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.LinkedId) {
		toSerialize["linked_id"] = o.LinkedId
	}
	if !IsNil(o.Tags) {
		toSerialize["tags"] = o.Tags
	}
	if !IsNil(o.Suspect) {
		toSerialize["suspect"] = o.Suspect
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *EventUpdate) UnmarshalJSON(data []byte) (err error) {
	varEventUpdate := _EventUpdate{}

	err = json.Unmarshal(data, &varEventUpdate)

	if err != nil {
		return err
	}

	*o = EventUpdate(varEventUpdate)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "linked_id")
		delete(additionalProperties, "tags")
		delete(additionalProperties, "suspect")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableEventUpdate struct {
	value *EventUpdate
	isSet bool
}

func (v NullableEventUpdate) Get() *EventUpdate {
	return v.value
}

func (v *NullableEventUpdate) Set(val *EventUpdate) {
	v.value = val
	v.isSet = true
}

func (v NullableEventUpdate) IsSet() bool {
	return v.isSet
}

func (v *NullableEventUpdate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEventUpdate(val *EventUpdate) *NullableEventUpdate {
	return &NullableEventUpdate{value: val, isSet: true}
}

func (v NullableEventUpdate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEventUpdate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
