/*
Server API

Fingerprint Server API allows you to get, search, and update Events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device.

API version: 4
Contact: support@fingerprint.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fingerprint

import (
	"encoding/json"
)

// checks if the Velocity type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Velocity{}

// Velocity Sums key data points for a specific `visitor_id`, `ip_address` and `linked_id` at three distinct time intervals: 5 minutes, 1 hour, and 24 hours as follows:   - Number of distinct IP addresses associated to the visitor Id. - Number of distinct linked Ids associated with the visitor Id. - Number of distinct countries associated with the visitor Id. - Number of identification events associated with the visitor Id. - Number of identification events associated with the detected IP address. - Number of distinct IP addresses associated with the provided linked Id. - Number of distinct visitor Ids associated with the provided linked Id.  The `24h` interval of `distinct_ip`, `distinct_linked_id`, `distinct_country`, `distinct_ip_by_linked_id` and `distinct_visitor_id_by_linked_id` will be omitted  if the number of `events` for the visitor Id in the last 24 hours (`events.['24h']`) is higher than 20.000.  All will not necessarily be returned in a response, some may be omitted if the  associated event does not have the required data, such as a linked_id.
type Velocity struct {
	DistinctIP                  *VelocityData `json:"distinct_ip,omitempty"`
	DistinctLinkedID            *VelocityData `json:"distinct_linked_id,omitempty"`
	DistinctCountry             *VelocityData `json:"distinct_country,omitempty"`
	Events                      *VelocityData `json:"events,omitempty"`
	IPEvents                    *VelocityData `json:"ip_events,omitempty"`
	DistinctIPByLinkedID        *VelocityData `json:"distinct_ip_by_linked_id,omitempty"`
	DistinctVisitorIDByLinkedID *VelocityData `json:"distinct_visitor_id_by_linked_id,omitempty"`
	AdditionalProperties        map[string]interface{}
}

type _Velocity Velocity

// NewVelocity instantiates a new Velocity object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVelocity() *Velocity {
	this := Velocity{}
	return &this
}

// NewVelocityWithDefaults instantiates a new Velocity object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVelocityWithDefaults() *Velocity {
	this := Velocity{}
	return &this
}

// GetDistinctIP returns the DistinctIP field value if set, zero value otherwise.
func (o *Velocity) GetDistinctIP() VelocityData {
	if o == nil || IsNil(o.DistinctIP) {
		var ret VelocityData
		return ret
	}
	return *o.DistinctIP
}

// GetDistinctIPOk returns a tuple with the DistinctIP field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Velocity) GetDistinctIPOk() (*VelocityData, bool) {
	if o == nil || IsNil(o.DistinctIP) {
		return nil, false
	}
	return o.DistinctIP, true
}

// HasDistinctIP returns a boolean if a field has been set.
func (o *Velocity) HasDistinctIP() bool {
	if o != nil && !IsNil(o.DistinctIP) {
		return true
	}

	return false
}

// SetDistinctIP gets a reference to the given VelocityData and assigns it to the DistinctIP field.
func (o *Velocity) SetDistinctIP(v VelocityData) {
	o.DistinctIP = &v
}

// GetDistinctLinkedID returns the DistinctLinkedID field value if set, zero value otherwise.
func (o *Velocity) GetDistinctLinkedID() VelocityData {
	if o == nil || IsNil(o.DistinctLinkedID) {
		var ret VelocityData
		return ret
	}
	return *o.DistinctLinkedID
}

// GetDistinctLinkedIDOk returns a tuple with the DistinctLinkedID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Velocity) GetDistinctLinkedIDOk() (*VelocityData, bool) {
	if o == nil || IsNil(o.DistinctLinkedID) {
		return nil, false
	}
	return o.DistinctLinkedID, true
}

// HasDistinctLinkedID returns a boolean if a field has been set.
func (o *Velocity) HasDistinctLinkedID() bool {
	if o != nil && !IsNil(o.DistinctLinkedID) {
		return true
	}

	return false
}

// SetDistinctLinkedID gets a reference to the given VelocityData and assigns it to the DistinctLinkedID field.
func (o *Velocity) SetDistinctLinkedID(v VelocityData) {
	o.DistinctLinkedID = &v
}

// GetDistinctCountry returns the DistinctCountry field value if set, zero value otherwise.
func (o *Velocity) GetDistinctCountry() VelocityData {
	if o == nil || IsNil(o.DistinctCountry) {
		var ret VelocityData
		return ret
	}
	return *o.DistinctCountry
}

// GetDistinctCountryOk returns a tuple with the DistinctCountry field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Velocity) GetDistinctCountryOk() (*VelocityData, bool) {
	if o == nil || IsNil(o.DistinctCountry) {
		return nil, false
	}
	return o.DistinctCountry, true
}

// HasDistinctCountry returns a boolean if a field has been set.
func (o *Velocity) HasDistinctCountry() bool {
	if o != nil && !IsNil(o.DistinctCountry) {
		return true
	}

	return false
}

// SetDistinctCountry gets a reference to the given VelocityData and assigns it to the DistinctCountry field.
func (o *Velocity) SetDistinctCountry(v VelocityData) {
	o.DistinctCountry = &v
}

// GetEvents returns the Events field value if set, zero value otherwise.
func (o *Velocity) GetEvents() VelocityData {
	if o == nil || IsNil(o.Events) {
		var ret VelocityData
		return ret
	}
	return *o.Events
}

// GetEventsOk returns a tuple with the Events field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Velocity) GetEventsOk() (*VelocityData, bool) {
	if o == nil || IsNil(o.Events) {
		return nil, false
	}
	return o.Events, true
}

// HasEvents returns a boolean if a field has been set.
func (o *Velocity) HasEvents() bool {
	if o != nil && !IsNil(o.Events) {
		return true
	}

	return false
}

// SetEvents gets a reference to the given VelocityData and assigns it to the Events field.
func (o *Velocity) SetEvents(v VelocityData) {
	o.Events = &v
}

// GetIPEvents returns the IPEvents field value if set, zero value otherwise.
func (o *Velocity) GetIPEvents() VelocityData {
	if o == nil || IsNil(o.IPEvents) {
		var ret VelocityData
		return ret
	}
	return *o.IPEvents
}

// GetIPEventsOk returns a tuple with the IPEvents field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Velocity) GetIPEventsOk() (*VelocityData, bool) {
	if o == nil || IsNil(o.IPEvents) {
		return nil, false
	}
	return o.IPEvents, true
}

// HasIPEvents returns a boolean if a field has been set.
func (o *Velocity) HasIPEvents() bool {
	if o != nil && !IsNil(o.IPEvents) {
		return true
	}

	return false
}

// SetIPEvents gets a reference to the given VelocityData and assigns it to the IPEvents field.
func (o *Velocity) SetIPEvents(v VelocityData) {
	o.IPEvents = &v
}

// GetDistinctIPByLinkedID returns the DistinctIPByLinkedID field value if set, zero value otherwise.
func (o *Velocity) GetDistinctIPByLinkedID() VelocityData {
	if o == nil || IsNil(o.DistinctIPByLinkedID) {
		var ret VelocityData
		return ret
	}
	return *o.DistinctIPByLinkedID
}

// GetDistinctIPByLinkedIDOk returns a tuple with the DistinctIPByLinkedID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Velocity) GetDistinctIPByLinkedIDOk() (*VelocityData, bool) {
	if o == nil || IsNil(o.DistinctIPByLinkedID) {
		return nil, false
	}
	return o.DistinctIPByLinkedID, true
}

// HasDistinctIPByLinkedID returns a boolean if a field has been set.
func (o *Velocity) HasDistinctIPByLinkedID() bool {
	if o != nil && !IsNil(o.DistinctIPByLinkedID) {
		return true
	}

	return false
}

// SetDistinctIPByLinkedID gets a reference to the given VelocityData and assigns it to the DistinctIPByLinkedID field.
func (o *Velocity) SetDistinctIPByLinkedID(v VelocityData) {
	o.DistinctIPByLinkedID = &v
}

// GetDistinctVisitorIDByLinkedID returns the DistinctVisitorIDByLinkedID field value if set, zero value otherwise.
func (o *Velocity) GetDistinctVisitorIDByLinkedID() VelocityData {
	if o == nil || IsNil(o.DistinctVisitorIDByLinkedID) {
		var ret VelocityData
		return ret
	}
	return *o.DistinctVisitorIDByLinkedID
}

// GetDistinctVisitorIDByLinkedIDOk returns a tuple with the DistinctVisitorIDByLinkedID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Velocity) GetDistinctVisitorIDByLinkedIDOk() (*VelocityData, bool) {
	if o == nil || IsNil(o.DistinctVisitorIDByLinkedID) {
		return nil, false
	}
	return o.DistinctVisitorIDByLinkedID, true
}

// HasDistinctVisitorIDByLinkedID returns a boolean if a field has been set.
func (o *Velocity) HasDistinctVisitorIDByLinkedID() bool {
	if o != nil && !IsNil(o.DistinctVisitorIDByLinkedID) {
		return true
	}

	return false
}

// SetDistinctVisitorIDByLinkedID gets a reference to the given VelocityData and assigns it to the DistinctVisitorIDByLinkedID field.
func (o *Velocity) SetDistinctVisitorIDByLinkedID(v VelocityData) {
	o.DistinctVisitorIDByLinkedID = &v
}

func (o Velocity) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Velocity) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DistinctIP) {
		toSerialize["distinct_ip"] = o.DistinctIP
	}
	if !IsNil(o.DistinctLinkedID) {
		toSerialize["distinct_linked_id"] = o.DistinctLinkedID
	}
	if !IsNil(o.DistinctCountry) {
		toSerialize["distinct_country"] = o.DistinctCountry
	}
	if !IsNil(o.Events) {
		toSerialize["events"] = o.Events
	}
	if !IsNil(o.IPEvents) {
		toSerialize["ip_events"] = o.IPEvents
	}
	if !IsNil(o.DistinctIPByLinkedID) {
		toSerialize["distinct_ip_by_linked_id"] = o.DistinctIPByLinkedID
	}
	if !IsNil(o.DistinctVisitorIDByLinkedID) {
		toSerialize["distinct_visitor_id_by_linked_id"] = o.DistinctVisitorIDByLinkedID
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *Velocity) UnmarshalJSON(data []byte) (err error) {
	varVelocity := _Velocity{}

	err = json.Unmarshal(data, &varVelocity)

	if err != nil {
		return err
	}

	*o = Velocity(varVelocity)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "distinct_ip")
		delete(additionalProperties, "distinct_linked_id")
		delete(additionalProperties, "distinct_country")
		delete(additionalProperties, "events")
		delete(additionalProperties, "ip_events")
		delete(additionalProperties, "distinct_ip_by_linked_id")
		delete(additionalProperties, "distinct_visitor_id_by_linked_id")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableVelocity struct {
	value *Velocity
	isSet bool
}

func (v NullableVelocity) Get() *Velocity {
	return v.value
}

func (v *NullableVelocity) Set(val *Velocity) {
	v.value = val
	v.isSet = true
}

func (v NullableVelocity) IsSet() bool {
	return v.isSet
}

func (v *NullableVelocity) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVelocity(val *Velocity) *NullableVelocity {
	return &NullableVelocity{value: val, isSet: true}
}

func (v NullableVelocity) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVelocity) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
