/*
Server API

Fingerprint Server API allows you to get, search, and update Events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device.

API version: 4
Contact: support@fingerprint.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fingerprint

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the EventSearch type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EventSearch{}

// EventSearch Contains a list of all identification events matching the specified search criteria.
type EventSearch struct {
	Events []Event `json:"events"`
	// Use this value in the `pagination_key` parameter to request the next page of search results.
	PaginationKey *string `json:"pagination_key,omitempty"`
	// This value represents the total number of events matching the search query, up to the limit provided in the `total_hits` query parameter. Only present if the `total_hits` query parameter was provided.
	TotalHits *int64 `json:"total_hits,omitempty"`
}

type _EventSearch EventSearch

// NewEventSearch instantiates a new EventSearch object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEventSearch(events []Event) *EventSearch {
	this := EventSearch{}
	this.Events = events
	return &this
}

// NewEventSearchWithDefaults instantiates a new EventSearch object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEventSearchWithDefaults() *EventSearch {
	this := EventSearch{}
	return &this
}

// GetEvents returns the Events field value
func (o *EventSearch) GetEvents() []Event {
	if o == nil {
		var ret []Event
		return ret
	}

	return o.Events
}

// GetEventsOk returns a tuple with the Events field value
// and a boolean to check if the value has been set.
func (o *EventSearch) GetEventsOk() ([]Event, bool) {
	if o == nil {
		return nil, false
	}
	return o.Events, true
}

// SetEvents sets field value
func (o *EventSearch) SetEvents(v []Event) {
	o.Events = v
}

// GetPaginationKey returns the PaginationKey field value if set, zero value otherwise.
func (o *EventSearch) GetPaginationKey() string {
	if o == nil || IsNil(o.PaginationKey) {
		var ret string
		return ret
	}
	return *o.PaginationKey
}

// GetPaginationKeyOk returns a tuple with the PaginationKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EventSearch) GetPaginationKeyOk() (*string, bool) {
	if o == nil || IsNil(o.PaginationKey) {
		return nil, false
	}
	return o.PaginationKey, true
}

// HasPaginationKey returns a boolean if a field has been set.
func (o *EventSearch) HasPaginationKey() bool {
	if o != nil && !IsNil(o.PaginationKey) {
		return true
	}

	return false
}

// SetPaginationKey gets a reference to the given string and assigns it to the PaginationKey field.
func (o *EventSearch) SetPaginationKey(v string) {
	o.PaginationKey = &v
}

// GetTotalHits returns the TotalHits field value if set, zero value otherwise.
func (o *EventSearch) GetTotalHits() int64 {
	if o == nil || IsNil(o.TotalHits) {
		var ret int64
		return ret
	}
	return *o.TotalHits
}

// GetTotalHitsOk returns a tuple with the TotalHits field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EventSearch) GetTotalHitsOk() (*int64, bool) {
	if o == nil || IsNil(o.TotalHits) {
		return nil, false
	}
	return o.TotalHits, true
}

// HasTotalHits returns a boolean if a field has been set.
func (o *EventSearch) HasTotalHits() bool {
	if o != nil && !IsNil(o.TotalHits) {
		return true
	}

	return false
}

// SetTotalHits gets a reference to the given int64 and assigns it to the TotalHits field.
func (o *EventSearch) SetTotalHits(v int64) {
	o.TotalHits = &v
}

func (o EventSearch) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EventSearch) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["events"] = o.Events
	if !IsNil(o.PaginationKey) {
		toSerialize["pagination_key"] = o.PaginationKey
	}
	if !IsNil(o.TotalHits) {
		toSerialize["total_hits"] = o.TotalHits
	}
	return toSerialize, nil
}

func (o *EventSearch) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"events",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEventSearch := _EventSearch{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEventSearch)

	if err != nil {
		return err
	}

	*o = EventSearch(varEventSearch)

	return err
}

type NullableEventSearch struct {
	value *EventSearch
	isSet bool
}

func (v NullableEventSearch) Get() *EventSearch {
	return v.value
}

func (v *NullableEventSearch) Set(val *EventSearch) {
	v.value = val
	v.isSet = true
}

func (v NullableEventSearch) IsSet() bool {
	return v.isSet
}

func (v *NullableEventSearch) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEventSearch(val *EventSearch) *NullableEventSearch {
	return &NullableEventSearch{value: val, isSet: true}
}

func (v NullableEventSearch) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEventSearch) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
