/*
Server API

Fingerprint Server API allows you to get, search, and update Events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device.

API version: 4
Contact: support@fingerprint.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fingerprint

import (
	"encoding/json"
)

// checks if the TouchSupport type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TouchSupport{}

// TouchSupport Browser-reported touch capabilities.
type TouchSupport struct {
	TouchEvent     *bool  `json:"touch_event,omitempty"`
	TouchStart     *bool  `json:"touch_start,omitempty"`
	MaxTouchPoints *int64 `json:"max_touch_points,omitempty"`
}

// NewTouchSupport instantiates a new TouchSupport object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTouchSupport() *TouchSupport {
	this := TouchSupport{}
	return &this
}

// NewTouchSupportWithDefaults instantiates a new TouchSupport object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTouchSupportWithDefaults() *TouchSupport {
	this := TouchSupport{}
	return &this
}

// GetTouchEvent returns the TouchEvent field value if set, zero value otherwise.
func (o *TouchSupport) GetTouchEvent() bool {
	if o == nil || IsNil(o.TouchEvent) {
		var ret bool
		return ret
	}
	return *o.TouchEvent
}

// GetTouchEventOk returns a tuple with the TouchEvent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TouchSupport) GetTouchEventOk() (*bool, bool) {
	if o == nil || IsNil(o.TouchEvent) {
		return nil, false
	}
	return o.TouchEvent, true
}

// HasTouchEvent returns a boolean if a field has been set.
func (o *TouchSupport) HasTouchEvent() bool {
	if o != nil && !IsNil(o.TouchEvent) {
		return true
	}

	return false
}

// SetTouchEvent gets a reference to the given bool and assigns it to the TouchEvent field.
func (o *TouchSupport) SetTouchEvent(v bool) {
	o.TouchEvent = &v
}

// GetTouchStart returns the TouchStart field value if set, zero value otherwise.
func (o *TouchSupport) GetTouchStart() bool {
	if o == nil || IsNil(o.TouchStart) {
		var ret bool
		return ret
	}
	return *o.TouchStart
}

// GetTouchStartOk returns a tuple with the TouchStart field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TouchSupport) GetTouchStartOk() (*bool, bool) {
	if o == nil || IsNil(o.TouchStart) {
		return nil, false
	}
	return o.TouchStart, true
}

// HasTouchStart returns a boolean if a field has been set.
func (o *TouchSupport) HasTouchStart() bool {
	if o != nil && !IsNil(o.TouchStart) {
		return true
	}

	return false
}

// SetTouchStart gets a reference to the given bool and assigns it to the TouchStart field.
func (o *TouchSupport) SetTouchStart(v bool) {
	o.TouchStart = &v
}

// GetMaxTouchPoints returns the MaxTouchPoints field value if set, zero value otherwise.
func (o *TouchSupport) GetMaxTouchPoints() int64 {
	if o == nil || IsNil(o.MaxTouchPoints) {
		var ret int64
		return ret
	}
	return *o.MaxTouchPoints
}

// GetMaxTouchPointsOk returns a tuple with the MaxTouchPoints field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TouchSupport) GetMaxTouchPointsOk() (*int64, bool) {
	if o == nil || IsNil(o.MaxTouchPoints) {
		return nil, false
	}
	return o.MaxTouchPoints, true
}

// HasMaxTouchPoints returns a boolean if a field has been set.
func (o *TouchSupport) HasMaxTouchPoints() bool {
	if o != nil && !IsNil(o.MaxTouchPoints) {
		return true
	}

	return false
}

// SetMaxTouchPoints gets a reference to the given int64 and assigns it to the MaxTouchPoints field.
func (o *TouchSupport) SetMaxTouchPoints(v int64) {
	o.MaxTouchPoints = &v
}

func (o TouchSupport) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TouchSupport) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TouchEvent) {
		toSerialize["touch_event"] = o.TouchEvent
	}
	if !IsNil(o.TouchStart) {
		toSerialize["touch_start"] = o.TouchStart
	}
	if !IsNil(o.MaxTouchPoints) {
		toSerialize["max_touch_points"] = o.MaxTouchPoints
	}
	return toSerialize, nil
}

type NullableTouchSupport struct {
	value *TouchSupport
	isSet bool
}

func (v NullableTouchSupport) Get() *TouchSupport {
	return v.value
}

func (v *NullableTouchSupport) Set(val *TouchSupport) {
	v.value = val
	v.isSet = true
}

func (v NullableTouchSupport) IsSet() bool {
	return v.isSet
}

func (v *NullableTouchSupport) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTouchSupport(val *TouchSupport) *NullableTouchSupport {
	return &NullableTouchSupport{value: val, isSet: true}
}

func (v NullableTouchSupport) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTouchSupport) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
