/*
Server API

Fingerprint Server API allows you to get, search, and update Events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device.

API version: 4
Contact: support@fingerprint.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fingerprint

import (
	"encoding/json"
	"fmt"
)

// checks if the EventRuleActionAllow type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EventRuleActionAllow{}

// EventRuleActionAllow Informs the client that the request should be forwarded to the origin with optional request header modifications.
type EventRuleActionAllow struct {
	Type                       RuleActionType              `json:"type"`
	RequestHeaderModifications *RequestHeaderModifications `json:"request_header_modifications,omitempty"`
	AdditionalProperties       map[string]interface{}
}

type _EventRuleActionAllow EventRuleActionAllow

// NewEventRuleActionAllow instantiates a new EventRuleActionAllow object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEventRuleActionAllow(type_ RuleActionType) *EventRuleActionAllow {
	this := EventRuleActionAllow{}
	this.Type = type_
	return &this
}

// NewEventRuleActionAllowWithDefaults instantiates a new EventRuleActionAllow object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEventRuleActionAllowWithDefaults() *EventRuleActionAllow {
	this := EventRuleActionAllow{}
	return &this
}

// GetType returns the Type field value
func (o *EventRuleActionAllow) GetType() RuleActionType {
	if o == nil {
		var ret RuleActionType
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *EventRuleActionAllow) GetTypeOk() (*RuleActionType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *EventRuleActionAllow) SetType(v RuleActionType) {
	o.Type = v
}

// GetRequestHeaderModifications returns the RequestHeaderModifications field value if set, zero value otherwise.
func (o *EventRuleActionAllow) GetRequestHeaderModifications() RequestHeaderModifications {
	if o == nil || IsNil(o.RequestHeaderModifications) {
		var ret RequestHeaderModifications
		return ret
	}
	return *o.RequestHeaderModifications
}

// GetRequestHeaderModificationsOk returns a tuple with the RequestHeaderModifications field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EventRuleActionAllow) GetRequestHeaderModificationsOk() (*RequestHeaderModifications, bool) {
	if o == nil || IsNil(o.RequestHeaderModifications) {
		return nil, false
	}
	return o.RequestHeaderModifications, true
}

// HasRequestHeaderModifications returns a boolean if a field has been set.
func (o *EventRuleActionAllow) HasRequestHeaderModifications() bool {
	if o != nil && !IsNil(o.RequestHeaderModifications) {
		return true
	}

	return false
}

// SetRequestHeaderModifications gets a reference to the given RequestHeaderModifications and assigns it to the RequestHeaderModifications field.
func (o *EventRuleActionAllow) SetRequestHeaderModifications(v RequestHeaderModifications) {
	o.RequestHeaderModifications = &v
}

func (o EventRuleActionAllow) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EventRuleActionAllow) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	if !IsNil(o.RequestHeaderModifications) {
		toSerialize["request_header_modifications"] = o.RequestHeaderModifications
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *EventRuleActionAllow) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEventRuleActionAllow := _EventRuleActionAllow{}

	err = json.Unmarshal(data, &varEventRuleActionAllow)

	if err != nil {
		return err
	}

	*o = EventRuleActionAllow(varEventRuleActionAllow)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "type")
		delete(additionalProperties, "request_header_modifications")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableEventRuleActionAllow struct {
	value *EventRuleActionAllow
	isSet bool
}

func (v NullableEventRuleActionAllow) Get() *EventRuleActionAllow {
	return v.value
}

func (v *NullableEventRuleActionAllow) Set(val *EventRuleActionAllow) {
	v.value = val
	v.isSet = true
}

func (v NullableEventRuleActionAllow) IsSet() bool {
	return v.isSet
}

func (v *NullableEventRuleActionAllow) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEventRuleActionAllow(val *EventRuleActionAllow) *NullableEventRuleActionAllow {
	return &NullableEventRuleActionAllow{value: val, isSet: true}
}

func (v NullableEventRuleActionAllow) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEventRuleActionAllow) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
