/*
Server API

Fingerprint Server API allows you to get, search, and update Events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device.

API version: 4
Contact: support@fingerprint.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fingerprint

import (
	"encoding/json"
	"fmt"
)

// checks if the RuleActionHeaderField type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RuleActionHeaderField{}

// RuleActionHeaderField struct for RuleActionHeaderField
type RuleActionHeaderField struct {
	// The header field name.
	Name string `json:"name"`
	// The value of the header field.
	Value                string `json:"value"`
	AdditionalProperties map[string]interface{}
}

type _RuleActionHeaderField RuleActionHeaderField

// NewRuleActionHeaderField instantiates a new RuleActionHeaderField object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRuleActionHeaderField(name string, value string) *RuleActionHeaderField {
	this := RuleActionHeaderField{}
	this.Name = name
	this.Value = value
	return &this
}

// NewRuleActionHeaderFieldWithDefaults instantiates a new RuleActionHeaderField object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRuleActionHeaderFieldWithDefaults() *RuleActionHeaderField {
	this := RuleActionHeaderField{}
	return &this
}

// GetName returns the Name field value
func (o *RuleActionHeaderField) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *RuleActionHeaderField) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *RuleActionHeaderField) SetName(v string) {
	o.Name = v
}

// GetValue returns the Value field value
func (o *RuleActionHeaderField) GetValue() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *RuleActionHeaderField) GetValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *RuleActionHeaderField) SetValue(v string) {
	o.Value = v
}

func (o RuleActionHeaderField) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RuleActionHeaderField) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["value"] = o.Value

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *RuleActionHeaderField) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"value",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRuleActionHeaderField := _RuleActionHeaderField{}

	err = json.Unmarshal(data, &varRuleActionHeaderField)

	if err != nil {
		return err
	}

	*o = RuleActionHeaderField(varRuleActionHeaderField)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		delete(additionalProperties, "value")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableRuleActionHeaderField struct {
	value *RuleActionHeaderField
	isSet bool
}

func (v NullableRuleActionHeaderField) Get() *RuleActionHeaderField {
	return v.value
}

func (v *NullableRuleActionHeaderField) Set(val *RuleActionHeaderField) {
	v.value = val
	v.isSet = true
}

func (v NullableRuleActionHeaderField) IsSet() bool {
	return v.isSet
}

func (v *NullableRuleActionHeaderField) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRuleActionHeaderField(val *RuleActionHeaderField) *NullableRuleActionHeaderField {
	return &NullableRuleActionHeaderField{value: val, isSet: true}
}

func (v NullableRuleActionHeaderField) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRuleActionHeaderField) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
