/*
Server API

Fingerprint Server API allows you to get, search, and update Events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device.

API version: 4
Contact: support@fingerprint.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fingerprint

import (
	"encoding/json"
)

// checks if the Emoji type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Emoji{}

// Emoji Bounding box metrics describing how the emoji glyph renders.
type Emoji struct {
	// Font family reported by the browser when drawing the emoji.
	Font   *string  `json:"font,omitempty"`
	Width  *float64 `json:"width,omitempty"`
	Height *float64 `json:"height,omitempty"`
	Top    *float64 `json:"top,omitempty"`
	Bottom *float64 `json:"bottom,omitempty"`
	Left   *float64 `json:"left,omitempty"`
	Right  *float64 `json:"right,omitempty"`
	X      *float64 `json:"x,omitempty"`
	Y      *float64 `json:"y,omitempty"`
}

// NewEmoji instantiates a new Emoji object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEmoji() *Emoji {
	this := Emoji{}
	return &this
}

// NewEmojiWithDefaults instantiates a new Emoji object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEmojiWithDefaults() *Emoji {
	this := Emoji{}
	return &this
}

// GetFont returns the Font field value if set, zero value otherwise.
func (o *Emoji) GetFont() string {
	if o == nil || IsNil(o.Font) {
		var ret string
		return ret
	}
	return *o.Font
}

// GetFontOk returns a tuple with the Font field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Emoji) GetFontOk() (*string, bool) {
	if o == nil || IsNil(o.Font) {
		return nil, false
	}
	return o.Font, true
}

// HasFont returns a boolean if a field has been set.
func (o *Emoji) HasFont() bool {
	if o != nil && !IsNil(o.Font) {
		return true
	}

	return false
}

// SetFont gets a reference to the given string and assigns it to the Font field.
func (o *Emoji) SetFont(v string) {
	o.Font = &v
}

// GetWidth returns the Width field value if set, zero value otherwise.
func (o *Emoji) GetWidth() float64 {
	if o == nil || IsNil(o.Width) {
		var ret float64
		return ret
	}
	return *o.Width
}

// GetWidthOk returns a tuple with the Width field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Emoji) GetWidthOk() (*float64, bool) {
	if o == nil || IsNil(o.Width) {
		return nil, false
	}
	return o.Width, true
}

// HasWidth returns a boolean if a field has been set.
func (o *Emoji) HasWidth() bool {
	if o != nil && !IsNil(o.Width) {
		return true
	}

	return false
}

// SetWidth gets a reference to the given float64 and assigns it to the Width field.
func (o *Emoji) SetWidth(v float64) {
	o.Width = &v
}

// GetHeight returns the Height field value if set, zero value otherwise.
func (o *Emoji) GetHeight() float64 {
	if o == nil || IsNil(o.Height) {
		var ret float64
		return ret
	}
	return *o.Height
}

// GetHeightOk returns a tuple with the Height field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Emoji) GetHeightOk() (*float64, bool) {
	if o == nil || IsNil(o.Height) {
		return nil, false
	}
	return o.Height, true
}

// HasHeight returns a boolean if a field has been set.
func (o *Emoji) HasHeight() bool {
	if o != nil && !IsNil(o.Height) {
		return true
	}

	return false
}

// SetHeight gets a reference to the given float64 and assigns it to the Height field.
func (o *Emoji) SetHeight(v float64) {
	o.Height = &v
}

// GetTop returns the Top field value if set, zero value otherwise.
func (o *Emoji) GetTop() float64 {
	if o == nil || IsNil(o.Top) {
		var ret float64
		return ret
	}
	return *o.Top
}

// GetTopOk returns a tuple with the Top field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Emoji) GetTopOk() (*float64, bool) {
	if o == nil || IsNil(o.Top) {
		return nil, false
	}
	return o.Top, true
}

// HasTop returns a boolean if a field has been set.
func (o *Emoji) HasTop() bool {
	if o != nil && !IsNil(o.Top) {
		return true
	}

	return false
}

// SetTop gets a reference to the given float64 and assigns it to the Top field.
func (o *Emoji) SetTop(v float64) {
	o.Top = &v
}

// GetBottom returns the Bottom field value if set, zero value otherwise.
func (o *Emoji) GetBottom() float64 {
	if o == nil || IsNil(o.Bottom) {
		var ret float64
		return ret
	}
	return *o.Bottom
}

// GetBottomOk returns a tuple with the Bottom field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Emoji) GetBottomOk() (*float64, bool) {
	if o == nil || IsNil(o.Bottom) {
		return nil, false
	}
	return o.Bottom, true
}

// HasBottom returns a boolean if a field has been set.
func (o *Emoji) HasBottom() bool {
	if o != nil && !IsNil(o.Bottom) {
		return true
	}

	return false
}

// SetBottom gets a reference to the given float64 and assigns it to the Bottom field.
func (o *Emoji) SetBottom(v float64) {
	o.Bottom = &v
}

// GetLeft returns the Left field value if set, zero value otherwise.
func (o *Emoji) GetLeft() float64 {
	if o == nil || IsNil(o.Left) {
		var ret float64
		return ret
	}
	return *o.Left
}

// GetLeftOk returns a tuple with the Left field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Emoji) GetLeftOk() (*float64, bool) {
	if o == nil || IsNil(o.Left) {
		return nil, false
	}
	return o.Left, true
}

// HasLeft returns a boolean if a field has been set.
func (o *Emoji) HasLeft() bool {
	if o != nil && !IsNil(o.Left) {
		return true
	}

	return false
}

// SetLeft gets a reference to the given float64 and assigns it to the Left field.
func (o *Emoji) SetLeft(v float64) {
	o.Left = &v
}

// GetRight returns the Right field value if set, zero value otherwise.
func (o *Emoji) GetRight() float64 {
	if o == nil || IsNil(o.Right) {
		var ret float64
		return ret
	}
	return *o.Right
}

// GetRightOk returns a tuple with the Right field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Emoji) GetRightOk() (*float64, bool) {
	if o == nil || IsNil(o.Right) {
		return nil, false
	}
	return o.Right, true
}

// HasRight returns a boolean if a field has been set.
func (o *Emoji) HasRight() bool {
	if o != nil && !IsNil(o.Right) {
		return true
	}

	return false
}

// SetRight gets a reference to the given float64 and assigns it to the Right field.
func (o *Emoji) SetRight(v float64) {
	o.Right = &v
}

// GetX returns the X field value if set, zero value otherwise.
func (o *Emoji) GetX() float64 {
	if o == nil || IsNil(o.X) {
		var ret float64
		return ret
	}
	return *o.X
}

// GetXOk returns a tuple with the X field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Emoji) GetXOk() (*float64, bool) {
	if o == nil || IsNil(o.X) {
		return nil, false
	}
	return o.X, true
}

// HasX returns a boolean if a field has been set.
func (o *Emoji) HasX() bool {
	if o != nil && !IsNil(o.X) {
		return true
	}

	return false
}

// SetX gets a reference to the given float64 and assigns it to the X field.
func (o *Emoji) SetX(v float64) {
	o.X = &v
}

// GetY returns the Y field value if set, zero value otherwise.
func (o *Emoji) GetY() float64 {
	if o == nil || IsNil(o.Y) {
		var ret float64
		return ret
	}
	return *o.Y
}

// GetYOk returns a tuple with the Y field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Emoji) GetYOk() (*float64, bool) {
	if o == nil || IsNil(o.Y) {
		return nil, false
	}
	return o.Y, true
}

// HasY returns a boolean if a field has been set.
func (o *Emoji) HasY() bool {
	if o != nil && !IsNil(o.Y) {
		return true
	}

	return false
}

// SetY gets a reference to the given float64 and assigns it to the Y field.
func (o *Emoji) SetY(v float64) {
	o.Y = &v
}

func (o Emoji) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Emoji) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Font) {
		toSerialize["font"] = o.Font
	}
	if !IsNil(o.Width) {
		toSerialize["width"] = o.Width
	}
	if !IsNil(o.Height) {
		toSerialize["height"] = o.Height
	}
	if !IsNil(o.Top) {
		toSerialize["top"] = o.Top
	}
	if !IsNil(o.Bottom) {
		toSerialize["bottom"] = o.Bottom
	}
	if !IsNil(o.Left) {
		toSerialize["left"] = o.Left
	}
	if !IsNil(o.Right) {
		toSerialize["right"] = o.Right
	}
	if !IsNil(o.X) {
		toSerialize["x"] = o.X
	}
	if !IsNil(o.Y) {
		toSerialize["y"] = o.Y
	}
	return toSerialize, nil
}

type NullableEmoji struct {
	value *Emoji
	isSet bool
}

func (v NullableEmoji) Get() *Emoji {
	return v.value
}

func (v *NullableEmoji) Set(val *Emoji) {
	v.value = val
	v.isSet = true
}

func (v NullableEmoji) IsSet() bool {
	return v.isSet
}

func (v *NullableEmoji) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEmoji(val *Emoji) *NullableEmoji {
	return &NullableEmoji{value: val, isSet: true}
}

func (v NullableEmoji) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEmoji) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
