/*
Server API

Fingerprint Server API allows you to get, search, and update Events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device.

API version: 4
Contact: support@fingerprint.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fingerprint

import (
	"encoding/json"
)

// checks if the RequestHeaderModifications type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RequestHeaderModifications{}

// RequestHeaderModifications The set of header modifications to apply, in the following order: remove, set, append.
type RequestHeaderModifications struct {
	// The list of headers to remove.
	Remove []string `json:"remove,omitempty"`
	// The list of headers to set, overwriting any existing headers with the same name.
	Set []RuleActionHeaderField `json:"set,omitempty"`
	// The list of headers to append.
	Append               []RuleActionHeaderField `json:"append,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _RequestHeaderModifications RequestHeaderModifications

// NewRequestHeaderModifications instantiates a new RequestHeaderModifications object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRequestHeaderModifications() *RequestHeaderModifications {
	this := RequestHeaderModifications{}
	return &this
}

// NewRequestHeaderModificationsWithDefaults instantiates a new RequestHeaderModifications object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRequestHeaderModificationsWithDefaults() *RequestHeaderModifications {
	this := RequestHeaderModifications{}
	return &this
}

// GetRemove returns the Remove field value if set, zero value otherwise.
func (o *RequestHeaderModifications) GetRemove() []string {
	if o == nil || IsNil(o.Remove) {
		var ret []string
		return ret
	}
	return o.Remove
}

// GetRemoveOk returns a tuple with the Remove field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RequestHeaderModifications) GetRemoveOk() ([]string, bool) {
	if o == nil || IsNil(o.Remove) {
		return nil, false
	}
	return o.Remove, true
}

// HasRemove returns a boolean if a field has been set.
func (o *RequestHeaderModifications) HasRemove() bool {
	if o != nil && !IsNil(o.Remove) {
		return true
	}

	return false
}

// SetRemove gets a reference to the given []string and assigns it to the Remove field.
func (o *RequestHeaderModifications) SetRemove(v []string) {
	o.Remove = v
}

// GetSet returns the Set field value if set, zero value otherwise.
func (o *RequestHeaderModifications) GetSet() []RuleActionHeaderField {
	if o == nil || IsNil(o.Set) {
		var ret []RuleActionHeaderField
		return ret
	}
	return o.Set
}

// GetSetOk returns a tuple with the Set field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RequestHeaderModifications) GetSetOk() ([]RuleActionHeaderField, bool) {
	if o == nil || IsNil(o.Set) {
		return nil, false
	}
	return o.Set, true
}

// HasSet returns a boolean if a field has been set.
func (o *RequestHeaderModifications) HasSet() bool {
	if o != nil && !IsNil(o.Set) {
		return true
	}

	return false
}

// SetSet gets a reference to the given []RuleActionHeaderField and assigns it to the Set field.
func (o *RequestHeaderModifications) SetSet(v []RuleActionHeaderField) {
	o.Set = v
}

// GetAppend returns the Append field value if set, zero value otherwise.
func (o *RequestHeaderModifications) GetAppend() []RuleActionHeaderField {
	if o == nil || IsNil(o.Append) {
		var ret []RuleActionHeaderField
		return ret
	}
	return o.Append
}

// GetAppendOk returns a tuple with the Append field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RequestHeaderModifications) GetAppendOk() ([]RuleActionHeaderField, bool) {
	if o == nil || IsNil(o.Append) {
		return nil, false
	}
	return o.Append, true
}

// HasAppend returns a boolean if a field has been set.
func (o *RequestHeaderModifications) HasAppend() bool {
	if o != nil && !IsNil(o.Append) {
		return true
	}

	return false
}

// SetAppend gets a reference to the given []RuleActionHeaderField and assigns it to the Append field.
func (o *RequestHeaderModifications) SetAppend(v []RuleActionHeaderField) {
	o.Append = v
}

func (o RequestHeaderModifications) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RequestHeaderModifications) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Remove) {
		toSerialize["remove"] = o.Remove
	}
	if !IsNil(o.Set) {
		toSerialize["set"] = o.Set
	}
	if !IsNil(o.Append) {
		toSerialize["append"] = o.Append
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *RequestHeaderModifications) UnmarshalJSON(data []byte) (err error) {
	varRequestHeaderModifications := _RequestHeaderModifications{}

	err = json.Unmarshal(data, &varRequestHeaderModifications)

	if err != nil {
		return err
	}

	*o = RequestHeaderModifications(varRequestHeaderModifications)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "remove")
		delete(additionalProperties, "set")
		delete(additionalProperties, "append")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableRequestHeaderModifications struct {
	value *RequestHeaderModifications
	isSet bool
}

func (v NullableRequestHeaderModifications) Get() *RequestHeaderModifications {
	return v.value
}

func (v *NullableRequestHeaderModifications) Set(val *RequestHeaderModifications) {
	v.value = val
	v.isSet = true
}

func (v NullableRequestHeaderModifications) IsSet() bool {
	return v.isSet
}

func (v *NullableRequestHeaderModifications) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRequestHeaderModifications(val *RequestHeaderModifications) *NullableRequestHeaderModifications {
	return &NullableRequestHeaderModifications{value: val, isSet: true}
}

func (v NullableRequestHeaderModifications) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRequestHeaderModifications) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
