/*
Server API

Fingerprint Server API allows you to get, search, and update Events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device.

API version: 4
Contact: support@fingerprint.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fingerprint

import (
	"encoding/json"
)

// checks if the Canvas type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Canvas{}

// Canvas Canvas fingerprint containing winding flag plus geometry/text hashes.
type Canvas struct {
	Winding *bool `json:"winding,omitempty"`
	// Hash of geometry rendering output or `unsupported` markers.
	Geometry *string `json:"geometry,omitempty"`
	// Hash of text rendering output or `unsupported` markers.
	Text *string `json:"text,omitempty"`
}

// NewCanvas instantiates a new Canvas object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCanvas() *Canvas {
	this := Canvas{}
	return &this
}

// NewCanvasWithDefaults instantiates a new Canvas object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCanvasWithDefaults() *Canvas {
	this := Canvas{}
	return &this
}

// GetWinding returns the Winding field value if set, zero value otherwise.
func (o *Canvas) GetWinding() bool {
	if o == nil || IsNil(o.Winding) {
		var ret bool
		return ret
	}
	return *o.Winding
}

// GetWindingOk returns a tuple with the Winding field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Canvas) GetWindingOk() (*bool, bool) {
	if o == nil || IsNil(o.Winding) {
		return nil, false
	}
	return o.Winding, true
}

// HasWinding returns a boolean if a field has been set.
func (o *Canvas) HasWinding() bool {
	if o != nil && !IsNil(o.Winding) {
		return true
	}

	return false
}

// SetWinding gets a reference to the given bool and assigns it to the Winding field.
func (o *Canvas) SetWinding(v bool) {
	o.Winding = &v
}

// GetGeometry returns the Geometry field value if set, zero value otherwise.
func (o *Canvas) GetGeometry() string {
	if o == nil || IsNil(o.Geometry) {
		var ret string
		return ret
	}
	return *o.Geometry
}

// GetGeometryOk returns a tuple with the Geometry field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Canvas) GetGeometryOk() (*string, bool) {
	if o == nil || IsNil(o.Geometry) {
		return nil, false
	}
	return o.Geometry, true
}

// HasGeometry returns a boolean if a field has been set.
func (o *Canvas) HasGeometry() bool {
	if o != nil && !IsNil(o.Geometry) {
		return true
	}

	return false
}

// SetGeometry gets a reference to the given string and assigns it to the Geometry field.
func (o *Canvas) SetGeometry(v string) {
	o.Geometry = &v
}

// GetText returns the Text field value if set, zero value otherwise.
func (o *Canvas) GetText() string {
	if o == nil || IsNil(o.Text) {
		var ret string
		return ret
	}
	return *o.Text
}

// GetTextOk returns a tuple with the Text field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Canvas) GetTextOk() (*string, bool) {
	if o == nil || IsNil(o.Text) {
		return nil, false
	}
	return o.Text, true
}

// HasText returns a boolean if a field has been set.
func (o *Canvas) HasText() bool {
	if o != nil && !IsNil(o.Text) {
		return true
	}

	return false
}

// SetText gets a reference to the given string and assigns it to the Text field.
func (o *Canvas) SetText(v string) {
	o.Text = &v
}

func (o Canvas) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Canvas) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Winding) {
		toSerialize["winding"] = o.Winding
	}
	if !IsNil(o.Geometry) {
		toSerialize["geometry"] = o.Geometry
	}
	if !IsNil(o.Text) {
		toSerialize["text"] = o.Text
	}
	return toSerialize, nil
}

type NullableCanvas struct {
	value *Canvas
	isSet bool
}

func (v NullableCanvas) Get() *Canvas {
	return v.value
}

func (v *NullableCanvas) Set(val *Canvas) {
	v.value = val
	v.isSet = true
}

func (v NullableCanvas) IsSet() bool {
	return v.isSet
}

func (v *NullableCanvas) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCanvas(val *Canvas) *NullableCanvas {
	return &NullableCanvas{value: val, isSet: true}
}

func (v NullableCanvas) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCanvas) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
