/*
Server API

Fingerprint Server API allows you to get, search, and update Events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device.

API version: 4
Contact: support@fingerprint.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fingerprint

import (
	"encoding/json"
)

// checks if the RawDeviceAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RawDeviceAttributes{}

// RawDeviceAttributes A curated subset of raw browser/device attributes that the API surface exposes. Each property contains a value or object with the data for the collected signal.
type RawDeviceAttributes struct {
	FontPreferences *FontPreferences `json:"font_preferences,omitempty"`
	Emoji           *Emoji           `json:"emoji,omitempty"`
	// List of fonts detected on the device.
	Fonts []string `json:"fonts,omitempty"`
	// Rounded amount of RAM (in gigabytes) reported by the browser.
	DeviceMemory *int32 `json:"device_memory,omitempty"`
	// Timezone identifier detected on the client.
	Timezone *string `json:"timezone,omitempty"`
	Canvas   *Canvas `json:"canvas,omitempty"`
	// Navigator languages reported by the agent including fallbacks. Each inner array represents ordered language preferences reported by different APIs.
	Languages       [][]string       `json:"languages,omitempty"`
	WebglExtensions *WebGlExtensions `json:"webgl_extensions,omitempty"`
	WebglBasics     *WebGlBasics     `json:"webgl_basics,omitempty"`
	// Current screen resolution.
	ScreenResolution []int32       `json:"screen_resolution,omitempty"`
	TouchSupport     *TouchSupport `json:"touch_support,omitempty"`
	// Navigator `oscpu` string.
	Oscpu *string `json:"oscpu,omitempty"`
	// Integer representing the CPU architecture exposed by the browser.
	Architecture *int32 `json:"architecture,omitempty"`
	// Whether the cookies are enabled in the browser.
	CookiesEnabled *bool `json:"cookies_enabled,omitempty"`
	// Number of logical CPU cores reported by the browser.
	HardwareConcurrency *int32 `json:"hardware_concurrency,omitempty"`
	// Locale derived from the Intl.DateTimeFormat API. Negative values indicate known error states. The negative statuses can be: - \"-1\": A permanent status for browsers that don't support Intl API. - \"-2\": A permanent status for browsers that don't supportDateTimeFormat constructor. - \"-3\": A permanent status for browsers in which DateTimeFormat locale is undefined or null.
	DateTimeLocale *string `json:"date_time_locale,omitempty"`
	// Navigator vendor string.
	Vendor *string `json:"vendor,omitempty"`
	// Screen color depth in bits.
	ColorDepth *int32 `json:"color_depth,omitempty"`
	// Navigator platform string.
	Platform *string `json:"platform,omitempty"`
	// Whether sessionStorage is available.
	SessionStorage *bool `json:"session_storage,omitempty"`
	// Whether localStorage is available.
	LocalStorage *bool `json:"local_storage,omitempty"`
	// AudioContext fingerprint or negative status when unavailable. The negative statuses can be: - -1: A permanent status for those browsers which are known to always suspend audio context - -2: A permanent status for browsers that don't support the signal - -3: A temporary status that means that an unexpected timeout has happened
	Audio *float64 `json:"audio,omitempty"`
	// Browser plugins reported by `navigator.plugins`.
	Plugins []PluginsInner `json:"plugins,omitempty"`
	// Whether IndexedDB is available.
	IndexedDb *bool `json:"indexed_db,omitempty"`
	// Hash of Math APIs used for entropy collection.
	Math                 *string `json:"math,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _RawDeviceAttributes RawDeviceAttributes

// NewRawDeviceAttributes instantiates a new RawDeviceAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRawDeviceAttributes() *RawDeviceAttributes {
	this := RawDeviceAttributes{}
	return &this
}

// NewRawDeviceAttributesWithDefaults instantiates a new RawDeviceAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRawDeviceAttributesWithDefaults() *RawDeviceAttributes {
	this := RawDeviceAttributes{}
	return &this
}

// GetFontPreferences returns the FontPreferences field value if set, zero value otherwise.
func (o *RawDeviceAttributes) GetFontPreferences() FontPreferences {
	if o == nil || IsNil(o.FontPreferences) {
		var ret FontPreferences
		return ret
	}
	return *o.FontPreferences
}

// GetFontPreferencesOk returns a tuple with the FontPreferences field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RawDeviceAttributes) GetFontPreferencesOk() (*FontPreferences, bool) {
	if o == nil || IsNil(o.FontPreferences) {
		return nil, false
	}
	return o.FontPreferences, true
}

// HasFontPreferences returns a boolean if a field has been set.
func (o *RawDeviceAttributes) HasFontPreferences() bool {
	if o != nil && !IsNil(o.FontPreferences) {
		return true
	}

	return false
}

// SetFontPreferences gets a reference to the given FontPreferences and assigns it to the FontPreferences field.
func (o *RawDeviceAttributes) SetFontPreferences(v FontPreferences) {
	o.FontPreferences = &v
}

// GetEmoji returns the Emoji field value if set, zero value otherwise.
func (o *RawDeviceAttributes) GetEmoji() Emoji {
	if o == nil || IsNil(o.Emoji) {
		var ret Emoji
		return ret
	}
	return *o.Emoji
}

// GetEmojiOk returns a tuple with the Emoji field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RawDeviceAttributes) GetEmojiOk() (*Emoji, bool) {
	if o == nil || IsNil(o.Emoji) {
		return nil, false
	}
	return o.Emoji, true
}

// HasEmoji returns a boolean if a field has been set.
func (o *RawDeviceAttributes) HasEmoji() bool {
	if o != nil && !IsNil(o.Emoji) {
		return true
	}

	return false
}

// SetEmoji gets a reference to the given Emoji and assigns it to the Emoji field.
func (o *RawDeviceAttributes) SetEmoji(v Emoji) {
	o.Emoji = &v
}

// GetFonts returns the Fonts field value if set, zero value otherwise.
func (o *RawDeviceAttributes) GetFonts() []string {
	if o == nil || IsNil(o.Fonts) {
		var ret []string
		return ret
	}
	return o.Fonts
}

// GetFontsOk returns a tuple with the Fonts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RawDeviceAttributes) GetFontsOk() ([]string, bool) {
	if o == nil || IsNil(o.Fonts) {
		return nil, false
	}
	return o.Fonts, true
}

// HasFonts returns a boolean if a field has been set.
func (o *RawDeviceAttributes) HasFonts() bool {
	if o != nil && !IsNil(o.Fonts) {
		return true
	}

	return false
}

// SetFonts gets a reference to the given []string and assigns it to the Fonts field.
func (o *RawDeviceAttributes) SetFonts(v []string) {
	o.Fonts = v
}

// GetDeviceMemory returns the DeviceMemory field value if set, zero value otherwise.
func (o *RawDeviceAttributes) GetDeviceMemory() int32 {
	if o == nil || IsNil(o.DeviceMemory) {
		var ret int32
		return ret
	}
	return *o.DeviceMemory
}

// GetDeviceMemoryOk returns a tuple with the DeviceMemory field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RawDeviceAttributes) GetDeviceMemoryOk() (*int32, bool) {
	if o == nil || IsNil(o.DeviceMemory) {
		return nil, false
	}
	return o.DeviceMemory, true
}

// HasDeviceMemory returns a boolean if a field has been set.
func (o *RawDeviceAttributes) HasDeviceMemory() bool {
	if o != nil && !IsNil(o.DeviceMemory) {
		return true
	}

	return false
}

// SetDeviceMemory gets a reference to the given int32 and assigns it to the DeviceMemory field.
func (o *RawDeviceAttributes) SetDeviceMemory(v int32) {
	o.DeviceMemory = &v
}

// GetTimezone returns the Timezone field value if set, zero value otherwise.
func (o *RawDeviceAttributes) GetTimezone() string {
	if o == nil || IsNil(o.Timezone) {
		var ret string
		return ret
	}
	return *o.Timezone
}

// GetTimezoneOk returns a tuple with the Timezone field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RawDeviceAttributes) GetTimezoneOk() (*string, bool) {
	if o == nil || IsNil(o.Timezone) {
		return nil, false
	}
	return o.Timezone, true
}

// HasTimezone returns a boolean if a field has been set.
func (o *RawDeviceAttributes) HasTimezone() bool {
	if o != nil && !IsNil(o.Timezone) {
		return true
	}

	return false
}

// SetTimezone gets a reference to the given string and assigns it to the Timezone field.
func (o *RawDeviceAttributes) SetTimezone(v string) {
	o.Timezone = &v
}

// GetCanvas returns the Canvas field value if set, zero value otherwise.
func (o *RawDeviceAttributes) GetCanvas() Canvas {
	if o == nil || IsNil(o.Canvas) {
		var ret Canvas
		return ret
	}
	return *o.Canvas
}

// GetCanvasOk returns a tuple with the Canvas field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RawDeviceAttributes) GetCanvasOk() (*Canvas, bool) {
	if o == nil || IsNil(o.Canvas) {
		return nil, false
	}
	return o.Canvas, true
}

// HasCanvas returns a boolean if a field has been set.
func (o *RawDeviceAttributes) HasCanvas() bool {
	if o != nil && !IsNil(o.Canvas) {
		return true
	}

	return false
}

// SetCanvas gets a reference to the given Canvas and assigns it to the Canvas field.
func (o *RawDeviceAttributes) SetCanvas(v Canvas) {
	o.Canvas = &v
}

// GetLanguages returns the Languages field value if set, zero value otherwise.
func (o *RawDeviceAttributes) GetLanguages() [][]string {
	if o == nil || IsNil(o.Languages) {
		var ret [][]string
		return ret
	}
	return o.Languages
}

// GetLanguagesOk returns a tuple with the Languages field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RawDeviceAttributes) GetLanguagesOk() ([][]string, bool) {
	if o == nil || IsNil(o.Languages) {
		return nil, false
	}
	return o.Languages, true
}

// HasLanguages returns a boolean if a field has been set.
func (o *RawDeviceAttributes) HasLanguages() bool {
	if o != nil && !IsNil(o.Languages) {
		return true
	}

	return false
}

// SetLanguages gets a reference to the given [][]string and assigns it to the Languages field.
func (o *RawDeviceAttributes) SetLanguages(v [][]string) {
	o.Languages = v
}

// GetWebglExtensions returns the WebglExtensions field value if set, zero value otherwise.
func (o *RawDeviceAttributes) GetWebglExtensions() WebGlExtensions {
	if o == nil || IsNil(o.WebglExtensions) {
		var ret WebGlExtensions
		return ret
	}
	return *o.WebglExtensions
}

// GetWebglExtensionsOk returns a tuple with the WebglExtensions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RawDeviceAttributes) GetWebglExtensionsOk() (*WebGlExtensions, bool) {
	if o == nil || IsNil(o.WebglExtensions) {
		return nil, false
	}
	return o.WebglExtensions, true
}

// HasWebglExtensions returns a boolean if a field has been set.
func (o *RawDeviceAttributes) HasWebglExtensions() bool {
	if o != nil && !IsNil(o.WebglExtensions) {
		return true
	}

	return false
}

// SetWebglExtensions gets a reference to the given WebGlExtensions and assigns it to the WebglExtensions field.
func (o *RawDeviceAttributes) SetWebglExtensions(v WebGlExtensions) {
	o.WebglExtensions = &v
}

// GetWebglBasics returns the WebglBasics field value if set, zero value otherwise.
func (o *RawDeviceAttributes) GetWebglBasics() WebGlBasics {
	if o == nil || IsNil(o.WebglBasics) {
		var ret WebGlBasics
		return ret
	}
	return *o.WebglBasics
}

// GetWebglBasicsOk returns a tuple with the WebglBasics field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RawDeviceAttributes) GetWebglBasicsOk() (*WebGlBasics, bool) {
	if o == nil || IsNil(o.WebglBasics) {
		return nil, false
	}
	return o.WebglBasics, true
}

// HasWebglBasics returns a boolean if a field has been set.
func (o *RawDeviceAttributes) HasWebglBasics() bool {
	if o != nil && !IsNil(o.WebglBasics) {
		return true
	}

	return false
}

// SetWebglBasics gets a reference to the given WebGlBasics and assigns it to the WebglBasics field.
func (o *RawDeviceAttributes) SetWebglBasics(v WebGlBasics) {
	o.WebglBasics = &v
}

// GetScreenResolution returns the ScreenResolution field value if set, zero value otherwise.
func (o *RawDeviceAttributes) GetScreenResolution() []int32 {
	if o == nil || IsNil(o.ScreenResolution) {
		var ret []int32
		return ret
	}
	return o.ScreenResolution
}

// GetScreenResolutionOk returns a tuple with the ScreenResolution field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RawDeviceAttributes) GetScreenResolutionOk() ([]int32, bool) {
	if o == nil || IsNil(o.ScreenResolution) {
		return nil, false
	}
	return o.ScreenResolution, true
}

// HasScreenResolution returns a boolean if a field has been set.
func (o *RawDeviceAttributes) HasScreenResolution() bool {
	if o != nil && !IsNil(o.ScreenResolution) {
		return true
	}

	return false
}

// SetScreenResolution gets a reference to the given []int32 and assigns it to the ScreenResolution field.
func (o *RawDeviceAttributes) SetScreenResolution(v []int32) {
	o.ScreenResolution = v
}

// GetTouchSupport returns the TouchSupport field value if set, zero value otherwise.
func (o *RawDeviceAttributes) GetTouchSupport() TouchSupport {
	if o == nil || IsNil(o.TouchSupport) {
		var ret TouchSupport
		return ret
	}
	return *o.TouchSupport
}

// GetTouchSupportOk returns a tuple with the TouchSupport field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RawDeviceAttributes) GetTouchSupportOk() (*TouchSupport, bool) {
	if o == nil || IsNil(o.TouchSupport) {
		return nil, false
	}
	return o.TouchSupport, true
}

// HasTouchSupport returns a boolean if a field has been set.
func (o *RawDeviceAttributes) HasTouchSupport() bool {
	if o != nil && !IsNil(o.TouchSupport) {
		return true
	}

	return false
}

// SetTouchSupport gets a reference to the given TouchSupport and assigns it to the TouchSupport field.
func (o *RawDeviceAttributes) SetTouchSupport(v TouchSupport) {
	o.TouchSupport = &v
}

// GetOscpu returns the Oscpu field value if set, zero value otherwise.
func (o *RawDeviceAttributes) GetOscpu() string {
	if o == nil || IsNil(o.Oscpu) {
		var ret string
		return ret
	}
	return *o.Oscpu
}

// GetOscpuOk returns a tuple with the Oscpu field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RawDeviceAttributes) GetOscpuOk() (*string, bool) {
	if o == nil || IsNil(o.Oscpu) {
		return nil, false
	}
	return o.Oscpu, true
}

// HasOscpu returns a boolean if a field has been set.
func (o *RawDeviceAttributes) HasOscpu() bool {
	if o != nil && !IsNil(o.Oscpu) {
		return true
	}

	return false
}

// SetOscpu gets a reference to the given string and assigns it to the Oscpu field.
func (o *RawDeviceAttributes) SetOscpu(v string) {
	o.Oscpu = &v
}

// GetArchitecture returns the Architecture field value if set, zero value otherwise.
func (o *RawDeviceAttributes) GetArchitecture() int32 {
	if o == nil || IsNil(o.Architecture) {
		var ret int32
		return ret
	}
	return *o.Architecture
}

// GetArchitectureOk returns a tuple with the Architecture field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RawDeviceAttributes) GetArchitectureOk() (*int32, bool) {
	if o == nil || IsNil(o.Architecture) {
		return nil, false
	}
	return o.Architecture, true
}

// HasArchitecture returns a boolean if a field has been set.
func (o *RawDeviceAttributes) HasArchitecture() bool {
	if o != nil && !IsNil(o.Architecture) {
		return true
	}

	return false
}

// SetArchitecture gets a reference to the given int32 and assigns it to the Architecture field.
func (o *RawDeviceAttributes) SetArchitecture(v int32) {
	o.Architecture = &v
}

// GetCookiesEnabled returns the CookiesEnabled field value if set, zero value otherwise.
func (o *RawDeviceAttributes) GetCookiesEnabled() bool {
	if o == nil || IsNil(o.CookiesEnabled) {
		var ret bool
		return ret
	}
	return *o.CookiesEnabled
}

// GetCookiesEnabledOk returns a tuple with the CookiesEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RawDeviceAttributes) GetCookiesEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.CookiesEnabled) {
		return nil, false
	}
	return o.CookiesEnabled, true
}

// HasCookiesEnabled returns a boolean if a field has been set.
func (o *RawDeviceAttributes) HasCookiesEnabled() bool {
	if o != nil && !IsNil(o.CookiesEnabled) {
		return true
	}

	return false
}

// SetCookiesEnabled gets a reference to the given bool and assigns it to the CookiesEnabled field.
func (o *RawDeviceAttributes) SetCookiesEnabled(v bool) {
	o.CookiesEnabled = &v
}

// GetHardwareConcurrency returns the HardwareConcurrency field value if set, zero value otherwise.
func (o *RawDeviceAttributes) GetHardwareConcurrency() int32 {
	if o == nil || IsNil(o.HardwareConcurrency) {
		var ret int32
		return ret
	}
	return *o.HardwareConcurrency
}

// GetHardwareConcurrencyOk returns a tuple with the HardwareConcurrency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RawDeviceAttributes) GetHardwareConcurrencyOk() (*int32, bool) {
	if o == nil || IsNil(o.HardwareConcurrency) {
		return nil, false
	}
	return o.HardwareConcurrency, true
}

// HasHardwareConcurrency returns a boolean if a field has been set.
func (o *RawDeviceAttributes) HasHardwareConcurrency() bool {
	if o != nil && !IsNil(o.HardwareConcurrency) {
		return true
	}

	return false
}

// SetHardwareConcurrency gets a reference to the given int32 and assigns it to the HardwareConcurrency field.
func (o *RawDeviceAttributes) SetHardwareConcurrency(v int32) {
	o.HardwareConcurrency = &v
}

// GetDateTimeLocale returns the DateTimeLocale field value if set, zero value otherwise.
func (o *RawDeviceAttributes) GetDateTimeLocale() string {
	if o == nil || IsNil(o.DateTimeLocale) {
		var ret string
		return ret
	}
	return *o.DateTimeLocale
}

// GetDateTimeLocaleOk returns a tuple with the DateTimeLocale field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RawDeviceAttributes) GetDateTimeLocaleOk() (*string, bool) {
	if o == nil || IsNil(o.DateTimeLocale) {
		return nil, false
	}
	return o.DateTimeLocale, true
}

// HasDateTimeLocale returns a boolean if a field has been set.
func (o *RawDeviceAttributes) HasDateTimeLocale() bool {
	if o != nil && !IsNil(o.DateTimeLocale) {
		return true
	}

	return false
}

// SetDateTimeLocale gets a reference to the given string and assigns it to the DateTimeLocale field.
func (o *RawDeviceAttributes) SetDateTimeLocale(v string) {
	o.DateTimeLocale = &v
}

// GetVendor returns the Vendor field value if set, zero value otherwise.
func (o *RawDeviceAttributes) GetVendor() string {
	if o == nil || IsNil(o.Vendor) {
		var ret string
		return ret
	}
	return *o.Vendor
}

// GetVendorOk returns a tuple with the Vendor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RawDeviceAttributes) GetVendorOk() (*string, bool) {
	if o == nil || IsNil(o.Vendor) {
		return nil, false
	}
	return o.Vendor, true
}

// HasVendor returns a boolean if a field has been set.
func (o *RawDeviceAttributes) HasVendor() bool {
	if o != nil && !IsNil(o.Vendor) {
		return true
	}

	return false
}

// SetVendor gets a reference to the given string and assigns it to the Vendor field.
func (o *RawDeviceAttributes) SetVendor(v string) {
	o.Vendor = &v
}

// GetColorDepth returns the ColorDepth field value if set, zero value otherwise.
func (o *RawDeviceAttributes) GetColorDepth() int32 {
	if o == nil || IsNil(o.ColorDepth) {
		var ret int32
		return ret
	}
	return *o.ColorDepth
}

// GetColorDepthOk returns a tuple with the ColorDepth field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RawDeviceAttributes) GetColorDepthOk() (*int32, bool) {
	if o == nil || IsNil(o.ColorDepth) {
		return nil, false
	}
	return o.ColorDepth, true
}

// HasColorDepth returns a boolean if a field has been set.
func (o *RawDeviceAttributes) HasColorDepth() bool {
	if o != nil && !IsNil(o.ColorDepth) {
		return true
	}

	return false
}

// SetColorDepth gets a reference to the given int32 and assigns it to the ColorDepth field.
func (o *RawDeviceAttributes) SetColorDepth(v int32) {
	o.ColorDepth = &v
}

// GetPlatform returns the Platform field value if set, zero value otherwise.
func (o *RawDeviceAttributes) GetPlatform() string {
	if o == nil || IsNil(o.Platform) {
		var ret string
		return ret
	}
	return *o.Platform
}

// GetPlatformOk returns a tuple with the Platform field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RawDeviceAttributes) GetPlatformOk() (*string, bool) {
	if o == nil || IsNil(o.Platform) {
		return nil, false
	}
	return o.Platform, true
}

// HasPlatform returns a boolean if a field has been set.
func (o *RawDeviceAttributes) HasPlatform() bool {
	if o != nil && !IsNil(o.Platform) {
		return true
	}

	return false
}

// SetPlatform gets a reference to the given string and assigns it to the Platform field.
func (o *RawDeviceAttributes) SetPlatform(v string) {
	o.Platform = &v
}

// GetSessionStorage returns the SessionStorage field value if set, zero value otherwise.
func (o *RawDeviceAttributes) GetSessionStorage() bool {
	if o == nil || IsNil(o.SessionStorage) {
		var ret bool
		return ret
	}
	return *o.SessionStorage
}

// GetSessionStorageOk returns a tuple with the SessionStorage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RawDeviceAttributes) GetSessionStorageOk() (*bool, bool) {
	if o == nil || IsNil(o.SessionStorage) {
		return nil, false
	}
	return o.SessionStorage, true
}

// HasSessionStorage returns a boolean if a field has been set.
func (o *RawDeviceAttributes) HasSessionStorage() bool {
	if o != nil && !IsNil(o.SessionStorage) {
		return true
	}

	return false
}

// SetSessionStorage gets a reference to the given bool and assigns it to the SessionStorage field.
func (o *RawDeviceAttributes) SetSessionStorage(v bool) {
	o.SessionStorage = &v
}

// GetLocalStorage returns the LocalStorage field value if set, zero value otherwise.
func (o *RawDeviceAttributes) GetLocalStorage() bool {
	if o == nil || IsNil(o.LocalStorage) {
		var ret bool
		return ret
	}
	return *o.LocalStorage
}

// GetLocalStorageOk returns a tuple with the LocalStorage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RawDeviceAttributes) GetLocalStorageOk() (*bool, bool) {
	if o == nil || IsNil(o.LocalStorage) {
		return nil, false
	}
	return o.LocalStorage, true
}

// HasLocalStorage returns a boolean if a field has been set.
func (o *RawDeviceAttributes) HasLocalStorage() bool {
	if o != nil && !IsNil(o.LocalStorage) {
		return true
	}

	return false
}

// SetLocalStorage gets a reference to the given bool and assigns it to the LocalStorage field.
func (o *RawDeviceAttributes) SetLocalStorage(v bool) {
	o.LocalStorage = &v
}

// GetAudio returns the Audio field value if set, zero value otherwise.
func (o *RawDeviceAttributes) GetAudio() float64 {
	if o == nil || IsNil(o.Audio) {
		var ret float64
		return ret
	}
	return *o.Audio
}

// GetAudioOk returns a tuple with the Audio field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RawDeviceAttributes) GetAudioOk() (*float64, bool) {
	if o == nil || IsNil(o.Audio) {
		return nil, false
	}
	return o.Audio, true
}

// HasAudio returns a boolean if a field has been set.
func (o *RawDeviceAttributes) HasAudio() bool {
	if o != nil && !IsNil(o.Audio) {
		return true
	}

	return false
}

// SetAudio gets a reference to the given float64 and assigns it to the Audio field.
func (o *RawDeviceAttributes) SetAudio(v float64) {
	o.Audio = &v
}

// GetPlugins returns the Plugins field value if set, zero value otherwise.
func (o *RawDeviceAttributes) GetPlugins() []PluginsInner {
	if o == nil || IsNil(o.Plugins) {
		var ret []PluginsInner
		return ret
	}
	return o.Plugins
}

// GetPluginsOk returns a tuple with the Plugins field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RawDeviceAttributes) GetPluginsOk() ([]PluginsInner, bool) {
	if o == nil || IsNil(o.Plugins) {
		return nil, false
	}
	return o.Plugins, true
}

// HasPlugins returns a boolean if a field has been set.
func (o *RawDeviceAttributes) HasPlugins() bool {
	if o != nil && !IsNil(o.Plugins) {
		return true
	}

	return false
}

// SetPlugins gets a reference to the given []PluginsInner and assigns it to the Plugins field.
func (o *RawDeviceAttributes) SetPlugins(v []PluginsInner) {
	o.Plugins = v
}

// GetIndexedDb returns the IndexedDb field value if set, zero value otherwise.
func (o *RawDeviceAttributes) GetIndexedDb() bool {
	if o == nil || IsNil(o.IndexedDb) {
		var ret bool
		return ret
	}
	return *o.IndexedDb
}

// GetIndexedDbOk returns a tuple with the IndexedDb field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RawDeviceAttributes) GetIndexedDbOk() (*bool, bool) {
	if o == nil || IsNil(o.IndexedDb) {
		return nil, false
	}
	return o.IndexedDb, true
}

// HasIndexedDb returns a boolean if a field has been set.
func (o *RawDeviceAttributes) HasIndexedDb() bool {
	if o != nil && !IsNil(o.IndexedDb) {
		return true
	}

	return false
}

// SetIndexedDb gets a reference to the given bool and assigns it to the IndexedDb field.
func (o *RawDeviceAttributes) SetIndexedDb(v bool) {
	o.IndexedDb = &v
}

// GetMath returns the Math field value if set, zero value otherwise.
func (o *RawDeviceAttributes) GetMath() string {
	if o == nil || IsNil(o.Math) {
		var ret string
		return ret
	}
	return *o.Math
}

// GetMathOk returns a tuple with the Math field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RawDeviceAttributes) GetMathOk() (*string, bool) {
	if o == nil || IsNil(o.Math) {
		return nil, false
	}
	return o.Math, true
}

// HasMath returns a boolean if a field has been set.
func (o *RawDeviceAttributes) HasMath() bool {
	if o != nil && !IsNil(o.Math) {
		return true
	}

	return false
}

// SetMath gets a reference to the given string and assigns it to the Math field.
func (o *RawDeviceAttributes) SetMath(v string) {
	o.Math = &v
}

func (o RawDeviceAttributes) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RawDeviceAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.FontPreferences) {
		toSerialize["font_preferences"] = o.FontPreferences
	}
	if !IsNil(o.Emoji) {
		toSerialize["emoji"] = o.Emoji
	}
	if !IsNil(o.Fonts) {
		toSerialize["fonts"] = o.Fonts
	}
	if !IsNil(o.DeviceMemory) {
		toSerialize["device_memory"] = o.DeviceMemory
	}
	if !IsNil(o.Timezone) {
		toSerialize["timezone"] = o.Timezone
	}
	if !IsNil(o.Canvas) {
		toSerialize["canvas"] = o.Canvas
	}
	if !IsNil(o.Languages) {
		toSerialize["languages"] = o.Languages
	}
	if !IsNil(o.WebglExtensions) {
		toSerialize["webgl_extensions"] = o.WebglExtensions
	}
	if !IsNil(o.WebglBasics) {
		toSerialize["webgl_basics"] = o.WebglBasics
	}
	if !IsNil(o.ScreenResolution) {
		toSerialize["screen_resolution"] = o.ScreenResolution
	}
	if !IsNil(o.TouchSupport) {
		toSerialize["touch_support"] = o.TouchSupport
	}
	if !IsNil(o.Oscpu) {
		toSerialize["oscpu"] = o.Oscpu
	}
	if !IsNil(o.Architecture) {
		toSerialize["architecture"] = o.Architecture
	}
	if !IsNil(o.CookiesEnabled) {
		toSerialize["cookies_enabled"] = o.CookiesEnabled
	}
	if !IsNil(o.HardwareConcurrency) {
		toSerialize["hardware_concurrency"] = o.HardwareConcurrency
	}
	if !IsNil(o.DateTimeLocale) {
		toSerialize["date_time_locale"] = o.DateTimeLocale
	}
	if !IsNil(o.Vendor) {
		toSerialize["vendor"] = o.Vendor
	}
	if !IsNil(o.ColorDepth) {
		toSerialize["color_depth"] = o.ColorDepth
	}
	if !IsNil(o.Platform) {
		toSerialize["platform"] = o.Platform
	}
	if !IsNil(o.SessionStorage) {
		toSerialize["session_storage"] = o.SessionStorage
	}
	if !IsNil(o.LocalStorage) {
		toSerialize["local_storage"] = o.LocalStorage
	}
	if !IsNil(o.Audio) {
		toSerialize["audio"] = o.Audio
	}
	if !IsNil(o.Plugins) {
		toSerialize["plugins"] = o.Plugins
	}
	if !IsNil(o.IndexedDb) {
		toSerialize["indexed_db"] = o.IndexedDb
	}
	if !IsNil(o.Math) {
		toSerialize["math"] = o.Math
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *RawDeviceAttributes) UnmarshalJSON(data []byte) (err error) {
	varRawDeviceAttributes := _RawDeviceAttributes{}

	err = json.Unmarshal(data, &varRawDeviceAttributes)

	if err != nil {
		return err
	}

	*o = RawDeviceAttributes(varRawDeviceAttributes)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "font_preferences")
		delete(additionalProperties, "emoji")
		delete(additionalProperties, "fonts")
		delete(additionalProperties, "device_memory")
		delete(additionalProperties, "timezone")
		delete(additionalProperties, "canvas")
		delete(additionalProperties, "languages")
		delete(additionalProperties, "webgl_extensions")
		delete(additionalProperties, "webgl_basics")
		delete(additionalProperties, "screen_resolution")
		delete(additionalProperties, "touch_support")
		delete(additionalProperties, "oscpu")
		delete(additionalProperties, "architecture")
		delete(additionalProperties, "cookies_enabled")
		delete(additionalProperties, "hardware_concurrency")
		delete(additionalProperties, "date_time_locale")
		delete(additionalProperties, "vendor")
		delete(additionalProperties, "color_depth")
		delete(additionalProperties, "platform")
		delete(additionalProperties, "session_storage")
		delete(additionalProperties, "local_storage")
		delete(additionalProperties, "audio")
		delete(additionalProperties, "plugins")
		delete(additionalProperties, "indexed_db")
		delete(additionalProperties, "math")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableRawDeviceAttributes struct {
	value *RawDeviceAttributes
	isSet bool
}

func (v NullableRawDeviceAttributes) Get() *RawDeviceAttributes {
	return v.value
}

func (v *NullableRawDeviceAttributes) Set(val *RawDeviceAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableRawDeviceAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableRawDeviceAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRawDeviceAttributes(val *RawDeviceAttributes) *NullableRawDeviceAttributes {
	return &NullableRawDeviceAttributes{value: val, isSet: true}
}

func (v NullableRawDeviceAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRawDeviceAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
