/*
Server API

Fingerprint Server API allows you to get, search, and update Events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device.

API version: 4
Contact: support@fingerprint.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fingerprint

import (
	"encoding/json"
)

// checks if the WebGlExtensions type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WebGlExtensions{}

// WebGlExtensions Hashes of WebGL context attributes and extension support.
type WebGlExtensions struct {
	ContextAttributes     *string  `json:"context_attributes,omitempty"`
	Parameters            *string  `json:"parameters,omitempty"`
	ShaderPrecisions      *string  `json:"shader_precisions,omitempty"`
	Extensions            *string  `json:"extensions,omitempty"`
	ExtensionParameters   *string  `json:"extension_parameters,omitempty"`
	UnsupportedExtensions []string `json:"unsupported_extensions,omitempty"`
}

// NewWebGlExtensions instantiates a new WebGlExtensions object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWebGlExtensions() *WebGlExtensions {
	this := WebGlExtensions{}
	return &this
}

// NewWebGlExtensionsWithDefaults instantiates a new WebGlExtensions object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWebGlExtensionsWithDefaults() *WebGlExtensions {
	this := WebGlExtensions{}
	return &this
}

// GetContextAttributes returns the ContextAttributes field value if set, zero value otherwise.
func (o *WebGlExtensions) GetContextAttributes() string {
	if o == nil || IsNil(o.ContextAttributes) {
		var ret string
		return ret
	}
	return *o.ContextAttributes
}

// GetContextAttributesOk returns a tuple with the ContextAttributes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebGlExtensions) GetContextAttributesOk() (*string, bool) {
	if o == nil || IsNil(o.ContextAttributes) {
		return nil, false
	}
	return o.ContextAttributes, true
}

// HasContextAttributes returns a boolean if a field has been set.
func (o *WebGlExtensions) HasContextAttributes() bool {
	if o != nil && !IsNil(o.ContextAttributes) {
		return true
	}

	return false
}

// SetContextAttributes gets a reference to the given string and assigns it to the ContextAttributes field.
func (o *WebGlExtensions) SetContextAttributes(v string) {
	o.ContextAttributes = &v
}

// GetParameters returns the Parameters field value if set, zero value otherwise.
func (o *WebGlExtensions) GetParameters() string {
	if o == nil || IsNil(o.Parameters) {
		var ret string
		return ret
	}
	return *o.Parameters
}

// GetParametersOk returns a tuple with the Parameters field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebGlExtensions) GetParametersOk() (*string, bool) {
	if o == nil || IsNil(o.Parameters) {
		return nil, false
	}
	return o.Parameters, true
}

// HasParameters returns a boolean if a field has been set.
func (o *WebGlExtensions) HasParameters() bool {
	if o != nil && !IsNil(o.Parameters) {
		return true
	}

	return false
}

// SetParameters gets a reference to the given string and assigns it to the Parameters field.
func (o *WebGlExtensions) SetParameters(v string) {
	o.Parameters = &v
}

// GetShaderPrecisions returns the ShaderPrecisions field value if set, zero value otherwise.
func (o *WebGlExtensions) GetShaderPrecisions() string {
	if o == nil || IsNil(o.ShaderPrecisions) {
		var ret string
		return ret
	}
	return *o.ShaderPrecisions
}

// GetShaderPrecisionsOk returns a tuple with the ShaderPrecisions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebGlExtensions) GetShaderPrecisionsOk() (*string, bool) {
	if o == nil || IsNil(o.ShaderPrecisions) {
		return nil, false
	}
	return o.ShaderPrecisions, true
}

// HasShaderPrecisions returns a boolean if a field has been set.
func (o *WebGlExtensions) HasShaderPrecisions() bool {
	if o != nil && !IsNil(o.ShaderPrecisions) {
		return true
	}

	return false
}

// SetShaderPrecisions gets a reference to the given string and assigns it to the ShaderPrecisions field.
func (o *WebGlExtensions) SetShaderPrecisions(v string) {
	o.ShaderPrecisions = &v
}

// GetExtensions returns the Extensions field value if set, zero value otherwise.
func (o *WebGlExtensions) GetExtensions() string {
	if o == nil || IsNil(o.Extensions) {
		var ret string
		return ret
	}
	return *o.Extensions
}

// GetExtensionsOk returns a tuple with the Extensions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebGlExtensions) GetExtensionsOk() (*string, bool) {
	if o == nil || IsNil(o.Extensions) {
		return nil, false
	}
	return o.Extensions, true
}

// HasExtensions returns a boolean if a field has been set.
func (o *WebGlExtensions) HasExtensions() bool {
	if o != nil && !IsNil(o.Extensions) {
		return true
	}

	return false
}

// SetExtensions gets a reference to the given string and assigns it to the Extensions field.
func (o *WebGlExtensions) SetExtensions(v string) {
	o.Extensions = &v
}

// GetExtensionParameters returns the ExtensionParameters field value if set, zero value otherwise.
func (o *WebGlExtensions) GetExtensionParameters() string {
	if o == nil || IsNil(o.ExtensionParameters) {
		var ret string
		return ret
	}
	return *o.ExtensionParameters
}

// GetExtensionParametersOk returns a tuple with the ExtensionParameters field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebGlExtensions) GetExtensionParametersOk() (*string, bool) {
	if o == nil || IsNil(o.ExtensionParameters) {
		return nil, false
	}
	return o.ExtensionParameters, true
}

// HasExtensionParameters returns a boolean if a field has been set.
func (o *WebGlExtensions) HasExtensionParameters() bool {
	if o != nil && !IsNil(o.ExtensionParameters) {
		return true
	}

	return false
}

// SetExtensionParameters gets a reference to the given string and assigns it to the ExtensionParameters field.
func (o *WebGlExtensions) SetExtensionParameters(v string) {
	o.ExtensionParameters = &v
}

// GetUnsupportedExtensions returns the UnsupportedExtensions field value if set, zero value otherwise.
func (o *WebGlExtensions) GetUnsupportedExtensions() []string {
	if o == nil || IsNil(o.UnsupportedExtensions) {
		var ret []string
		return ret
	}
	return o.UnsupportedExtensions
}

// GetUnsupportedExtensionsOk returns a tuple with the UnsupportedExtensions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebGlExtensions) GetUnsupportedExtensionsOk() ([]string, bool) {
	if o == nil || IsNil(o.UnsupportedExtensions) {
		return nil, false
	}
	return o.UnsupportedExtensions, true
}

// HasUnsupportedExtensions returns a boolean if a field has been set.
func (o *WebGlExtensions) HasUnsupportedExtensions() bool {
	if o != nil && !IsNil(o.UnsupportedExtensions) {
		return true
	}

	return false
}

// SetUnsupportedExtensions gets a reference to the given []string and assigns it to the UnsupportedExtensions field.
func (o *WebGlExtensions) SetUnsupportedExtensions(v []string) {
	o.UnsupportedExtensions = v
}

func (o WebGlExtensions) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WebGlExtensions) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ContextAttributes) {
		toSerialize["context_attributes"] = o.ContextAttributes
	}
	if !IsNil(o.Parameters) {
		toSerialize["parameters"] = o.Parameters
	}
	if !IsNil(o.ShaderPrecisions) {
		toSerialize["shader_precisions"] = o.ShaderPrecisions
	}
	if !IsNil(o.Extensions) {
		toSerialize["extensions"] = o.Extensions
	}
	if !IsNil(o.ExtensionParameters) {
		toSerialize["extension_parameters"] = o.ExtensionParameters
	}
	if !IsNil(o.UnsupportedExtensions) {
		toSerialize["unsupported_extensions"] = o.UnsupportedExtensions
	}
	return toSerialize, nil
}

type NullableWebGlExtensions struct {
	value *WebGlExtensions
	isSet bool
}

func (v NullableWebGlExtensions) Get() *WebGlExtensions {
	return v.value
}

func (v *NullableWebGlExtensions) Set(val *WebGlExtensions) {
	v.value = val
	v.isSet = true
}

func (v NullableWebGlExtensions) IsSet() bool {
	return v.isSet
}

func (v *NullableWebGlExtensions) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebGlExtensions(val *WebGlExtensions) *NullableWebGlExtensions {
	return &NullableWebGlExtensions{value: val, isSet: true}
}

func (v NullableWebGlExtensions) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebGlExtensions) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
