/*
Server API

Fingerprint Server API allows you to get, search, and update Events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device.

API version: 4
Contact: support@fingerprint.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fingerprint

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the EventRuleAction type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EventRuleAction{}

// EventRuleAction Describes the action the client should take, according to the rule in the ruleset that matched the event. When getting an event by event ID, the rule_action will only be included when the ruleset_id query parameter is specified.
type EventRuleAction struct {
	// The ID of the evaluated ruleset.
	RulesetId string `json:"ruleset_id"`
	// The ID of the rule that matched the identification event.
	RuleId *string `json:"rule_id,omitempty"`
	// The expression of the rule that matched the identification event.
	RuleExpression *string `json:"rule_expression,omitempty"`
}

type _EventRuleAction EventRuleAction

// NewEventRuleAction instantiates a new EventRuleAction object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEventRuleAction(rulesetId string) *EventRuleAction {
	this := EventRuleAction{}
	this.RulesetId = rulesetId
	return &this
}

// NewEventRuleActionWithDefaults instantiates a new EventRuleAction object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEventRuleActionWithDefaults() *EventRuleAction {
	this := EventRuleAction{}
	return &this
}

// GetRulesetId returns the RulesetId field value
func (o *EventRuleAction) GetRulesetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RulesetId
}

// GetRulesetIdOk returns a tuple with the RulesetId field value
// and a boolean to check if the value has been set.
func (o *EventRuleAction) GetRulesetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RulesetId, true
}

// SetRulesetId sets field value
func (o *EventRuleAction) SetRulesetId(v string) {
	o.RulesetId = v
}

// GetRuleId returns the RuleId field value if set, zero value otherwise.
func (o *EventRuleAction) GetRuleId() string {
	if o == nil || IsNil(o.RuleId) {
		var ret string
		return ret
	}
	return *o.RuleId
}

// GetRuleIdOk returns a tuple with the RuleId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EventRuleAction) GetRuleIdOk() (*string, bool) {
	if o == nil || IsNil(o.RuleId) {
		return nil, false
	}
	return o.RuleId, true
}

// HasRuleId returns a boolean if a field has been set.
func (o *EventRuleAction) HasRuleId() bool {
	if o != nil && !IsNil(o.RuleId) {
		return true
	}

	return false
}

// SetRuleId gets a reference to the given string and assigns it to the RuleId field.
func (o *EventRuleAction) SetRuleId(v string) {
	o.RuleId = &v
}

// GetRuleExpression returns the RuleExpression field value if set, zero value otherwise.
func (o *EventRuleAction) GetRuleExpression() string {
	if o == nil || IsNil(o.RuleExpression) {
		var ret string
		return ret
	}
	return *o.RuleExpression
}

// GetRuleExpressionOk returns a tuple with the RuleExpression field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EventRuleAction) GetRuleExpressionOk() (*string, bool) {
	if o == nil || IsNil(o.RuleExpression) {
		return nil, false
	}
	return o.RuleExpression, true
}

// HasRuleExpression returns a boolean if a field has been set.
func (o *EventRuleAction) HasRuleExpression() bool {
	if o != nil && !IsNil(o.RuleExpression) {
		return true
	}

	return false
}

// SetRuleExpression gets a reference to the given string and assigns it to the RuleExpression field.
func (o *EventRuleAction) SetRuleExpression(v string) {
	o.RuleExpression = &v
}

func (o EventRuleAction) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EventRuleAction) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["ruleset_id"] = o.RulesetId
	if !IsNil(o.RuleId) {
		toSerialize["rule_id"] = o.RuleId
	}
	if !IsNil(o.RuleExpression) {
		toSerialize["rule_expression"] = o.RuleExpression
	}
	return toSerialize, nil
}

func (o *EventRuleAction) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"ruleset_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEventRuleAction := _EventRuleAction{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEventRuleAction)

	if err != nil {
		return err
	}

	*o = EventRuleAction(varEventRuleAction)

	return err
}

type NullableEventRuleAction struct {
	value *EventRuleAction
	isSet bool
}

func (v NullableEventRuleAction) Get() *EventRuleAction {
	return v.value
}

func (v *NullableEventRuleAction) Set(val *EventRuleAction) {
	v.value = val
	v.isSet = true
}

func (v NullableEventRuleAction) IsSet() bool {
	return v.isSet
}

func (v *NullableEventRuleAction) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEventRuleAction(val *EventRuleAction) *NullableEventRuleAction {
	return &NullableEventRuleAction{value: val, isSet: true}
}

func (v NullableEventRuleAction) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEventRuleAction) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
