/*
Server API

Fingerprint Server API allows you to get, search, and update Events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device. 

API version: 4
Contact: support@fingerprint.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fingerprint

import (
	"encoding/json"
	"fmt"
)

// checks if the EventRuleActionBlock type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EventRuleActionBlock{}

// EventRuleActionBlock Informs the client the request should be blocked using the response described by this rule action.
type EventRuleActionBlock struct {
	Type RuleActionType `json:"type"`
	// A valid HTTP status code.
	StatusCode *int32 `json:"status_code,omitempty"`
	// A list of headers to send.
	Headers []RuleActionHeaderField `json:"headers,omitempty"`
	// The response body to send to the client.
	Body *string `json:"body,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _EventRuleActionBlock EventRuleActionBlock

// NewEventRuleActionBlock instantiates a new EventRuleActionBlock object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEventRuleActionBlock(type_ RuleActionType) *EventRuleActionBlock {
	this := EventRuleActionBlock{}
	this.Type = type_
	return &this
}

// NewEventRuleActionBlockWithDefaults instantiates a new EventRuleActionBlock object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEventRuleActionBlockWithDefaults() *EventRuleActionBlock {
	this := EventRuleActionBlock{}
	return &this
}

// GetType returns the Type field value
func (o *EventRuleActionBlock) GetType() RuleActionType {
	if o == nil {
		var ret RuleActionType
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *EventRuleActionBlock) GetTypeOk() (*RuleActionType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *EventRuleActionBlock) SetType(v RuleActionType) {
	o.Type = v
}

// GetStatusCode returns the StatusCode field value if set, zero value otherwise.
func (o *EventRuleActionBlock) GetStatusCode() int32 {
	if o == nil || IsNil(o.StatusCode) {
		var ret int32
		return ret
	}
	return *o.StatusCode
}

// GetStatusCodeOk returns a tuple with the StatusCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EventRuleActionBlock) GetStatusCodeOk() (*int32, bool) {
	if o == nil || IsNil(o.StatusCode) {
		return nil, false
	}
	return o.StatusCode, true
}

// HasStatusCode returns a boolean if a field has been set.
func (o *EventRuleActionBlock) HasStatusCode() bool {
	if o != nil && !IsNil(o.StatusCode) {
		return true
	}

	return false
}

// SetStatusCode gets a reference to the given int32 and assigns it to the StatusCode field.
func (o *EventRuleActionBlock) SetStatusCode(v int32) {
	o.StatusCode = &v
}

// GetHeaders returns the Headers field value if set, zero value otherwise.
func (o *EventRuleActionBlock) GetHeaders() []RuleActionHeaderField {
	if o == nil || IsNil(o.Headers) {
		var ret []RuleActionHeaderField
		return ret
	}
	return o.Headers
}

// GetHeadersOk returns a tuple with the Headers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EventRuleActionBlock) GetHeadersOk() ([]RuleActionHeaderField, bool) {
	if o == nil || IsNil(o.Headers) {
		return nil, false
	}
	return o.Headers, true
}

// HasHeaders returns a boolean if a field has been set.
func (o *EventRuleActionBlock) HasHeaders() bool {
	if o != nil && !IsNil(o.Headers) {
		return true
	}

	return false
}

// SetHeaders gets a reference to the given []RuleActionHeaderField and assigns it to the Headers field.
func (o *EventRuleActionBlock) SetHeaders(v []RuleActionHeaderField) {
	o.Headers = v
}

// GetBody returns the Body field value if set, zero value otherwise.
func (o *EventRuleActionBlock) GetBody() string {
	if o == nil || IsNil(o.Body) {
		var ret string
		return ret
	}
	return *o.Body
}

// GetBodyOk returns a tuple with the Body field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EventRuleActionBlock) GetBodyOk() (*string, bool) {
	if o == nil || IsNil(o.Body) {
		return nil, false
	}
	return o.Body, true
}

// HasBody returns a boolean if a field has been set.
func (o *EventRuleActionBlock) HasBody() bool {
	if o != nil && !IsNil(o.Body) {
		return true
	}

	return false
}

// SetBody gets a reference to the given string and assigns it to the Body field.
func (o *EventRuleActionBlock) SetBody(v string) {
	o.Body = &v
}

func (o EventRuleActionBlock) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EventRuleActionBlock) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	if !IsNil(o.StatusCode) {
		toSerialize["status_code"] = o.StatusCode
	}
	if !IsNil(o.Headers) {
		toSerialize["headers"] = o.Headers
	}
	if !IsNil(o.Body) {
		toSerialize["body"] = o.Body
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *EventRuleActionBlock) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEventRuleActionBlock := _EventRuleActionBlock{}

	err = json.Unmarshal(data, &varEventRuleActionBlock)

	if err != nil {
		return err
	}

	*o = EventRuleActionBlock(varEventRuleActionBlock)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "type")
		delete(additionalProperties, "status_code")
		delete(additionalProperties, "headers")
		delete(additionalProperties, "body")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableEventRuleActionBlock struct {
	value *EventRuleActionBlock
	isSet bool
}

func (v NullableEventRuleActionBlock) Get() *EventRuleActionBlock {
	return v.value
}

func (v *NullableEventRuleActionBlock) Set(val *EventRuleActionBlock) {
	v.value = val
	v.isSet = true
}

func (v NullableEventRuleActionBlock) IsSet() bool {
	return v.isSet
}

func (v *NullableEventRuleActionBlock) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEventRuleActionBlock(val *EventRuleActionBlock) *NullableEventRuleActionBlock {
	return &NullableEventRuleActionBlock{value: val, isSet: true}
}

func (v NullableEventRuleActionBlock) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEventRuleActionBlock) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


