/*
Server API

Fingerprint Server API allows you to get, search, and update Events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device. 

API version: 4
Contact: support@fingerprint.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fingerprint

import (
	"encoding/json"
	"fmt"
)

// checks if the VelocityData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VelocityData{}

// VelocityData Is absent if the velocity data could not be generated for the visitor Id. 
type VelocityData struct {
	// Count for the last 5 minutes of velocity data, from the time of the event. 
	Var5Minutes int32 `json:"5_minutes"`
	// Count for the last 1 hour of velocity data, from the time of the event. 
	Var1Hour int32 `json:"1_hour"`
	// The `24_hours` interval of `distinct_ip`, `distinct_linked_id`, `distinct_country`, `distinct_ip_by_linked_id` and `distinct_visitor_id_by_linked_id` will be omitted if the number of `events` for the visitor Id in the last 24 hours (`events.['24_hours']`) is higher than 20.000. 
	Var24Hours *int32 `json:"24_hours,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _VelocityData VelocityData

// NewVelocityData instantiates a new VelocityData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVelocityData(var5Minutes int32, var1Hour int32) *VelocityData {
	this := VelocityData{}
	this.Var5Minutes = var5Minutes
	this.Var1Hour = var1Hour
	return &this
}

// NewVelocityDataWithDefaults instantiates a new VelocityData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVelocityDataWithDefaults() *VelocityData {
	this := VelocityData{}
	return &this
}

// GetVar5Minutes returns the Var5Minutes field value
func (o *VelocityData) GetVar5Minutes() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Var5Minutes
}

// GetVar5MinutesOk returns a tuple with the Var5Minutes field value
// and a boolean to check if the value has been set.
func (o *VelocityData) GetVar5MinutesOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Var5Minutes, true
}

// SetVar5Minutes sets field value
func (o *VelocityData) SetVar5Minutes(v int32) {
	o.Var5Minutes = v
}

// GetVar1Hour returns the Var1Hour field value
func (o *VelocityData) GetVar1Hour() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Var1Hour
}

// GetVar1HourOk returns a tuple with the Var1Hour field value
// and a boolean to check if the value has been set.
func (o *VelocityData) GetVar1HourOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Var1Hour, true
}

// SetVar1Hour sets field value
func (o *VelocityData) SetVar1Hour(v int32) {
	o.Var1Hour = v
}

// GetVar24Hours returns the Var24Hours field value if set, zero value otherwise.
func (o *VelocityData) GetVar24Hours() int32 {
	if o == nil || IsNil(o.Var24Hours) {
		var ret int32
		return ret
	}
	return *o.Var24Hours
}

// GetVar24HoursOk returns a tuple with the Var24Hours field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VelocityData) GetVar24HoursOk() (*int32, bool) {
	if o == nil || IsNil(o.Var24Hours) {
		return nil, false
	}
	return o.Var24Hours, true
}

// HasVar24Hours returns a boolean if a field has been set.
func (o *VelocityData) HasVar24Hours() bool {
	if o != nil && !IsNil(o.Var24Hours) {
		return true
	}

	return false
}

// SetVar24Hours gets a reference to the given int32 and assigns it to the Var24Hours field.
func (o *VelocityData) SetVar24Hours(v int32) {
	o.Var24Hours = &v
}

func (o VelocityData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VelocityData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["5_minutes"] = o.Var5Minutes
	toSerialize["1_hour"] = o.Var1Hour
	if !IsNil(o.Var24Hours) {
		toSerialize["24_hours"] = o.Var24Hours
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *VelocityData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"5_minutes",
		"1_hour",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varVelocityData := _VelocityData{}

	err = json.Unmarshal(data, &varVelocityData)

	if err != nil {
		return err
	}

	*o = VelocityData(varVelocityData)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "5_minutes")
		delete(additionalProperties, "1_hour")
		delete(additionalProperties, "24_hours")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableVelocityData struct {
	value *VelocityData
	isSet bool
}

func (v NullableVelocityData) Get() *VelocityData {
	return v.value
}

func (v *NullableVelocityData) Set(val *VelocityData) {
	v.value = val
	v.isSet = true
}

func (v NullableVelocityData) IsSet() bool {
	return v.isSet
}

func (v *NullableVelocityData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVelocityData(val *VelocityData) *NullableVelocityData {
	return &NullableVelocityData{value: val, isSet: true}
}

func (v NullableVelocityData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVelocityData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


