/*
Server API

Fingerprint Server API allows you to get, search, and update Events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device.

API version: 4
Contact: support@fingerprint.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fingerprint

import (
	"encoding/json"
)

// checks if the WebGlBasics type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WebGlBasics{}

// WebGlBasics Render and vendor strings reported by the WebGL context.
type WebGlBasics struct {
	Version                *string `json:"version,omitempty"`
	Vendor                 *string `json:"vendor,omitempty"`
	VendorUnmasked         *string `json:"vendor_unmasked,omitempty"`
	Renderer               *string `json:"renderer,omitempty"`
	RendererUnmasked       *string `json:"renderer_unmasked,omitempty"`
	ShadingLanguageVersion *string `json:"shading_language_version,omitempty"`
}

// NewWebGlBasics instantiates a new WebGlBasics object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWebGlBasics() *WebGlBasics {
	this := WebGlBasics{}
	return &this
}

// NewWebGlBasicsWithDefaults instantiates a new WebGlBasics object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWebGlBasicsWithDefaults() *WebGlBasics {
	this := WebGlBasics{}
	return &this
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *WebGlBasics) GetVersion() string {
	if o == nil || IsNil(o.Version) {
		var ret string
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebGlBasics) GetVersionOk() (*string, bool) {
	if o == nil || IsNil(o.Version) {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *WebGlBasics) HasVersion() bool {
	if o != nil && !IsNil(o.Version) {
		return true
	}

	return false
}

// SetVersion gets a reference to the given string and assigns it to the Version field.
func (o *WebGlBasics) SetVersion(v string) {
	o.Version = &v
}

// GetVendor returns the Vendor field value if set, zero value otherwise.
func (o *WebGlBasics) GetVendor() string {
	if o == nil || IsNil(o.Vendor) {
		var ret string
		return ret
	}
	return *o.Vendor
}

// GetVendorOk returns a tuple with the Vendor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebGlBasics) GetVendorOk() (*string, bool) {
	if o == nil || IsNil(o.Vendor) {
		return nil, false
	}
	return o.Vendor, true
}

// HasVendor returns a boolean if a field has been set.
func (o *WebGlBasics) HasVendor() bool {
	if o != nil && !IsNil(o.Vendor) {
		return true
	}

	return false
}

// SetVendor gets a reference to the given string and assigns it to the Vendor field.
func (o *WebGlBasics) SetVendor(v string) {
	o.Vendor = &v
}

// GetVendorUnmasked returns the VendorUnmasked field value if set, zero value otherwise.
func (o *WebGlBasics) GetVendorUnmasked() string {
	if o == nil || IsNil(o.VendorUnmasked) {
		var ret string
		return ret
	}
	return *o.VendorUnmasked
}

// GetVendorUnmaskedOk returns a tuple with the VendorUnmasked field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebGlBasics) GetVendorUnmaskedOk() (*string, bool) {
	if o == nil || IsNil(o.VendorUnmasked) {
		return nil, false
	}
	return o.VendorUnmasked, true
}

// HasVendorUnmasked returns a boolean if a field has been set.
func (o *WebGlBasics) HasVendorUnmasked() bool {
	if o != nil && !IsNil(o.VendorUnmasked) {
		return true
	}

	return false
}

// SetVendorUnmasked gets a reference to the given string and assigns it to the VendorUnmasked field.
func (o *WebGlBasics) SetVendorUnmasked(v string) {
	o.VendorUnmasked = &v
}

// GetRenderer returns the Renderer field value if set, zero value otherwise.
func (o *WebGlBasics) GetRenderer() string {
	if o == nil || IsNil(o.Renderer) {
		var ret string
		return ret
	}
	return *o.Renderer
}

// GetRendererOk returns a tuple with the Renderer field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebGlBasics) GetRendererOk() (*string, bool) {
	if o == nil || IsNil(o.Renderer) {
		return nil, false
	}
	return o.Renderer, true
}

// HasRenderer returns a boolean if a field has been set.
func (o *WebGlBasics) HasRenderer() bool {
	if o != nil && !IsNil(o.Renderer) {
		return true
	}

	return false
}

// SetRenderer gets a reference to the given string and assigns it to the Renderer field.
func (o *WebGlBasics) SetRenderer(v string) {
	o.Renderer = &v
}

// GetRendererUnmasked returns the RendererUnmasked field value if set, zero value otherwise.
func (o *WebGlBasics) GetRendererUnmasked() string {
	if o == nil || IsNil(o.RendererUnmasked) {
		var ret string
		return ret
	}
	return *o.RendererUnmasked
}

// GetRendererUnmaskedOk returns a tuple with the RendererUnmasked field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebGlBasics) GetRendererUnmaskedOk() (*string, bool) {
	if o == nil || IsNil(o.RendererUnmasked) {
		return nil, false
	}
	return o.RendererUnmasked, true
}

// HasRendererUnmasked returns a boolean if a field has been set.
func (o *WebGlBasics) HasRendererUnmasked() bool {
	if o != nil && !IsNil(o.RendererUnmasked) {
		return true
	}

	return false
}

// SetRendererUnmasked gets a reference to the given string and assigns it to the RendererUnmasked field.
func (o *WebGlBasics) SetRendererUnmasked(v string) {
	o.RendererUnmasked = &v
}

// GetShadingLanguageVersion returns the ShadingLanguageVersion field value if set, zero value otherwise.
func (o *WebGlBasics) GetShadingLanguageVersion() string {
	if o == nil || IsNil(o.ShadingLanguageVersion) {
		var ret string
		return ret
	}
	return *o.ShadingLanguageVersion
}

// GetShadingLanguageVersionOk returns a tuple with the ShadingLanguageVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebGlBasics) GetShadingLanguageVersionOk() (*string, bool) {
	if o == nil || IsNil(o.ShadingLanguageVersion) {
		return nil, false
	}
	return o.ShadingLanguageVersion, true
}

// HasShadingLanguageVersion returns a boolean if a field has been set.
func (o *WebGlBasics) HasShadingLanguageVersion() bool {
	if o != nil && !IsNil(o.ShadingLanguageVersion) {
		return true
	}

	return false
}

// SetShadingLanguageVersion gets a reference to the given string and assigns it to the ShadingLanguageVersion field.
func (o *WebGlBasics) SetShadingLanguageVersion(v string) {
	o.ShadingLanguageVersion = &v
}

func (o WebGlBasics) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WebGlBasics) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Version) {
		toSerialize["version"] = o.Version
	}
	if !IsNil(o.Vendor) {
		toSerialize["vendor"] = o.Vendor
	}
	if !IsNil(o.VendorUnmasked) {
		toSerialize["vendor_unmasked"] = o.VendorUnmasked
	}
	if !IsNil(o.Renderer) {
		toSerialize["renderer"] = o.Renderer
	}
	if !IsNil(o.RendererUnmasked) {
		toSerialize["renderer_unmasked"] = o.RendererUnmasked
	}
	if !IsNil(o.ShadingLanguageVersion) {
		toSerialize["shading_language_version"] = o.ShadingLanguageVersion
	}
	return toSerialize, nil
}

type NullableWebGlBasics struct {
	value *WebGlBasics
	isSet bool
}

func (v NullableWebGlBasics) Get() *WebGlBasics {
	return v.value
}

func (v *NullableWebGlBasics) Set(val *WebGlBasics) {
	v.value = val
	v.isSet = true
}

func (v NullableWebGlBasics) IsSet() bool {
	return v.isSet
}

func (v *NullableWebGlBasics) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebGlBasics(val *WebGlBasics) *NullableWebGlBasics {
	return &NullableWebGlBasics{value: val, isSet: true}
}

func (v NullableWebGlBasics) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebGlBasics) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
