/*
Server API

Fingerprint Server API allows you to get, search, and update Events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device.

API version: 4
Contact: support@fingerprint.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fingerprint

import (
	"encoding/json"
)

// checks if the IPBlockList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IPBlockList{}

// IPBlockList struct for IPBlockList
type IPBlockList struct {
	// IP address was part of a known email spam attack (SMTP).
	EmailSpam *bool `json:"email_spam,omitempty"`
	// IP address was part of a known network attack (SSH/HTTPS).
	AttackSource *bool `json:"attack_source,omitempty"`
	// IP address was part of known TOR network activity.
	TorNode              *bool `json:"tor_node,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _IPBlockList IPBlockList

// NewIPBlockList instantiates a new IPBlockList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIPBlockList() *IPBlockList {
	this := IPBlockList{}
	return &this
}

// NewIPBlockListWithDefaults instantiates a new IPBlockList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIPBlockListWithDefaults() *IPBlockList {
	this := IPBlockList{}
	return &this
}

// GetEmailSpam returns the EmailSpam field value if set, zero value otherwise.
func (o *IPBlockList) GetEmailSpam() bool {
	if o == nil || IsNil(o.EmailSpam) {
		var ret bool
		return ret
	}
	return *o.EmailSpam
}

// GetEmailSpamOk returns a tuple with the EmailSpam field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IPBlockList) GetEmailSpamOk() (*bool, bool) {
	if o == nil || IsNil(o.EmailSpam) {
		return nil, false
	}
	return o.EmailSpam, true
}

// HasEmailSpam returns a boolean if a field has been set.
func (o *IPBlockList) HasEmailSpam() bool {
	if o != nil && !IsNil(o.EmailSpam) {
		return true
	}

	return false
}

// SetEmailSpam gets a reference to the given bool and assigns it to the EmailSpam field.
func (o *IPBlockList) SetEmailSpam(v bool) {
	o.EmailSpam = &v
}

// GetAttackSource returns the AttackSource field value if set, zero value otherwise.
func (o *IPBlockList) GetAttackSource() bool {
	if o == nil || IsNil(o.AttackSource) {
		var ret bool
		return ret
	}
	return *o.AttackSource
}

// GetAttackSourceOk returns a tuple with the AttackSource field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IPBlockList) GetAttackSourceOk() (*bool, bool) {
	if o == nil || IsNil(o.AttackSource) {
		return nil, false
	}
	return o.AttackSource, true
}

// HasAttackSource returns a boolean if a field has been set.
func (o *IPBlockList) HasAttackSource() bool {
	if o != nil && !IsNil(o.AttackSource) {
		return true
	}

	return false
}

// SetAttackSource gets a reference to the given bool and assigns it to the AttackSource field.
func (o *IPBlockList) SetAttackSource(v bool) {
	o.AttackSource = &v
}

// GetTorNode returns the TorNode field value if set, zero value otherwise.
func (o *IPBlockList) GetTorNode() bool {
	if o == nil || IsNil(o.TorNode) {
		var ret bool
		return ret
	}
	return *o.TorNode
}

// GetTorNodeOk returns a tuple with the TorNode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IPBlockList) GetTorNodeOk() (*bool, bool) {
	if o == nil || IsNil(o.TorNode) {
		return nil, false
	}
	return o.TorNode, true
}

// HasTorNode returns a boolean if a field has been set.
func (o *IPBlockList) HasTorNode() bool {
	if o != nil && !IsNil(o.TorNode) {
		return true
	}

	return false
}

// SetTorNode gets a reference to the given bool and assigns it to the TorNode field.
func (o *IPBlockList) SetTorNode(v bool) {
	o.TorNode = &v
}

func (o IPBlockList) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IPBlockList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.EmailSpam) {
		toSerialize["email_spam"] = o.EmailSpam
	}
	if !IsNil(o.AttackSource) {
		toSerialize["attack_source"] = o.AttackSource
	}
	if !IsNil(o.TorNode) {
		toSerialize["tor_node"] = o.TorNode
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *IPBlockList) UnmarshalJSON(data []byte) (err error) {
	varIPBlockList := _IPBlockList{}

	err = json.Unmarshal(data, &varIPBlockList)

	if err != nil {
		return err
	}

	*o = IPBlockList(varIPBlockList)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "email_spam")
		delete(additionalProperties, "attack_source")
		delete(additionalProperties, "tor_node")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableIPBlockList struct {
	value *IPBlockList
	isSet bool
}

func (v NullableIPBlockList) Get() *IPBlockList {
	return v.value
}

func (v *NullableIPBlockList) Set(val *IPBlockList) {
	v.value = val
	v.isSet = true
}

func (v NullableIPBlockList) IsSet() bool {
	return v.isSet
}

func (v *NullableIPBlockList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIPBlockList(val *IPBlockList) *NullableIPBlockList {
	return &NullableIPBlockList{value: val, isSet: true}
}

func (v NullableIPBlockList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIPBlockList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
